In [30]:
from ExploreData import ExploreData
import numpy as np
import pandas as pd
# import matplotlib.pyplot as plt
# import seaborn as sns
import typing as t
from textwrap import dedent

## Data

In [31]:
import os
print(os.getcwd())
data_path = '../data/'

c:\Users\BrandonBrown\repos\basketball\scripts

In [32]:
df_game_detail = pd.read_csv(data_path + 'box_score_traditional_data.csv')

## Impute missing values in labels with 0
counting_stats_cols = ['MIN', 'FGM', 'FGA', 'FG3M', 'FG3A', 'FTM', 'FTA', 'REB', 'AST', 'STL', 'BLK', 'TO', 'PTS', 'PLUS_MINUS', 'PF']
df_game_detail[counting_stats_cols] = df_game_detail[counting_stats_cols].fillna(0)
df_game_detail

display(df_game_detail.sample(5))
print(df_game_detail.shape)

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,NICKNAME,START_POSITION,COMMENT,MIN,...,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS,PLUS_MINUS
263595,22200891,1610612759,SAS,San Antonio,1629646,Charles Bassey,Charles,NaN,NaN,19.000000:16,...,3.0,4.0,7.0,2.0,1.0,0.0,0.0,1.0,16.0,-14.0
87291,20201122,1610612760,SEA,Seattle,958,Vitaly Potapenko,Vitaly,NaN,NaN,8.000000:31,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,4.0,-9.0
215624,22100429,1610612755,PHI,Philadelphia,1629646,Charles Bassey,Charles,NaN,DNP - Coach's Decision,0,...,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
245814,22200191,1610612745,HOU,Houston,1629726,Garrison Mathews,Garrison,NaN,DNP - Coach's Decision,0,...,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
181404,22000427,1610612738,BOS,Boston,1629605,Tacko Fall,Tacko,NaN,DNP - Coach's Decision,0,...,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

(274692, 29)

In [56]:
# df_games = pd.read_csv(data_path + 'games.csv')
df_scoreboard = pd.read_csv(data_path + 'scoreboard_data.csv')
display(df_scoreboard.sample(5))
print(df_scoreboard.shape)

,GAME_DATE_EST,GAME_SEQUENCE,GAME_ID,GAME_STATUS_ID,GAME_STATUS_TEXT,GAMECODE,HOME_TEAM_ID,VISITOR_TEAM_ID,SEASON,LIVE_PERIOD,LIVE_PC_TIME,NATL_TV_BROADCASTER_ABBREVIATION,HOME_TV_BROADCASTER_ABBREVIATION,AWAY_TV_BROADCASTER_ABBREVIATION,LIVE_PERIOD_TIME_BCAST,ARENA_NAME,WH_STATUS,WNBA_COMMISSIONER_FLAG
7635,2006-04-07T00:00:00,9.0,20501129,3.0,Final,20060407/SEAPOR,1610612757,1610612760,2005,4.0,NaN,NaN,NBCSNW,FSNW-SEA,Q4 -,Moda Center,1,0
15494,2012-02-22T00:00:00,3.0,21100488,3.0,Final,20120222/INDCHA,1610612766,1610612754,2011,4.0,NaN,NaN,FSSE-CHA,FSIND,Q4 -,Spectrum Center,1,0
26163,2019-11-02T00:00:00,2.0,21900078,3.0,Final,20191102/BKNDET,1610612765,1610612751,2019,4.0,NaN,NaN,FSD,YES,Q4 -,Little Caesars Arena,1,0
18158,2014-01-10T00:00:00,1.0,21300531,3.0,Final,20140110/WASIND,1610612754,1610612764,2013,4.0,NaN,NaN,FSIND,NBCSWA,Q4 -,Bankers Life Fieldhouse,1,0
24369,2018-03-21T00:00:00,4.0,21701068,3.0,Final,20180321/NYKMIA,1610612748,1610612752,2017,4.0,NaN,NaN,FSSUN,MSG,Q4 -,AmericanAirlines Arena,1,0

(31247, 18)

In [57]:
df_game_log = pd.read_csv(data_path + 'game_log_data.csv')
display(df_game_log.sample(5))
print(df_game_log.shape)

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,...,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS,VIDEO_AVAILABLE,SeasonTypeAllStar
45875,22016,1610612744,GSW,Golden State Warriors,21601152,2017-04-02,GSW vs. WAS,W,240,50,...,44,34,7,10,16,20,139,24,1,Regular Season
60093,22022,1610612742,DAL,Dallas Mavericks,22200207,2022-11-15,DAL vs. LAC,W,240,35,...,34,20,12,1,12,20,103,2,1,Regular Season
19096,22007,1610612766,CHA,Charlotte Bobcats,20700296,2007-12-09,CHA @ DET,L,240,34,...,29,22,5,3,12,27,85,-19,0,Regular Season
57498,22021,1610612748,MIA,Miami Heat,22100296,2021-11-27,MIA @ CHI,W,240,37,...,36,23,13,1,10,19,107,3,1,Regular Season
28734,22010,1610612750,MIN,Minnesota Timberwolves,21000842,2011-02-22,MIN @ MIL,L,240,32,...,50,18,4,2,17,26,88,-6,0,Regular Season

(62446, 30)

In [35]:
# df_seasons = pd.read_csv(data_path + 'seasons.csv')

# # 5 date columns to pandas datetime, format dd/mm/yyyy
# df_seasons['season_start'] = pd.to_datetime(df_seasons['season_start'], format='%d/%m/%Y')
# df_seasons['season_end'] = pd.to_datetime(df_seasons['season_end'], format='%d/%m/%Y')
# df_seasons['preseason_end'] = pd.to_datetime(df_seasons['preseason_end'], format='%d/%m/%Y')
# df_seasons['postseason_start'] = pd.to_datetime(df_seasons['postseason_start'], format='%d/%m/%Y')
# df_seasons['postseason_end'] = pd.to_datetime(df_seasons['postseason_end'], format='%d/%m/%Y')


# display(df_seasons.head(5))

## Initial Data Analysis


**Drop**
- GAME_ID
- TEAM_ID - Maybe useful later for finding teammates
- TEAM_CITY
- TEAM_ABBREVIATION
- PLAYER_ID - Will need when creating time series data, but will not use now for exploration
- PLAYER_NAME
- NICKNAME

**Feature Engineering Required - Cat**
- COMMENT
    - FUTURE UPDATE: Text processing - case, lemmatizing, removing special characters

**Feature Engineering Required - Num**
- MIN

**Categorical**
- START_POSITION

**Numeric**
- 'FGM',
- 'FGA',
- 'FG_PCT',
- 'FG3M',
- 'FG3A',
- 'FG3_PCT',
- 'FTM',
- 'FTA',
- 'FT_PCT',
- 'OREB',
- 'DREB',
- 'REB',
- 'AST',
- 'STL',
- 'BLK',
- 'TO',
- 'PTS',
- 'PLUS_MINUS'
- 'PF'

In [36]:
explore = ExploreData(df_game_detail)
explore.var_dict

{'num_vars': ['GAME_ID',
  'TEAM_ID',
  'PLAYER_ID',
  'FGM',
  'FGA',
  'FG_PCT',
  'FG3M',
  'FG3A',
  'FG3_PCT',
  'FTM',
  'FTA',
  'FT_PCT',
  'OREB',
  'DREB',
  'REB',
  'AST',
  'STL',
  'BLK',
  'TO',
  'PTS',
  'PLUS_MINUS'],
 'cat_vars': ['TEAM_ABBREVIATION',
  'TEAM_CITY',
  'PLAYER_NAME',
  'NICKNAME',
  'START_POSITION',
  'COMMENT',
  'MIN',
  'PF']}

In [37]:
explore.summary()

========= Summary Statistics =========
274692 rows, 29 columns

========= Column Level Statistics =========
GAME_ID -- int64
count    2.746920e+05
mean     2.208155e+07
std      5.520011e+06
min      1.190000e+07
1%       1.190007e+07
10%      2.000069e+07
25%      2.020004e+07
50%      2.040052e+07
75%      2.210049e+07
90%      2.220089e+07
99%      4.210030e+07
max      4.220040e+07
Name: GAME_ID, dtype: float64
number of outliers: 29552
max outlier value: 42200405
min outlier value: 11900001
Unique values: 10915
Null count: 0

TEAM_ID -- int64
count    2.746920e+05
mean     1.609053e+09
std      5.009496e+07
min      9.300000e+01
1%       1.610613e+09
10%      1.610613e+09
25%      1.610613e+09
50%      1.610613e+09
75%      1.610613e+09
90%      1.610613e+09
99%      1.610613e+09
max      1.610617e+09
Name: TEAM_ID, dtype: float64
number of outliers: 459
max outlier value: 1610616834
min outlier value: 93
Unique values: 41
Null count: 0

TEAM_ABBREVIATION -- object
LAL    10161
BOS    10080
MIL     9987
PHI     9902
MIA     9901
DAL     9771
DEN     9735
Name: TEAM_ABBREVIATION, dtype: int64
Unique values: 49
Null count: 0

TEAM_CITY -- object
Los Angeles     14526
Boston          10080
Milwaukee        9987
Philadelphia     9902
Miami            9901
Dallas           9771
Denver           9735
Name: TEAM_CITY, dtype: int64
Unique values: 45
Null count: 0

PLAYER_ID -- int64
count    2.746920e+05
mean     1.291500e+06
std      3.592859e+07
min      1.000000e+00
1%       7.000000e+01
10%      4.460000e+02
25%      1.544000e+03
50%      1.011500e+05
75%      1.628392e+06
90%      1.629731e+06
99%      1.631107e+06
max      1.966938e+09
Name: PLAYER_ID, dtype: float64
number of outliers: 166
max outlier value: 1966938209
min outlier value: 196294083
Unique values: 1911
Null count: 0

PLAYER_NAME -- object
Udonis Haslem       499
Vince Carter        426
Robert Horry        424
Kobe Bryant         422
Tim Duncan          421
Shaquille O'Neal    417
LeBron James        416
Name: PLAYER_NAME, dtype: int64
Unique values: 1887
Null count: 0

NICKNAME -- object
Chris      4033
Michael    3260
Kevin      2655
Jason      2444
Anthony    2376
Mike       2247
John       2085
Name: NICKNAME, dtype: int64
Unique values: 1048
Null count: 0

START_POSITION -- object
NaN    165552
F       43656
G       43656
C       21828
Name: START_POSITION, dtype: int64
Unique values: 4
Null count: 165552

COMMENT -- object
NaN                       227153
DNP - Coach's Decision     37393
DNP - Injury/Illness        1935
DND - Injury/Illness        1505
NWT - Not With Team          256
DNP - Rest                   152
NWT - Injury/Illness         148
Name: COMMENT, dtype: int64
Unique values: 2665
Null count: 227153

MIN -- object
0               47543
12.000000:00      725
24.000000:00      390
48.000000:00      175
22.000000:09      140
19.000000:05      139
21.000000:28      138
Name: MIN, dtype: int64
Unique values: 3237
Null count: 0

FGM -- float64
count    274692.000000
mean          3.032964
std           3.175919
min           0.000000
1%            0.000000
10%           0.000000
25%           0.000000
50%           2.000000
75%           5.000000
90%           8.000000
99%          13.000000
max          24.000000
Name: FGM, dtype: float64
number of outliers: 2912
max outlier value: 24.0
min outlier value: 13.0
Unique values: 25
Null count: 0

FGA -- float64
count    274692.000000
mean          6.695732
std           6.231979
min           0.000000
1%            0.000000
10%           0.000000
25%           1.000000
50%           5.000000
75%          10.000000
90%          16.000000
99%          25.000000
max          47.000000
Name: FGA, dtype: float64
number of outliers: 3824
max outlier value: 47.0
min outlier value: 24.0
Unique values: 44
Null count: 0

FG_PCT -- float64
count    227149.000000
mean          0.416328
std           0.252166
min           0.000000
1%            0.000000
10%           0.000000
25%           0.267000
50%           0.429000
75%           0.563000
90%           0.714000
99%           1.000000
max           1.000000
Name: FG_PCT, dtype: float64
number of outliers: 0
Unique values: 283
Null count: 47543

FG3M -- float64
count    274692.000000
mean          0.689714
std           1.220153
min           0.000000
1%            0.000000
10%           0.000000
25%           0.000000
50%           0.000000
75%           1.000000
90%           2.000000
99%           5.000000
max          16.000000
Name: FG3M, dtype: float64
number of outliers: 24977
max outlier value: 16.0
min outlier value: 3.0
Unique values: 15
Null count: 0

FG3A -- float64
count    274692.000000
mean          1.938935
std           2.652662
min           0.000000
1%            0.000000
10%           0.000000
25%           0.000000
50%           1.000000
75%           3.000000
90%           6.000000
99%          11.000000
max          27.000000
Name: FG3A, dtype: float64
number of outliers: 13390
max outlier value: 27.0
min outlier value: 8.0
Unique values: 24
Null count: 0

FG3_PCT -- float64
count    227149.000000
mean          0.204530
std           0.288712
min           0.000000
1%            0.000000
10%           0.000000
25%           0.000000
50%           0.000000
75%           0.400000
90%           0.600000
99%           1.000000
max           1.000000
Name: FG3_PCT, dtype: float64
number of outliers: 0
Unique values: 99
Null count: 47543

FTM -- float64
count    274692.000000
mean          1.435917
std           2.255494
min           0.000000
1%            0.000000
10%           0.000000
25%           0.000000
50%           0.000000
75%           2.000000
90%           4.000000
99%          10.000000
max          26.000000
Name: FTM, dtype: float64
number of outliers: 17846
max outlier value: 26.0
min outlier value: 6.0
Unique values: 26
Null count: 0

FTA -- float64
count    274692.000000
mean          1.881562
std           2.781015
min           0.000000
1%            0.000000
10%           0.000000
25%           0.000000
50%           0.000000
75%           3.000000
90%           6.000000
99%          12.000000
max          28.000000
Name: FTA, dtype: float64
number of outliers: 14767
max outlier value: 28.0
min outlier value: 8.0
Unique values: 29
Null count: 0

FT_PCT -- float64
count    227149.000000
mean          0.435696
std           0.429494
min           0.000000
1%            0.000000
10%           0.000000
25%           0.000000
50%           0.500000
75%           0.933000
90%           1.000000
99%           1.000000
max           1.000000
Name: FT_PCT, dtype: float64
number of outliers: 0
Unique values: 135
Null count: 47543

OREB -- float64
count    227149.000000
mean          1.071138
std           1.416185
min           0.000000
1%            0.000000
10%           0.000000
25%           0.000000
50%           1.000000
75%           2.000000
90%           3.000000
99%           6.000000
max          14.000000
Name: OREB, dtype: float64
number of outliers: 3509
max outlier value: 14.0
min outlier value: 6.0
Unique values: 16
Null count: 47543

DREB -- float64
count    227149.000000
mean          3.088070
std           2.722607
min           0.000000
1%            0.000000
10%           0.000000
25%           1.000000
50%           2.000000
75%           4.000000
90%           7.000000
99%          12.000000
max          25.000000
Name: DREB, dtype: float64
number of outliers: 10828
max outlier value: 25.0
min outlier value: 9.0
Unique values: 26
Null count: 47543

REB -- float64
count    274692.000000
mean          3.439343
std           3.564188
min           0.000000
1%            0.000000
10%           0.000000
25%           0.000000
50%           3.000000
75%           5.000000
90%           8.000000
99%          15.000000
max          30.000000
Name: REB, dtype: float64
number of outliers: 6805
max outlier value: 30.0
min outlier value: 13.0
Unique values: 31
Null count: 0

AST -- float64
count    274692.000000
mean          1.829059
std           2.440101
min           0.000000
1%            0.000000
10%           0.000000
25%           0.000000
50%           1.000000
75%           3.000000
90%           5.000000
99%          11.000000
max          24.000000
Name: AST, dtype: float64
number of outliers: 10850
max outlier value: 24.0
min outlier value: 8.0
Unique values: 25
Null count: 0

STL -- float64
count    274692.000000
mean          0.611481
std           0.939625
min           0.000000
1%            0.000000
10%           0.000000
25%           0.000000
50%           0.000000
75%           1.000000
90%           2.000000
99%           4.000000
max          10.000000
Name: STL, dtype: float64
number of outliers: 13769
max outlier value: 10.0
min outlier value: 3.0
Unique values: 11
Null count: 0

BLK -- float64
count    274692.000000
mean          0.393688
std           0.827760
min           0.000000
1%            0.000000
10%           0.000000
25%           0.000000
50%           0.000000
75%           1.000000
90%           1.000000
99%           4.000000
max          12.000000
Name: BLK, dtype: float64
number of outliers: 8582
max outlier value: 12.0
min outlier value: 3.0
Unique values: 12
Null count: 0

TO -- float64
count    274692.000000
mean          1.101648
std           1.386039
min           0.000000
1%            0.000000
10%           0.000000
25%           0.000000
50%           1.000000
75%           2.000000
90%           3.000000
99%           6.000000
max          14.000000
Name: TO, dtype: float64
number of outliers: 3187
max outlier value: 14.0
min outlier value: 6.0
Unique values: 14
Null count: 0

PF -- float64
0.0    89525
1.0    52506
2.0    51409
3.0    40011
4.0    25436
5.0    12327
6.0     3478
Name: PF, dtype: int64
Unique values: 7
Null count: 0

PTS -- float64
count    274692.000000
mean          8.191560
std           8.505327
min           0.000000
1%            0.000000
10%           0.000000
25%           0.000000
50%           6.000000
75%          13.000000
90%          20.000000
99%          34.000000
max          71.000000
Name: PTS, dtype: float64
number of outliers: 3720
max outlier value: 71.0
min outlier value: 33.0
Unique values: 64
Null count: 0

PLUS_MINUS -- float64
count    274692.000000
mean          0.000215
std           9.767224
min         -62.000000
1%          -24.000000
10%         -12.000000
25%          -5.000000
50%           0.000000
75%           5.000000
90%          12.000000
99%          26.000000
max          54.000000
Name: PLUS_MINUS, dtype: float64
number of outliers: 14350
max outlier value: 54.0
min outlier value: -62.0
Unique values: 108
Null count: 0

To see more functions, run help() method

## Initial Feature Engineering
Converting minutes to numeric and quick feature engineering for the comments field

In [38]:
df_game_detail2 = df_game_detail.copy()
df_game_detail2.drop(['GAME_ID', 'TEAM_ID', 'TEAM_CITY', 'TEAM_ABBREVIATION', 'PLAYER_ID', 'NICKNAME'], axis=1, inplace=True) # , 'PLAYER_NAME'

In [39]:
def get_min(time_str):
    """Get minutes from time (MM:SS)"""
    try:
        m, s = time_str.split(':')
        mins = float(m) + float(s)/60
    except:
        mins = float(time_str)
    return mins

df_game_detail2['MIN'] = df_game_detail2['MIN'].apply(get_min)
print(df_game_detail2['MIN'].dtype)

float64

In [40]:
pd.set_option("display.max_rows", None)
print(df_game_detail2['COMMENT'].value_counts())
pd.set_option("display.max_rows", 30)

DNP - Coach's Decision                      37393
DNP - Injury/Illness                         1935
DND - Injury/Illness                         1505
NWT - Not With Team                           256
DNP - Rest                                    152
NWT - Injury/Illness                          148
DND - Sprained Left Ankle                     111
DND - Sprained Right Ankle                    106
NWT - Health and Safety Protocols              71
DND - Back Spasms                              66
DND - Left Ankle Sprain                        63
DND - Rest                                     62
NWT - Personal Reasons                         58
DND - Flu                                      53
DND - Sore Right Knee                          52
NWT - Personal                                 52
NWT - NBA Suspension                           48
NWT_LEAGUE_SUSPENSION                          44
NWT - League Suspension                        42
NWT - Flu                                      39
DND - Sore Lower Back                          36
DND - Sore Left Knee                           35
DND - sprained left ankle                      35
DND - Strained Left Hamstring                  35
NWT                                            35
DND - Sprained left ankle                      32
DND - Strained Left Groin                      31
DND - Coach's Decision                         30
DND - Sprained right ankle                     25
DND - Right Ankle Sprain                       24
DND - Sore Back                                23
NWT - Suspended                                22
DND - Stress Fracture; Right Heel              22
DND - Strained Lower Back                      21
DNP - Personal                                 20
DND - Strained Right Groin                     19
DND - Strained Right Knee                      19
DNP - League Suspension                        18
DND - Bruised Right Knee                       18
DND - Sprained right ankle.                    18
NWT_HEALTH_AND_SAFETY_PROTOCOLS                18
DND - Back spasms                              18
NWT - Sprained Left Ankle                      18
DND - Left Knee Surgery                        17
NWT - Back Spasms                              17
DND - Lower Back Strain                        16
DND - Tendinitis Right Knee                    15
DND - Sore Left Foot                           15
DND - sprained right ankle                     15
DND - Strained Right Hamstring                 15
DND - Sprained Right Knee                      15
DND - Sprained left ankle.                     15
DND - Sore Left Ankle                          14
DND - Left Achilles Tendinitis                 14
DND - Left ankle sprain                        14
DND - Lower Back Disc Injury                   13
NWT - Trade                                    13
DND_LEAGUE_SUSPENSION                          13
DND - Swollen Right Knee                       12
DND - Sprained Right Thumb                     12
DND - Left Knee Tendinitis                     12
DND - Personal                                 12
DND - Abdominal Strain                         12
NWT - Team Suspension                          12
DND - Sprained Left Knee                       12
DND - plantar fasciitis                        12
DND-Return to Competition Reconditioning       12
NWT - League Suspension.                       12
NWT - Personal Business                        11
DND_HEALTH_AND_SAFETY_PROTOCOLS                11
DND - NBA suspension                           11
DNP_PERSONAL                                   11
DND - Left Knee Sprain                         11
NWT - Stomach Virus                            10
NWT - Sprained Right Ankle                     10
DND - Sprained ankle                           10
DND - Left Groin Strain                        10
NWT - Sprained left ankle                      10
DND - Right Knee Tendinitis                    10
NWT - Left Knee Surgery                        10
DND - Sore Left Hamstring                      10
DND - Sprained Left Foot                       10
DND - Upper Respiratory Infection              10
DND - Sore left knee                           10
NWT - Suspension                               10
DND - Sore Right Ankle                         10
NWT - Sore Back                                10
Did Not Dress - Back Spasms                    10
NWT - Right Knee Surgery                        9
DND - Sore lower back                           9
DND - strained lower back                       9
DND - Hyperextended Left Knee                   9
NWT - left Achilles surgery                     9
DND - left foot surgery                         9
DND - Right foot surgery                        9
DND - Sprained Right Foot                       9
DND - INJ - Sprained Right Ankle                9
DNP_LEAGUE_SUSPENSION                           9
DND - Stomach Virus                             9
DND - Illness                                   9
DND - strained right groin                      9
DND - Strained Right Calf                       9
NWT - Sore Right Knee                           8
DND - INJ - Sprained Left Ankle                 8
DND - SPRAINED RIGHT ANKLE                      8
DND - Left Groin Pull                           8
DND - strained left knee                        8
DND - Sprained Right Hand                       8
DND - Did Not Dress                             8
NWT - Suspended By NBA                          8
NWT - League suspension.                        8
DND - Strained Left Shoulder                    8
DND - Sore right knee                           8
DND - back spasms                               8
DND - Sprained right foot.                      8
Not with team - NBA suspension                  8
NWT-Return to Competition Reconditioning        8
DND - Back Sprain                               7
DND - Strained right hip flexor.                7
NWT - Stress Fracture, Right Heel               7
NWT - Personal reasons                          7
DND - Strained Left Knee                        7
NWT - Trade Pending                             7
DND - Left Hamstring Strain                     7
Not With Team - Personal                        7
DND - Sore back                                 7
DND - Strained right calf                       7
DND-sprained right ankle                        7
DND - Left knee tendinitis                      7
Not with team - personal reasons                7
DND - flu                                       7
DND - Sore right ankle                          7
NWT - league suspension                         7
NWT - personal reasons                          7
DND - INJ - Strained Left Hamstring             7
DND - Strained right calf.                      7
NWT - Sore Lower Back                           7
NWT- NBA Suspension                             7
DND - Right Thumb Surgery                       6
NWT - Self Isolating                            6
NWT - Lower Back Strain                         6
DND - Left Plantar Fascia Strain                6
DND - Abdominal strain                          6
DND - Back spasms.                              6
NWT - sprained left ankle                       6
DND - orbital wall fracture, left eye           6
DND - sprained ankle                            6
DND - Strained left hamstring                   6
DND - Left Knee Bone Bruise                     6
DND - Left Ankle                                6
Did Not Dress - Plantar fasciitis               6
NWT - Acquired in Trade                         6
DND - Sprained Rt. Ankle                        6
Did Not Dress - Sore Right Wrist                6
DND - Strained right groin                      6
DND - strained left groin                       6
NWT -                                           6
DND - Strained Groin                            6
DND - Lower Back Pain                           6
DND - Left Knee Strain                          6
DND - SPRAINED LEFT ANKLE                       6
DND - sprained left foot                        6
DND - Right Knee Synovitis                      6
DND - Left Knee Rehab                           6
DND - Strained left groin                       6
NWT - Left Ankle Sprain                         6
DND - sore left knee                            6
DND - sore back                                 6
Did Not Dress - Right Foot Contusion            6
DND - Bruised Left Knee                         6
DND - stress fracture, right foot               6
DND - Flu-like symptoms                         5
DND - Stomach Flu                               5
DND - Sore Right Wrist                          5
DND - Lower back strain                         5
DND - Back Spasms.                              5
DND - Thumb Injury                              5
DND - Right Thigh Contusion                     5
DND - Left Ring Finger Fracture                 5
DND - bursa sac injury, right hip               5
DND - Left Quad Deficiency                      5
DND - abdominal strain                          5
DND - bi-lateral plantar fasciitis              5
DND - strained right knee                       5
DND - Right Quadriceps Tendinitis               5
DND - Left 5th Metatarsal Fracture              5
NWT-League Suspension                           5
DND - Lower Back Spasms                         5
DND - Left Shoulder Tendinitis                  5
DND - Suspended                                 5
NWT - Strained Right Knee                       5
DND - Sprained Right Wrist                      5
DND - Strained Left Calf                        5
DND - INJ - Strained Left Groin                 5
DND - Stress Fracture, Right Tibia              5
DND - FLU                                       5
DND - Strained Left Hip Flexor                  5
DND - Right Hamstring Pull                      5
Did Not Dress - Flu                             5
NWT - Sore Left Achilles                        5
DND - sore right knee                           5
DND - Bruised Left Calf                         5
DND - Right Calf Strain                         5
Did Not Dress - Sprained Left Ankle             5
NWT - Bronchitis                                5
DND - Sore Right Foot                           5
DND - Left thigh bruise                         5
DND - Sore left I/T band.                       5
DND - Mild Concussion                           5
DND - Left Calf Strain                          5
DND - Stress Fracture, RT Foot                  5
DND - Stress fracture, right foot               5
NWT - NBA suspension                            5
DND - Sprained right foot                       5
NWT - Viral Illness                             5
DND - sprained right foot                       5
DND - bruised left foot                         5
DND - Left Quadriceps Tendon Strain             5
DND - Sore right foot                           5
DND - stress fracture lower back                5
DND - Stress Fracture, Right Heel               5
DND - Rt. Lower Leg Soft Tissue Strain          5
DND - Bruised Lower Back                        5
DND - Left ankle sprain.                        5
DND - Sprained right knee                       5
DND - Moderate Left Ankle Sprain                5
DND - Arthroscopic Surgery, Left Knee           5
DND - Sprained Right Big Toe                    5
Did Not Travel - Personal                       5
DND - Sprained Right MCL                        5
DND - Right Elbow Tendinitis                    4
NWT - Strained Left Groin                       4
NOT WITH TEAM - FLU                             4
DND - Strained left knee                        4
Did Not Dress - Right Thumb Surgery             4
DND - Strained Right Ankle Tendon               4
DND - Arthroscopic Surgery, Right Knee          4
Did Not Dress - Left Foot                       4
DNP - Sprained Left Ankle                       4
DND - Deep Bone Bruise & Stress Reaction        4
DND - Strained left groin.                      4
DND - Sore right knee.                          4
Not with team - suspended                       4
Did Not Travel - Left Ankle                     4
Not With Team - Personal Reasons                4
NWT - Family reasons                            4
DND - Fractured Right Hand                      4
NWT - Strained right knee                       4
DNP - Back Spasms                               4
NWT - Upper Respiratory Infection               4
DND - Stress Reaction, Left Foot                4
DND - Sprained Lt. Ankle                        4
DND - LEFT KNEE BONE BRUISE                     4
DND - INJ - Strained Right Groin                4
NWT - Sinus Infection                           4
NWT - Right Knee Tendinitis                     4
NBA SUSPENSION                                  4
DND - Groin Strain                              4
DNP - DND - Sore left knee                      4
DND - Sprained Lt Ankle                         4
NWT - Death in Family                           4
DND - Right Knee Strain                         4
DND - LEFT ANKLE SPRAIN                         4
DND - Team Suspension                           4
DND - Left Quadricep Contusion                  4
DND - Sore Left Achilles                        4
DND - INJ - Lower Back Strain                   4
DND - Sore Left Thigh                           4
DND - Bruised Right Shoulder                    4
Did Not Dress - Bone bruise, right knee         4
DND - right ankle sprain                        4
NWT - Strained Left Hamstring                   4
DND - strained left hamstring                   4
NWT - Broken Right Wrist                        4
DND - Sprained right knee.                      4
DND - Strained back                             4
NWT_RETURN_TO_COMPETITION_RECONDITIONING        4
DND - Injured                                   4
DND - Migraine Headache                         4
NWT - Sprained left ankle.                      4
NWT-flu                                         4
DND - Food Poisoning                            4
DND - Right ankle tendinitis                    4
Not With Team - NBA Suspension                  4
DND - Left Knee Pain                            4
Did Not Dress - Left Ankle Sprain               4
DND - Bruised right knee.                       4
DND - Pulled groin                              4
DND - strained right hamstring                  4
NWT - Swollen Right Knee                        4
NWT - Strained Lower Back                       4
DND - Right Lower Leg Edema                     4
DND - Left Knee Hyperextension                  4
DND - Right Ankle Tendonitis                    4
DND - BACK SPASMS                               4
DND - Left Thigh Bruise                         4
DND - toe surgery                               4
DND - Strain, Right Hamstring                   4
DND - Fractured Lt Wrist                        4
DND - Strained left calf                        3
DND - Strained left achilles tendon.            3
NWT - Left ankle sprain                         3
DND - Dislocated Left Knee Cap                  3
DND - Lower Back Contusion                      3
DND - Strained Lt. Hamstring                    3
DND - Left great toe sprain                     3
DND - Right Thigh Bruise                        3
DND - Sore left foot.                           3
DND - sore toes                                 3
NWT - Sprained right ankle                      3
DND - low back soreness                         3
DND - Sore Right Hamstring                      3
DNP - NWT - Sprained right ankle                3
DND - sprained left knee                        3
DND - Inflammation, left knee                   3
DND - Right index finger                        3
DND - Sprained right hand                       3
DND - Torn ligaments in right wrist.            3
DND - Right Hip Contusion                       3
NWT - strained lower back                       3
DND - Trade                                     3
DND - Viral Infection                           3
NOT WITH TEAM - PERSONAL REASONS                3
DND - Deep Right Thigh Bruise                   3
DND - Sore Rt. Ankle                            3
NWT - Personal reasons.                         3
NWT - personal                                  3
DND - Torn ligaments in right wrist             3
DND - Hip flexor strain                         3
DND - left groin strain                         3
DND - INJ - Subluxated Left Kneecap             3
NWT - Sore back                                 3
NWT - Strep Throat                              3
DND - lower back stress fracture                3
DND - Stomach flu                               3
DND - Sore left knee.                           3
DND - Strained left Achilles tendon.            3
DND - Low back soreness                         3
DND - Sprained Left Hip                         3
DND - Sore Lt. Foot                             3
DND - Sprained Left Rib                         3
DND - Sprained left foot.                       3
NWT - Suspended by NBA                          3
DND - strained right plantar fascia             3
NWT - Left Thigh Bruise                         3
Did Not Dress - Right Knee Sprain               3
NWT - Back spasms                               3
Not With Team - Flu                             3
DND - Personal Reasons                          3
DND - Right knee patellar tendon strain         3
DND - Sore left thigh                           3
DND - left ankle sprain                         3
DND - Sore lower back.                          3
Did Not Dress - Left Quadricep Strain           3
NWT - Strained Groin                            3
NWT - Right Foot Stress Fracture                3
DND - Strained left hip flexor                  3
DND - Left Achilles inflammation                3
DND - Torn peroneus longus tendon.              3
NWT - Strained lower back                       3
DND - Right Ankle Synovitis                     3
DND - Hyperextended left knee                   3
DND - Left Knee                                 3
DND - Left hamstring strain                     3
DND - Strained lower back                       3
DND - Left Hand Contusion                       3
DND - Back Strain                               3
DND - Strained right peroneal tendon            3
NWT - Sore Left Knee                            3
DND - Sprained left knee                        3
DNP - DND - Sprained Left Ankle                 3
DND - strained groin                            3
DND - INJ - Strained Right Calf                 3
NWT - Stomach virus                             3
DND - Stress Fracture, Rt Foot                  3
DND - sprained right knee                       3
DND - lateral meniscus tear, left knee          3
DND-sore right hip                              3
DND - Left Thigh Contusion                      3
DND - Left Knee Effusion                        3
NWT - Viral Infection                           3
NWT-en route                                    3
DND - Low Back Pain                             3
DND - Right shoulder separation.                3
DND - BROKEN RIGHT HAND                         3
DND - low back injury                           3
NWT - Partial tear of left ACL                  3
DND - Right Mid Foot Bone Contusion             3
DND - Fractured Second Metacarpal, Right        3
NWT - Family Situation                          3
DND - Dislocated Metatarsal, Left Foot          3
Did Not Dress - Left Hamstring Strain           3
DND - Right Ankle Tendinitis                    3
DND - Sore Lt. Knee                             3
NWT - Low Back Injury                           3
DND - Left Hip Contusion                        3
DND - Hip flexor strain.                        3
DND - lower abdominal strain                    3
NWT - Coach's Decision                          3
DND - Corneal Abrasion                          3

In [41]:
def comment_cat(comment_str):
    try:
        code, reason = comment_str.split('-', maxsplit=1)
        return code.strip(), reason.strip()
    except:
        return comment_str, comment_str

df_game_detail2['comment_code'], df_game_detail2['comment_reason'] = zip(*df_game_detail2['COMMENT'].apply(comment_cat))

In [42]:
pd.set_option("display.max_rows", None)
print(df_game_detail2['comment_code'].value_counts()[:10], "\n")
print(df_game_detail2['comment_reason'].value_counts())
pd.set_option("display.max_rows", 30)

DNP                      39741
DND                       5424
NWT                       1829
Did Not Dress              189
NOT WITH TEAM               49
Not With Team               49
Not with team               46
NWT_LEAGUE_SUSPENSION       44
DNT                         38
Did Not Travel              25
Name: comment_code, dtype: int64

Coach's Decision                            37431
Injury/Illness                               3588
Not With Team                                 263
Rest                                          217
Sprained Left Ankle                           143
Sprained Right Ankle                          121
Flu                                           103
Back Spasms                                   100
Personal                                       97
Left Ankle Sprain                              76
Health and Safety Protocols                    75
Personal Reasons                               68
League Suspension                              67
Sore Right Knee                                62
NBA Suspension                                 60
Sore Lower Back                                46
Sprained left ankle                            46
NWT_LEAGUE_SUSPENSION                          44
sprained left ankle                            44
Sore Left Knee                                 42
Strained Left Hamstring                        39
Strained Left Groin                            37
Sore Back                                      36
NWT                                            35
Sprained right ankle                           31
Suspended                                      31
Right Ankle Sprain                             28
Left Knee Surgery                              28
Strained Lower Back                            28
Lower Back Strain                              26
Strained Right Knee                            26
sprained right ankle                           25
NBA suspension                                 25
Stomach Virus                                  24
Strained Right Groin                           24
Back spasms                                    23
Stress Fracture; Right Heel                    22
personal reasons                               20
Return to Competition Reconditioning           20
Sprained Right Knee                            20
Sprained right ankle.                          20
Sprained left ankle.                           20
Sore Left Foot                                 19
NWT_HEALTH_AND_SAFETY_PROTOCOLS                18
Bruised Right Knee                             18
Strained Right Hamstring                       18
Sore Left Ankle                                18
Suspension                                     17
Team Suspension                                17
Left ankle sprain                              17
Swollen Right Knee                             16
Trade                                          16
Left Knee Tendinitis                           16
Tendinitis Right Knee                          15
Lower Back Disc Injury                         15
Right Knee Tendinitis                          15
Upper Respiratory Infection                    15
Sprained Left Knee                             14
Abdominal Strain                               14
Left Achilles Tendinitis                       14
flu                                            14
Sprained Left Foot                             13
Left Groin Strain                              13
strained lower back                            13
Right Knee Surgery                             13
Sprained Right Thumb                           13
DND_LEAGUE_SUSPENSION                          13
Illness                                        12
Stress Fracture, Right Heel                    12
plantar fasciitis                              12
League Suspension.                             12
Sore Right Wrist                               12
Sore left knee                                 12
Personal Business                              12
Sore Right Ankle                               12
Lower Back Spasms                              12
Left Knee Sprain                               12
Sprained ankle                                 11
SPRAINED RIGHT ANKLE                           11
DNP_PERSONAL                                   11
Hyperextended Left Knee                        11
FLU                                            11
DND_HEALTH_AND_SAFETY_PROTOCOLS                11
sore back                                      11
Sore back                                      11
Left Ankle                                     11
Sore Left Hamstring                            11
back spasms                                    11
Strained Right Calf                            10
Suspended By NBA                               10
strained left groin                            10
Right Thumb Surgery                            10
Strained Left Shoulder                         10
Right foot surgery                             10
League suspension.                             10
Strained Left Knee                             10
Left Hamstring Strain                          10
Bruised Left Knee                              10
left Achilles surgery                          10
Right Calf Strain                               9
Sprained Right Hand                             9
Personal reasons                                9
left foot surgery                               9
Sprained right foot.                            9
Sore Left Achilles                              9
INJ - Sprained Right Ankle                      9
Left Thigh Bruise                               9
Sprained Right Foot                             9
sore left knee                                  9
Left knee tendinitis                            9
strained right groin                            9
Bronchitis                                      9
Back Sprain                                     9
Strained Groin                                  9
DNP_LEAGUE_SUSPENSION                           9
sore right knee                                 9
Left Groin Pull                                 9
Sore lower back                                 9
Strained right calf                             8
Did Not Dress                                   8
strained right knee                             8
Left Knee Rehab                                 8
Flu-like symptoms                               8
Strained left hamstring                         8
INJ - Sprained Left Ankle                       8
strained left knee                              8
Stress Fracture, Right Tibia                    8
Left Knee Strain                                8
Viral Illness                                   8
stress fracture, right foot                     8
Right Knee Synovitis                            8
league suspension                               8
SPRAINED LEFT ANKLE                             8
Sore right knee                                 8
Left Knee Bone Bruise                           7
Right Knee Sprain                               7
Plantar fasciitis                               7
Bruised Right Shoulder                          7
Trade Pending                                   7
Sprained Rt. Ankle                              7
Stomach Flu                                     7
Sore Right Foot                                 7
Strained right hip flexor.                      7
INJ - Strained Left Hamstring                   7
Right Thigh Contusion                           7
Strained right calf.                            7
Left Ring Finger Fracture                       7
Sore right ankle                                7
NBA SUSPENSION                                  7
Strained Left Hip Flexor                        7
Right Foot Contusion                            7
right knee tendinitis                           6
Right Ankle Tendonitis                          6
Arthroscopic Surgery, Left Knee                 6
Sore right foot                                 6
Not with team                                   6
Stress fracture, right foot                     6
abdominal strain                                6
Left Plantar Fascia Strain                      6
Concussion                                      6
Left Shoulder Tendinitis                        6
Sprained Right Wrist                            6
Strained left groin                             6
Stomach virus                                   6
sore left foot                                  6
sprained ankle                                  6
sprained left foot                              6
Food Poisoning                                  6
Sinus Infection                                 6
                                                6
Back spasms.                                    6
Right Ankle Tendinitis                          6
Left Foot                                       6
Abdominal strain                                6
Strained Right Hip Flexor                       6
Death in Family                                 6
Lower Back Pain                                 6
stress fracture lower back                      6
BACK SPASMS                                     6
Moderate Left Ankle Sprain                      6
Strained lower back                             6
Strained right knee                             6
Bruised Lower Back                              6
Strained right groin                            6
Viral Infection                                 6
Mild Concussion                                 6
orbital wall fracture, left eye                 6
Self Isolating                                  6
Strained Left Calf                              6
Migraine Headache                               6
Strep Throat                                    6
Acquired in Trade                               6
INJ - Strained Left Groin                       5
Right Hamstring Pull                            5
Sprained Ankle                                  5
left ankle sprain                               5
personal                                        5
stomach virus                                   5
Sprained right knee                             5
Right Thumb                                     5
Lower back strain                               5
Strained left groin.                            5
Left ankle sprain.                              5
Injured                                         5
Sore Hamstrings                                 5
Right ankle tendinitis                          5
suspended                                       5
Sore left I/T band.                             5
Bruised Left Calf                               5
Right knee tendinitis                           5
bi-lateral plantar fasciitis                    5
Sore left ankle                                 5
right ankle sprain                              5
Left Calf Strain                                5
strained left hamstring                         5
Stress Fracture, RT Foot                        5
Right Lower Leg Edema                           5
Left Quadriceps Tendon Strain                   5
Sprained right foot                             5
Arthroscopic Surgery, Right Knee                5
Rt. Lower Leg Soft Tissue Strain                5
sprained right foot                             5
Broken Right Wrist                              5
Bruised right knee.                             5
Swollen Left Knee                               5
bruised left foot                               5
Sprained Right Big Toe                          5
Back Spasms.                                    5
Right Knee Contusion                            5
Left Quad Deficiency                            5
bursa sac injury, right hip                     5
Left Knee Hyperextension                        5
Left thigh bruise                               5
Sore Left Elbow                                 5
Low Back Injury                                 5
Sprained Right MCL                              5
Right Quadriceps Tendinitis                     5
Thumb Injury                                    5
Sprained left knee                              5
Left 5th Metatarsal Fracture                    5
Strained right peroneal tendon                  4
Fractured Right Hand                            4
Sprained right hand                             4
Sprained right knee.                            4
sore right hip                                  4
Family reasons                                  4
Strained back                                   4
Stress Reaction, Left Foot                      4
Left Knee Pain                                  4
Right Elbow Synovitis                           4
Stiff Neck                                      4
Lower abdominal strain                          4
LEFT KNEE BONE BRUISE                           4
DND - Sore left knee                            4
Sore right knee.                                4
Torn peroneus longus tendon.                    4
NWT_RETURN_TO_COMPETITION_RECONDITIONING        4
Right Thumb Sprain                              4
Strained Right Ankle Tendon                     4
Groin Strain                                    4
team suspension                                 4
Left Knee                                       4
Sore Right Hamstring                            4
Torn ligaments in right wrist                   4
Deep Bone Bruise & Stress Reaction              4
INJ - Lower Back Strain                         4
Back Strain                                     4
Right Thigh Bruise                              4
Right knee surgery                              4
toe surgery                                     4
Left Hip Strain                                 4
LEFT ANKLE SPRAIN                               4
Sprained Neck                                   4
trade                                           4
Right Knee Strain                               4
Right Hip Strain                                4
Left hamstring strain                           4
SORE RIGHT KNEE                                 4
Left Quadricep Contusion                        4
RIGHT ANKLE SPRAIN                              4
sore right foot                                 4
Ankle Tendinitis                                4
Stress Fracture, Rt Foot                        4
strained right hamstring                        4
INJ - Strained Right Groin                      4
Pulled groin                                    4
Bone bruise, right knee                         4
Right Hamstring Strain                          4
Strain, Right Hamstring                         4
Strained Right Arch                             4
Sore Left Thigh                                 4
Pulled Groin                                    4
Right Corneal Abrasion                          4
Strained left knee                              4
Personal.                                       4
Sprained Lt Ankle                               4
Sore left knee.                                 4
sprained left knee                              4
Left Knee Contusion                             4
Left Thigh Contusion                            4
Stress fracture, right tibia                    4
Fractured Lt Wrist                              4
Lt. Ankle Sprain                                4
Sprained Rt Ankle                               4
SUSPENDED                                       4
Sprained Lt. Ankle                              4
Right Elbow Tendinitis                          4
Left Plantar Fasciitis                          4
bone spur left ankle                            4
Intestinal Virus                                4
Personal reasons.                               4
Sore Right Hip                                  4
Personal Reasons.                               3
DND - Sprained Left Ankle                       3
DND                                             3
Sore Left Ankle/Big Toe                         3
Swollen right knee                              3
Strained Left Achilles Tendon                   3
left knee surgery                               3
torn peroneus longus tendon                     3
sprained right thumb                            3
lateral meniscus tear, left knee                3
Hernia                                          3
Stomach flu                                     3
Right ankle sprain                              3
Viral Infection.                                3
INJ - Right Groin Strain                        3
League suspension                               3
INJ - Right Knee Tendinitis                     3
Sore Lt. Knee                                   3
Corneal Abrasion                                3
Bruised Sternum                                 3
PERSONAL REASONS                                3
Flu-like Symptoms                               3
Sprained Left Rib                               3
Sore Right Hand                                 3
Strained right hamstring.                       3
Right Shoulder Strain                           3
INJ - Strained Right Calf                       3
Inflamed Left Knee                              3
Left Ankle Surgery                              3
Dislocated Metatarsal, Left Foot                3
Partial tear of left ACL                        3
DND - Right Knee Surgery                        3
BROKEN RIGHT HAND                               3
left groin strain                               3
Right Hip Contusion                             3
Strained right hamstring                        3
Left Hip Contusion                              3
Left Ankle Bruise                               3
Right knee contusion                            3
Bruised left knee                               3
Sprained Right Great Toe                        3
Left Hand Contusion                             3
Left ankle surgery                              3
Sore Achilles                                   3
sore toes                                       3
strained groin                                  3
Sprained Right Hamstring                        3
Strained left calf                              3
LEFT CALF STRAIN                                3
Dislocated Left Knee Cap                        3
Sprained right hand.                            3
Left great toe sprain                           3
Left calf strain                                3
Left knee sprain                                3
INJ - Torn Left Achilles Tendon                 3
Sprained left foot.                             3
Neck Spasms                                     3
Lower back strain.                              3
Right knee patellar tendon strain               3
Lt. Knee Tendinitis                             3
Left Wrist Sprain                               3
lower abdominal strain                          3
Stress fracture right foot                      3
bruised right shoulder                          3
Lower Back Contusion                            3
Left hip pointer                                3
Strained left calf.                             3
sprained right knee                             3
strained right plantar fascia                   3
Injured Groin                                   3
Right Knee                                      3
Suspended by NBA                                3
Right Achilles Tendinitis                       3
INJ - Subluxated Left Kneecap                   3
Left plantar fasciitis                          3
Flu.                                            3
Strained Back                                   3
Sprained left hip.                              3
Family Situation                                3
Sore left foot.                                 3
Sprained Toe                                    3

In [43]:
## Change to per minute stats
cols_to_make_per_min = \
    ['FGM', 'FGA', 'FG3M', 'FG3A', 'FTM', 'FTA', 'OREB', 'DREB',
    'REB', 'AST', 'STL', 'BLK', 'TO', 'PTS', 'PLUS_MINUS', 'PF',
    ]

per_min_cols = [x + '_pm' for x in cols_to_make_per_min]

In [44]:
arr1 = np.array(df_game_detail2[cols_to_make_per_min])
arr2 = np.array(df_game_detail2['MIN'])

df_per_min = pd.DataFrame(np.where(arr2==0, np.nan, arr1.T/arr2).T, columns=per_min_cols)
# df_per_min = pd.DataFrame((arr1.T / arr2).T, columns=per_min_cols)
df_game_detail3 = pd.concat([df_game_detail2, df_per_min], axis=1)
df_game_detail3

C:\Users\BrandonBrown\AppData\Local\Temp\ipykernel_18728\1407694959.py:4: RuntimeWarning: divide by zero encountered in divide
  df_per_min = pd.DataFrame(np.where(arr2==0, np.nan, arr1.T/arr2).T, columns=per_min_cols)
C:\Users\BrandonBrown\AppData\Local\Temp\ipykernel_18728\1407694959.py:4: RuntimeWarning: invalid value encountered in divide
  df_per_min = pd.DataFrame(np.where(arr2==0, np.nan, arr1.T/arr2).T, columns=per_min_cols)

,PLAYER_NAME,START_POSITION,COMMENT,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,...,OREB_pm,DREB_pm,REB_pm,AST_pm,STL_pm,BLK_pm,TO_pm,PTS_pm,PLUS_MINUS_pm,PF_pm
0,Lamond Murray,F,NaN,31.733333,8.0,17.0,0.471,1.0,1.0,1.0,...,0.031513,0.031513,0.063025,0.063025,0.031513,0.000000,0.031513,0.535714,0.315126,0.063025
1,Clar. Weatherspoon,F,NaN,32.966667,1.0,4.0,0.250,0.0,0.0,0.0,...,0.091001,0.333670,0.424671,0.000000,0.091001,0.030334,0.030334,0.242669,0.394338,0.091001
2,Zydrunas Ilgauskas,C,NaN,12.266667,0.0,4.0,0.000,0.0,0.0,0.0,...,0.081522,0.163043,0.244565,0.000000,0.000000,0.081522,0.163043,0.000000,0.163043,0.407609
3,Matt Harpring,G,NaN,36.666667,7.0,13.0,0.538,0.0,1.0,0.0,...,0.027273,0.054545,0.081818,0.081818,0.000000,0.081818,0.027273,0.436364,0.327273,0.081818
4,Andre Miller,G,NaN,27.000000,3.0,5.0,0.600,0.0,0.0,0.0,...,0.000000,0.148148,0.148148,0.222222,0.000000,0.000000,0.222222,0.296296,0.148148,0.111111
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
274687,Vlatko Cancar,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
274688,Reggie Jackson,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
274689,Zeke Nnaji,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
274690,Ish Smith,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
274691,Peyton Watson,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [45]:
display(df_game_detail3[df_game_detail3['MIN']==0].head())

# ## Looks ok, turn off numpy divide and invalid errors
# np.seterr(divide='ignore', invalid='ignore')

,PLAYER_NAME,START_POSITION,COMMENT,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,...,OREB_pm,DREB_pm,REB_pm,AST_pm,STL_pm,BLK_pm,TO_pm,PTS_pm,PLUS_MINUS_pm,PF_pm
11,Trajan Langdon,NaN,DNP - Coach's Decision,0.0,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Lucious Harris,NaN,DND - Hernia,0.0,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,Kevin Ollie,NaN,DNP - Coach's Decision,0.0,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,Andrew DeClercq,NaN,DNP - Coach's Decision,0.0,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,Don Reid,NaN,DNP - Coach's Decision,0.0,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [46]:
var_dict = {
    'num_vars':
        ['FGM', 'FGA', 'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT',
        'OREB', 'DREB', 'REB', 'AST', 'STL', 'BLK', 'TO', 'PTS', 'PLUS_MINUS', 'MIN', 'PF',
        ],
    'cat_vars':
        ['START_POSITION', 'comment_code', 'comment_reason']
}

In [47]:
for c in df_game_detail3.columns:
    if c in var_dict['num_vars']:
        df_game_detail3[c] = pd.to_numeric(df_game_detail3[c], errors='raise')
        print(f"{c} data type: {df_game_detail3[c].dtype}")
    elif c in var_dict['cat_vars']:
        print(f"{c} data type: {df_game_detail3[c].dtype}")
    else:
        print(f'column {c} not in var_dict')

column PLAYER_NAME not in var_dict
START_POSITION data type: object
column COMMENT not in var_dict
MIN data type: float64
FGM data type: float64
FGA data type: float64
FG_PCT data type: float64
FG3M data type: float64
FG3A data type: float64
FG3_PCT data type: float64
FTM data type: float64
FTA data type: float64
FT_PCT data type: float64
OREB data type: float64
DREB data type: float64
REB data type: float64
AST data type: float64
STL data type: float64
BLK data type: float64
TO data type: float64
PF data type: float64
PTS data type: float64
PLUS_MINUS data type: float64
comment_code data type: object
comment_reason data type: object
column FGM_pm not in var_dict
column FGA_pm not in var_dict
column FG3M_pm not in var_dict
column FG3A_pm not in var_dict
column FTM_pm not in var_dict
column FTA_pm not in var_dict
column OREB_pm not in var_dict
column DREB_pm not in var_dict
column REB_pm not in var_dict
column AST_pm not in var_dict
column STL_pm not in var_dict
column BLK_pm not in var_dict
column TO_pm not in var_dict
column PTS_pm not in var_dict
column PLUS_MINUS_pm not in var_dict
column PF_pm not in var_dict

In [48]:
explore2 = ExploreData(data=df_game_detail3, var_dict=var_dict)
explore2.summary()

========= Summary Statistics =========
274692 rows, 41 columns

========= Column Level Statistics =========
PLAYER_NAME -- object
Column not in cat_vars or num_vars
Unique values: 1887
Null count: 0

START_POSITION -- object
NaN    165552
F       43656
G       43656
C       21828
Name: START_POSITION, dtype: int64
Unique values: 4
Null count: 165552

COMMENT -- object
Column not in cat_vars or num_vars
Unique values: 2665
Null count: 227153

MIN -- float64
count    274692.000000
mean         19.206250
std          13.677977
min           0.000000
1%            0.000000
10%           0.000000
25%           5.950000
50%          20.050000
75%          30.516667
90%          37.300000
99%          44.966667
max          64.966667
Name: MIN, dtype: float64
number of outliers: 0
Unique values: 3173
Null count: 0

FGM -- float64
count    274692.000000
mean          3.032964
std           3.175919
min           0.000000
1%            0.000000
10%           0.000000
25%           0.000000
50%           2.000000
75%           5.000000
90%           8.000000
99%          13.000000
max          24.000000
Name: FGM, dtype: float64
number of outliers: 2912
max outlier value: 24.0
min outlier value: 13.0
Unique values: 25
Null count: 0

FGA -- float64
count    274692.000000
mean          6.695732
std           6.231979
min           0.000000
1%            0.000000
10%           0.000000
25%           1.000000
50%           5.000000
75%          10.000000
90%          16.000000
99%          25.000000
max          47.000000
Name: FGA, dtype: float64
number of outliers: 3824
max outlier value: 47.0
min outlier value: 24.0
Unique values: 44
Null count: 0

FG_PCT -- float64
count    227149.000000
mean          0.416328
std           0.252166
min           0.000000
1%            0.000000
10%           0.000000
25%           0.267000
50%           0.429000
75%           0.563000
90%           0.714000
99%           1.000000
max           1.000000
Name: FG_PCT, dtype: float64
number of outliers: 0
Unique values: 283
Null count: 47543

FG3M -- float64
count    274692.000000
mean          0.689714
std           1.220153
min           0.000000
1%            0.000000
10%           0.000000
25%           0.000000
50%           0.000000
75%           1.000000
90%           2.000000
99%           5.000000
max          16.000000
Name: FG3M, dtype: float64
number of outliers: 24977
max outlier value: 16.0
min outlier value: 3.0
Unique values: 15
Null count: 0

FG3A -- float64
count    274692.000000
mean          1.938935
std           2.652662
min           0.000000
1%            0.000000
10%           0.000000
25%           0.000000
50%           1.000000
75%           3.000000
90%           6.000000
99%          11.000000
max          27.000000
Name: FG3A, dtype: float64
number of outliers: 13390
max outlier value: 27.0
min outlier value: 8.0
Unique values: 24
Null count: 0

FG3_PCT -- float64
count    227149.000000
mean          0.204530
std           0.288712
min           0.000000
1%            0.000000
10%           0.000000
25%           0.000000
50%           0.000000
75%           0.400000
90%           0.600000
99%           1.000000
max           1.000000
Name: FG3_PCT, dtype: float64
number of outliers: 0
Unique values: 99
Null count: 47543

FTM -- float64
count    274692.000000
mean          1.435917
std           2.255494
min           0.000000
1%            0.000000
10%           0.000000
25%           0.000000
50%           0.000000
75%           2.000000
90%           4.000000
99%          10.000000
max          26.000000
Name: FTM, dtype: float64
number of outliers: 17846
max outlier value: 26.0
min outlier value: 6.0
Unique values: 26
Null count: 0

FTA -- float64
count    274692.000000
mean          1.881562
std           2.781015
min           0.000000
1%            0.000000
10%           0.000000
25%           0.000000
50%           0.000000
75%           3.000000
90%           6.000000
99%          12.000000
max          28.000000
Name: FTA, dtype: float64
number of outliers: 14767
max outlier value: 28.0
min outlier value: 8.0
Unique values: 29
Null count: 0

FT_PCT -- float64
count    227149.000000
mean          0.435696
std           0.429494
min           0.000000
1%            0.000000
10%           0.000000
25%           0.000000
50%           0.500000
75%           0.933000
90%           1.000000
99%           1.000000
max           1.000000
Name: FT_PCT, dtype: float64
number of outliers: 0
Unique values: 135
Null count: 47543

OREB -- float64
count    227149.000000
mean          1.071138
std           1.416185
min           0.000000
1%            0.000000
10%           0.000000
25%           0.000000
50%           1.000000
75%           2.000000
90%           3.000000
99%           6.000000
max          14.000000
Name: OREB, dtype: float64
number of outliers: 3509
max outlier value: 14.0
min outlier value: 6.0
Unique values: 16
Null count: 47543

DREB -- float64
count    227149.000000
mean          3.088070
std           2.722607
min           0.000000
1%            0.000000
10%           0.000000
25%           1.000000
50%           2.000000
75%           4.000000
90%           7.000000
99%          12.000000
max          25.000000
Name: DREB, dtype: float64
number of outliers: 10828
max outlier value: 25.0
min outlier value: 9.0
Unique values: 26
Null count: 47543

REB -- float64
count    274692.000000
mean          3.439343
std           3.564188
min           0.000000
1%            0.000000
10%           0.000000
25%           0.000000
50%           3.000000
75%           5.000000
90%           8.000000
99%          15.000000
max          30.000000
Name: REB, dtype: float64
number of outliers: 6805
max outlier value: 30.0
min outlier value: 13.0
Unique values: 31
Null count: 0

AST -- float64
count    274692.000000
mean          1.829059
std           2.440101
min           0.000000
1%            0.000000
10%           0.000000
25%           0.000000
50%           1.000000
75%           3.000000
90%           5.000000
99%          11.000000
max          24.000000
Name: AST, dtype: float64
number of outliers: 10850
max outlier value: 24.0
min outlier value: 8.0
Unique values: 25
Null count: 0

STL -- float64
count    274692.000000
mean          0.611481
std           0.939625
min           0.000000
1%            0.000000
10%           0.000000
25%           0.000000
50%           0.000000
75%           1.000000
90%           2.000000
99%           4.000000
max          10.000000
Name: STL, dtype: float64
number of outliers: 13769
max outlier value: 10.0
min outlier value: 3.0
Unique values: 11
Null count: 0

BLK -- float64
count    274692.000000
mean          0.393688
std           0.827760
min           0.000000
1%            0.000000
10%           0.000000
25%           0.000000
50%           0.000000
75%           1.000000
90%           1.000000
99%           4.000000
max          12.000000
Name: BLK, dtype: float64
number of outliers: 8582
max outlier value: 12.0
min outlier value: 3.0
Unique values: 12
Null count: 0

TO -- float64
count    274692.000000
mean          1.101648
std           1.386039
min           0.000000
1%            0.000000
10%           0.000000
25%           0.000000
50%           1.000000
75%           2.000000
90%           3.000000
99%           6.000000
max          14.000000
Name: TO, dtype: float64
number of outliers: 3187
max outlier value: 14.0
min outlier value: 6.0
Unique values: 14
Null count: 0

PF -- float64
count    274692.000000
mean          1.673161
std           1.584452
min           0.000000
1%            0.000000
10%           0.000000
25%           0.000000
50%           1.000000
75%           3.000000
90%           4.000000
99%           6.000000
max           6.000000
Name: PF, dtype: float64
number of outliers: 0
Unique values: 7
Null count: 0

PTS -- float64
count    274692.000000
mean          8.191560
std           8.505327
min           0.000000
1%            0.000000
10%           0.000000
25%           0.000000
50%           6.000000
75%          13.000000
90%          20.000000
99%          34.000000
max          71.000000
Name: PTS, dtype: float64
number of outliers: 3720
max outlier value: 71.0
min outlier value: 33.0
Unique values: 64
Null count: 0

PLUS_MINUS -- float64
count    274692.000000
mean          0.000215
std           9.767224
min         -62.000000
1%          -24.000000
10%         -12.000000
25%          -5.000000
50%           0.000000
75%           5.000000
90%          12.000000
99%          26.000000
max          54.000000
Name: PLUS_MINUS, dtype: float64
number of outliers: 14350
max outlier value: 54.0
min outlier value: -62.0
Unique values: 108
Null count: 0

comment_code -- object
NaN              227153
DNP               39741
DND                5424
NWT                1829
Did Not Dress       189
NOT WITH TEAM        49
Not With Team        49
Name: comment_code, dtype: int64
Unique values: 36
Null count: 227153

comment_reason -- object
NaN                     227153
Coach's Decision         37431
Injury/Illness            3588
Not With Team              263
Rest                       217
Sprained Left Ankle        143
Sprained Right Ankle       121
Name: comment_reason, dtype: int64
Unique values: 2084
Null count: 227153

FGM_pm -- float64
Column not in cat_vars or num_vars
Unique values: 16516
Null count: 47575

FGA_pm -- float64
Column not in cat_vars or num_vars
Unique values: 25540
Null count: 47575

FG3M_pm -- float64
Column not in cat_vars or num_vars
Unique values: 8811
Null count: 47575

FG3A_pm -- float64
Column not in cat_vars or num_vars
Unique values: 15553
Null count: 47575

FTM_pm -- float64
Column not in cat_vars or num_vars
Unique values: 14156
Null count: 47575

FTA_pm -- float64
Column not in cat_vars or num_vars
Unique values: 16303
Null count: 47575

OREB_pm -- float64
Column not in cat_vars or num_vars
Unique values: 10198
Null count: 47575

DREB_pm -- float64
Column not in cat_vars or num_vars
Unique values: 16479
Null count: 47575

REB_pm -- float64
Column not in cat_vars or num_vars
Unique values: 20421
Null count: 47575

AST_pm -- float64
Column not in cat_vars or num_vars
Unique values: 14997
Null count: 47575

STL_pm -- float64
Column not in cat_vars or num_vars
Unique values: 7361
Null count: 47575

BLK_pm -- float64
Column not in cat_vars or num_vars
Unique values: 7147
Null count: 47575

TO_pm -- float64
Column not in cat_vars or num_vars
Unique values: 9876
Null count: 47575

PTS_pm -- float64
Column not in cat_vars or num_vars
Unique values: 34033
Null count: 47575

PLUS_MINUS_pm -- float64
Column not in cat_vars or num_vars
Unique values: 60429
Null count: 47575

PF_pm -- float64
Column not in cat_vars or num_vars
Unique values: 10395
Null count: 47575

To see more functions, run help() method

## Create timeseries data

In [49]:
## Lag and average window functions
def get_all_lags(df, cols:t.List, group_cols:t.List, n_lags:int) -> t.Tuple[pd.DataFrame, t.List[str]]:
    df_ = df.copy()
    created_cols = []

    if n_lags > 0:
        start, stop, step = 1, n_lags + 1, 1
        prefix = 'lag_'
    else:
        start, stop, step = 0, n_lags, -1
        prefix = 'next_'
    
    # for each column in cols, get n_lags number of lags
    for col in cols:
        # for each lag, create a new column with the lagged value
        for i in range(start, stop, step):
            created_col = f'{prefix}{abs(i)}_{col}'
            created_cols.append(created_col)
            df_[created_col] = df_.groupby(group_cols)[col].shift(i)

    return df_, created_cols

def get_all_average_windows(df, cols:t.List, group_cols:t.List, 
            prefix:str, windows:np.array, shifts:np.array, min_periods:np.array
            ) -> t.Tuple[pd.DataFrame, t.List[str]]:
    df_ = df.copy()
    created_cols = []

    # for each column in cols, get average over a window of games
    for col in cols:
        # for each window, create a new column with the average value
        for w, s, mp in zip(windows, shifts, min_periods):
            created_col = f'{prefix}{s}_{s+w-1}_{col}'
            created_cols.append(created_col)
            df_[created_col] = df_.groupby(group_cols)[col].shift(s).rolling(w, min_periods=mp).mean()

    return df_, created_cols

### Game-level table - sorted by team
Step 1: Aggregate by Team and Game to get an ordered game list for each team

Also add on the date field from *games.csv* so we can see how many days between games

In [125]:
df_scoreboard_slim = df_scoreboard[['GAME_DATE_EST', 'GAME_ID', 'GAME_STATUS_TEXT', 'HOME_TEAM_ID', 'VISITOR_TEAM_ID', 'SEASON']]

## only where trim(GAME_STATUS_TEXT) == 'Final'
df_scoreboard_slim = df_scoreboard_slim[df_scoreboard_slim['GAME_STATUS_TEXT'].str.strip() == 'Final']

df_game_log_slim = df_game_log[['GAME_ID', 'TEAM_ID', 'PTS', 'FG_PCT', 'FG3_PCT', 'AST', 'REB', 'TOV', 'SEASON_ID']]

# First, merge the home team data
df_games = df_scoreboard_slim.merge(df_game_log_slim.add_suffix('_home'), how='left', left_on=['GAME_ID', 'HOME_TEAM_ID'], right_on=['GAME_ID_home', 'TEAM_ID_home'])

# Then, merge the visitor team data with different suffix
df_games = df_games.merge(df_game_log_slim.add_suffix('_away'), how='left', left_on=['GAME_ID', 'VISITOR_TEAM_ID'], right_on=['GAME_ID_away', 'TEAM_ID_away'])

## remove rows where any of [GAME_ID_home, TEAM_ID_home, GAME_ID_away, TEAM_ID_away] contain NaN
df_games = df_games.dropna(subset=['GAME_ID_home', 'TEAM_ID_home', 'GAME_ID_away', 'TEAM_ID_away'])

# ##seasons starting with 2 are regular season (e.g. 22000 is regular season 2020-2021)
start_with_2_mask = np.char.startswith(np.char.mod('%d', df_games['SEASON_ID_home']), '2')
df_games['regular_season'] = np.where(start_with_2_mask, 1, 0)

df_games.drop(['SEASON_ID_home', 'SEASON_ID_away', 'GAME_ID_home', 'GAME_ID_away'], axis=1, inplace=True)

## convert GAME_DATE_EST to datetime
df_games['GAME_DATE_EST'] = pd.to_datetime(df_games['GAME_DATE_EST'])

display(df_games)

,GAME_DATE_EST,GAME_ID,GAME_STATUS_TEXT,HOME_TEAM_ID,VISITOR_TEAM_ID,SEASON,TEAM_ID_home,PTS_home,FG_PCT_home,FG3_PCT_home,...,REB_home,TOV_home,TEAM_ID_away,PTS_away,FG_PCT_away,FG3_PCT_away,AST_away,REB_away,TOV_away,regular_season
0,2000-10-31,20000002,Final,1610612751,1610612739,2000,1.610613e+09,82.0,0.365,0.300,...,47.0,15.0,1.610613e+09,86.0,0.410,0.286,16.0,52.0,19.0,1
1,2000-10-31,20000003,Final,1610612753,1610612764,2000,1.610613e+09,97.0,0.430,0.375,...,37.0,15.0,1.610613e+09,86.0,0.458,0.571,20.0,44.0,27.0,1
2,2000-10-31,20000004,Final,1610612737,1610612766,2000,1.610613e+09,82.0,0.370,0.400,...,29.0,13.0,1.610613e+09,106.0,0.565,0.556,16.0,44.0,17.0,1
3,2000-10-31,20000001,Final,1610612752,1610612755,2000,1.610613e+09,72.0,0.357,0.273,...,37.0,22.0,1.610613e+09,101.0,0.576,0.375,27.0,37.0,14.0,1
4,2000-10-31,20000005,Final,1610612761,1610612765,2000,1.610613e+09,95.0,0.376,0.294,...,48.0,15.0,1.610613e+09,104.0,0.473,0.250,21.0,45.0,12.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31232,2023-06-01,42200401,Final,1610612743,1610612748,2022,1.610613e+09,104.0,0.506,0.296,...,45.0,10.0,1.610613e+09,93.0,0.406,0.333,26.0,43.0,8.0,0
31233,2023-06-04,42200402,Final,1610612743,1610612748,2022,1.610613e+09,108.0,0.520,0.393,...,38.0,14.0,1.610613e+09,111.0,0.487,0.486,28.0,31.0,11.0,0
31234,2023-06-07,42200403,Final,1610612748,1610612743,2022,1.610613e+09,94.0,0.370,0.314,...,33.0,4.0,1.610613e+09,109.0,0.513,0.278,28.0,58.0,14.0,0
31235,2023-06-09,42200404,Final,1610612748,1610612743,2022,1.610613e+09,95.0,0.449,0.320,...,37.0,15.0,1.610613e+09,108.0,0.494,0.500,26.0,34.0,8.0,0
31236,2023-06-12,42200405,Final,1610612743,1610612748,2022,1.610613e+09,94.0,0.452,0.179,...,57.0,15.0,1.610613e+09,89.0,0.344,0.257,18.0,44.0,8.0,0

In [126]:
## 0. Transform games table from HOME_TEAM, AWAY_TEAM to TEAM, HOME/AWAY 
game_general_cols = ['GAME_DATE_EST', 'GAME_ID', 'SEASON', 'regular_season']
game_home_cols = ['TEAM_ID_home', 'PTS_home', 'FG_PCT_home', 'FG3_PCT_home', 'AST_home', 'REB_home', 'TOV_home']
game_away_cols = ['TEAM_ID_away', 'PTS_away', 'FG_PCT_away', 'FG3_PCT_away', 'AST_away', 'REB_away', 'TOV_away']

team_stat_cols = ['TEAM_PTS', 'TEAM_FG_PCT', 'TEAM_FG3_PCT', 'TEAM_AST', 'TEAM_REB', 'TEAM_TOV']
opp_team_stat_cols = ['OPP_TEAM_PTS', 'OPP_TEAM_FG_PCT', 'OPP_TEAM_FG3_PCT', 'OPP_TEAM_AST', 'OPP_TEAM_REB', 'OPP_TEAM_TOV']
new_column_names = game_general_cols + ['TEAM_ID'] + team_stat_cols + ['OPP_TEAM_ID'] + opp_team_stat_cols

df_gamedays_home = df_games[game_general_cols + game_home_cols + game_away_cols].copy()
# df_gamedays_home = df_games[['GAME_DATE_EST', 'GAME_ID', 'HOME_TEAM_ID', 'PTS_home', 'VISITOR_TEAM_ID', 'PTS_away']].copy()
df_gamedays_home.columns = new_column_names
df_gamedays_home['HOME'] = 1

print(df_gamedays_home.shape)

df_gamedays_away = df_games[game_general_cols + game_away_cols + game_home_cols].copy()
# df_gamedays_away = df_games[['GAME_DATE_EST', 'GAME_ID', 'VISITOR_TEAM_ID', 'PTS_away', 'HOME_TEAM_ID', 'PTS_home']].copy()
df_gamedays_away.columns = new_column_names
df_gamedays_away['HOME'] = 0
print(df_gamedays_away.shape)

## Concatenate the datasets and sort by date/team
df_gamedays = pd.concat([df_gamedays_home, df_gamedays_away], axis=0, ignore_index=True, sort=False).sort_values(by=['GAME_DATE_EST', 'TEAM_ID'])

## add Win column
def win_or_loss(row):
    # if team pts or opp team pts is null then null
    if pd.isnull(row['TEAM_PTS']) or pd.isnull(row['OPP_TEAM_PTS']):
        return np.nan    
    elif row['TEAM_PTS'] > row['OPP_TEAM_PTS']:
        return 1
    else:
        return 0
df_gamedays['WIN'] = df_gamedays.apply(win_or_loss, axis=1)

## remove duplicate game_id and team_id
df_gamedays.drop_duplicates(subset=['GAME_ID', 'TEAM_ID'], inplace=True)

print(df_gamedays.shape)
display(df_gamedays)

(31228, 19)
(31228, 19)
(62438, 20)

,GAME_DATE_EST,GAME_ID,SEASON,regular_season,TEAM_ID,TEAM_PTS,TEAM_FG_PCT,TEAM_FG3_PCT,TEAM_AST,TEAM_REB,TEAM_TOV,OPP_TEAM_ID,OPP_TEAM_PTS,OPP_TEAM_FG_PCT,OPP_TEAM_FG3_PCT,OPP_TEAM_AST,OPP_TEAM_REB,OPP_TEAM_TOV,HOME,WIN
2,2000-10-31,20000004,2000,1,1.610613e+09,82.0,0.370,0.400,14.0,29.0,13.0,1.610613e+09,106.0,0.565,0.556,16.0,44.0,17.0,1,0
31228,2000-10-31,20000002,2000,1,1.610613e+09,86.0,0.410,0.286,16.0,52.0,19.0,1.610613e+09,82.0,0.365,0.300,24.0,47.0,15.0,0,1
6,2000-10-31,20000006,2000,1,1.610613e+09,81.0,0.388,0.750,19.0,29.0,20.0,1.610613e+09,100.0,0.548,0.385,29.0,37.0,18.0,1,0
5,2000-10-31,20000007,2000,1,1.610613e+09,97.0,0.398,0.360,22.0,52.0,18.0,1.610613e+09,93.0,0.398,0.316,16.0,51.0,20.0,1,1
10,2000-10-31,20000011,2000,1,1.610613e+09,96.0,0.405,0.500,18.0,55.0,21.0,1.610613e+09,94.0,0.396,0.286,25.0,44.0,16.0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31225,2023-06-07,42200403,2022,0,1.610613e+09,94.0,0.370,0.314,20.0,33.0,4.0,1.610613e+09,109.0,0.513,0.278,28.0,58.0,14.0,1,0
62454,2023-06-09,42200404,2022,0,1.610613e+09,108.0,0.494,0.500,26.0,34.0,8.0,1.610613e+09,95.0,0.449,0.320,23.0,37.0,15.0,0,1
31226,2023-06-09,42200404,2022,0,1.610613e+09,95.0,0.449,0.320,23.0,37.0,15.0,1.610613e+09,108.0,0.494,0.500,26.0,34.0,8.0,1,0
31227,2023-06-12,42200405,2022,0,1.610613e+09,94.0,0.452,0.179,21.0,57.0,15.0,1.610613e+09,89.0,0.344,0.257,18.0,44.0,8.0,1,1
62455,2023-06-12,42200405,2022,0,1.610613e+09,89.0,0.344,0.257,18.0,44.0,8.0,1.610613e+09,94.0,0.452,0.179,21.0,57.0,15.0,0,0

In [127]:
df_gamedays['GAME_DATE_EST'] = pd.to_datetime(df_gamedays['GAME_DATE_EST'])

## 1. Two features: Get days from previous game and days to next game
df_gamedays['last_game_date'] = df_gamedays.groupby('TEAM_ID')['GAME_DATE_EST'].shift(1)
df_gamedays['days_since_last_game'] = df_gamedays['GAME_DATE_EST'] - df_gamedays['last_game_date']
df_gamedays['days_since_last_game'] = df_gamedays['days_since_last_game'].dt.days.fillna(0).astype(int)

df_gamedays['next_game_date'] = df_gamedays.groupby('TEAM_ID')['GAME_DATE_EST'].shift(-1)
df_gamedays['days_until_next_game'] = df_gamedays['next_game_date'] - df_gamedays['GAME_DATE_EST']
df_gamedays['days_until_next_game'] = df_gamedays['days_until_next_game'].dt.days.fillna(0).astype(int)

## 2. Create two binary features: first_back_to_back, second_back_to_back
# first night of back-to-back if days_since_last_game == 1
df_gamedays['first_back_to_back'] = df_gamedays['days_until_next_game'].apply(lambda x: 1 if x == 1 else 0)

# second night of back-to-back if days_until_next_game == 1
df_gamedays['second_back_to_back'] = df_gamedays['days_since_last_game'].apply(lambda x: 1 if x == 1 else 0)

display(df_gamedays.head())
display(df_gamedays.tail())

,GAME_DATE_EST,GAME_ID,SEASON,regular_season,TEAM_ID,TEAM_PTS,TEAM_FG_PCT,TEAM_FG3_PCT,TEAM_AST,TEAM_REB,...,OPP_TEAM_REB,OPP_TEAM_TOV,HOME,WIN,last_game_date,days_since_last_game,next_game_date,days_until_next_game,first_back_to_back,second_back_to_back
2,2000-10-31,20000004,2000,1,1.610613e+09,82.0,0.370,0.400,14.0,29.0,...,44.0,17.0,1,0,NaT,0,2000-11-02,2,0,0
31228,2000-10-31,20000002,2000,1,1.610613e+09,86.0,0.410,0.286,16.0,52.0,...,47.0,15.0,0,1,NaT,0,2000-11-01,1,1,0
6,2000-10-31,20000006,2000,1,1.610613e+09,81.0,0.388,0.750,19.0,29.0,...,37.0,18.0,1,0,NaT,0,2000-11-03,3,0,0
5,2000-10-31,20000007,2000,1,1.610613e+09,97.0,0.398,0.360,22.0,52.0,...,51.0,20.0,1,1,NaT,0,2000-11-02,2,0,0
10,2000-10-31,20000011,2000,1,1.610613e+09,96.0,0.405,0.500,18.0,55.0,...,44.0,16.0,1,1,NaT,0,2000-11-02,2,0,0

,GAME_DATE_EST,GAME_ID,SEASON,regular_season,TEAM_ID,TEAM_PTS,TEAM_FG_PCT,TEAM_FG3_PCT,TEAM_AST,TEAM_REB,...,OPP_TEAM_REB,OPP_TEAM_TOV,HOME,WIN,last_game_date,days_since_last_game,next_game_date,days_until_next_game,first_back_to_back,second_back_to_back
31225,2023-06-07,42200403,2022,0,1.610613e+09,94.0,0.370,0.314,20.0,33.0,...,58.0,14.0,1,0,2023-06-04,3,2023-06-09,2,0,0
62454,2023-06-09,42200404,2022,0,1.610613e+09,108.0,0.494,0.500,26.0,34.0,...,37.0,15.0,0,1,2023-06-07,2,2023-06-12,3,0,0
31226,2023-06-09,42200404,2022,0,1.610613e+09,95.0,0.449,0.320,23.0,37.0,...,34.0,8.0,1,0,2023-06-07,2,2023-06-12,3,0,0
31227,2023-06-12,42200405,2022,0,1.610613e+09,94.0,0.452,0.179,21.0,57.0,...,44.0,8.0,1,1,2023-06-09,3,NaT,0,0,0
62455,2023-06-12,42200405,2022,0,1.610613e+09,89.0,0.344,0.257,18.0,44.0,...,57.0,15.0,0,0,2023-06-09,3,NaT,0,0,0

In [22]:
# ## 3. Join games table onto season table
# import pandasql as ps

# sqlcode = '''
# select gd.*, s.season, s.season_short, s.min_games, s.max_games, s.number_of_teams, s.preseason_end, s.postseason_start, s.postseason_end
# from df_gamedays gd
# inner join df_seasons s on gd.GAME_DATE_EST>= s.season_start and gd.GAME_DATE_EST <= s.season_end
# '''

# df_gamedays2 = ps.sqldf(sqlcode,locals())

# ## make datetime format yyyy-mm-dd: GAME_DATE_EST, preseason_end, postseason_start, postseason_end, last_game_date, next_game_date
# df_gamedays2['GAME_DATE_EST'] = pd.to_datetime(df_gamedays2['GAME_DATE_EST'])
# df_gamedays2['preseason_end'] = pd.to_datetime(df_gamedays2['preseason_end'])
# df_gamedays2['postseason_start'] = pd.to_datetime(df_gamedays2['postseason_start'])
# df_gamedays2['postseason_end'] = pd.to_datetime(df_gamedays2['postseason_end'])
# df_gamedays2['last_game_date'] = pd.to_datetime(df_gamedays2['last_game_date'])
# df_gamedays2['next_game_date'] = pd.to_datetime(df_gamedays2['next_game_date'])

# display(pd.concat([df_gamedays2.head(3), df_gamedays2.tail(3)], axis=0, sort=False))
# print(df_gamedays2.shape)

,GAME_DATE_EST,GAME_ID,TEAM_ID,TEAM_PTS,TEAM_FG_PCT,TEAM_FG3_PCT,TEAM_AST,TEAM_REB,OPP_TEAM_ID,OPP_TEAM_PTS,...,first_back_to_back,second_back_to_back,season,season_short,min_games,max_games,number_of_teams,preseason_end,postseason_start,postseason_end
0,2003-10-05,10300001,1610612742,85.0,0.447,0.250,20.0,38.0,1610612762,90.0,...,0,0,2003-2004,2004,82,82,29,2003-10-28,2004-04-17,2004-06-15
1,2003-10-05,10300001,1610612762,90.0,0.457,0.143,23.0,41.0,1610612742,85.0,...,0,0,2003-2004,2004,82,82,29,2003-10-28,2004-04-17,2004-06-15
2,2003-10-06,10300002,1610612749,94.0,0.427,0.154,20.0,43.0,1610612763,105.0,...,0,0,2003-2004,2004,82,82,29,2003-10-28,2004-04-17,2004-06-15
53241,2022-12-22,22200477,1610612759,117.0,0.478,0.321,23.0,44.0,1610612740,126.0,...,0,0,2022-2023,2023,82,82,30,2022-10-18,2023-04-16,2023-06-16
53242,2022-12-22,22200478,1610612762,120.0,0.488,0.457,16.0,40.0,1610612764,112.0,...,0,0,2022-2023,2023,82,82,30,2022-10-18,2023-04-16,2023-06-16
53243,2022-12-22,22200478,1610612764,112.0,0.561,0.333,20.0,37.0,1610612762,120.0,...,0,0,2022-2023,2023,82,82,30,2022-10-18,2023-04-16,2023-06-16

(53244, 30)

In [128]:
## 4. Get season level features (regular season game, regular season game pct, etc.)
# sort by team_id, game_date_est
df_gamedays.sort_values(by=['GAME_DATE_EST', 'TEAM_ID'], inplace=True)

# # regular season if between preseason_end and postseason_start
# df_gamedays['regular_season'] = df_gamedays.apply(lambda x: 1 if x['GAME_DATE_EST'] >= x['preseason_end'] and x['GAME_DATE_EST'] < x['postseason_start'] else 0, axis=1)

# # preseason if before preseason_end
# df_gamedays['preseason'] = df_gamedays.apply(lambda x: 1 if x['GAME_DATE_EST'] < x['preseason_end'] else 0, axis=1)

# # postseason if between postseason_start and postseason_end
# df_gamedays['postseason'] = df_gamedays.apply(lambda x: 1 if x['GAME_DATE_EST'] >= x['postseason_start'] and x['GAME_DATE_EST'] <= x['postseason_end'] else 0, axis=1)

# get game number of season for team
df_gamedays['game_number_of_season'] = df_gamedays.groupby(['TEAM_ID', 'SEASON'])['regular_season'].cumsum()

# get total number of regular_season games played by team in season, no less than of min_games
df_gamedays['total_regular_season_games'] = df_gamedays.groupby(['TEAM_ID', 'SEASON'])['regular_season'].transform('sum')
# df_gamedays['total_regular_season_games'] = df_gamedays['total_regular_season_games'].apply(lambda x: x if x >= df_gamedays['min_games'].iloc[0] else df_gamedays['min_games'].iloc[0])

# percentage of regaular season games played - game number divided by max of total regular season games and min_games
df_gamedays['percentage_regular_season_games'] = df_gamedays['game_number_of_season'] / df_gamedays['total_regular_season_games']

# remove all records that are not regular season games
df_gamedays = df_gamedays[df_gamedays['regular_season'] == 1]

display(df_gamedays)

,GAME_DATE_EST,GAME_ID,SEASON,regular_season,TEAM_ID,TEAM_PTS,TEAM_FG_PCT,TEAM_FG3_PCT,TEAM_AST,TEAM_REB,...,WIN,last_game_date,days_since_last_game,next_game_date,days_until_next_game,first_back_to_back,second_back_to_back,game_number_of_season,total_regular_season_games,percentage_regular_season_games
2,2000-10-31,20000004,2000,1,1.610613e+09,82.0,0.370,0.400,14.0,29.0,...,0,NaT,0,2000-11-02,2,0,0,1,82,0.012195
31228,2000-10-31,20000002,2000,1,1.610613e+09,86.0,0.410,0.286,16.0,52.0,...,1,NaT,0,2000-11-01,1,1,0,1,82,0.012195
6,2000-10-31,20000006,2000,1,1.610613e+09,81.0,0.388,0.750,19.0,29.0,...,0,NaT,0,2000-11-03,3,0,0,1,82,0.012195
5,2000-10-31,20000007,2000,1,1.610613e+09,97.0,0.398,0.360,22.0,52.0,...,1,NaT,0,2000-11-02,2,0,0,1,82,0.012195
10,2000-10-31,20000011,2000,1,1.610613e+09,96.0,0.405,0.500,18.0,55.0,...,1,NaT,0,2000-11-02,2,0,0,1,82,0.012195
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62369,2023-04-09,22201228,2022,1,1.610613e+09,117.0,0.505,0.286,31.0,45.0,...,0,2023-04-08,1,NaT,0,0,1,82,82,1.000000
62367,2023-04-09,22201226,2022,1,1.610613e+09,100.0,0.435,0.189,25.0,43.0,...,0,2023-04-07,2,2023-04-16,7,0,0,82,82,1.000000
31135,2023-04-09,22201222,2022,1,1.610613e+09,109.0,0.423,0.311,28.0,51.0,...,0,2023-04-07,2,NaT,0,0,0,82,82,1.000000
62364,2023-04-09,22201223,2022,1,1.610613e+09,81.0,0.365,0.273,20.0,59.0,...,0,2023-04-07,2,NaT,0,0,0,82,82,1.000000
62359,2023-04-09,22201218,2022,1,1.610613e+09,106.0,0.457,0.188,23.0,49.0,...,1,2023-04-07,2,NaT,0,0,0,82,82,1.000000

In [130]:
def per_game_stats_coming_into_game(df, team_cols:t.List, opp_team_cols:t.List) -> pd.DataFrame:
    """
    Get per game stats coming into game for each team

    Args:
        df: dataframe
        team_cols: list of team columns
        opp_team_cols: list of opponent team columns

    Returns:
        dataframe with per game stats coming into game for each team
    """
    df_ = df.copy()
    
    for team_col, opp_col in zip(team_cols, opp_team_cols):
        ## get cumulative average per game and opposing per game for each team up to last game for each season
        # df_[f'{team_col}_per_game'] = df_.groupby(['TEAM_ID', 'SEASON'])[team_col].transform(lambda x: x.shift(1).expanding().mean())
        df_[f'{team_col}_opp_per_game'] = df_.groupby(['TEAM_ID', 'SEASON'])[opp_col].transform(lambda x: x.shift(1).expanding().mean())
        
        # ## get opp_team_ppg and opp_team_opp_ppg
        # df_[f'{opp_col}_per_game'] = df_.groupby([f'OPP_TEAM_ID', 'SEASON'])[opp_col].transform(lambda x: x.shift(1).expanding().mean())
        # df_[f'{opp_col}_opp_per_game'] = df_.groupby([f'OPP_TEAM_ID', 'SEASON'])[team_col].transform(lambda x: x.shift(1).expanding().mean())

    return df_

df_gamedays2 = per_game_stats_coming_into_game(df=df_gamedays, team_cols=team_stat_cols, opp_team_cols=opp_team_stat_cols)

print(df_gamedays2.shape)
for i in range(int(len(df_gamedays2.columns)/10)+1):
    try:
        print(i, list(df_gamedays2.columns[i*10:(i+1)*10]))
    except:
        print(i, list(df_gamedays2.columns[i*10:]))
        break

(55128, 35)
0 ['GAME_DATE_EST', 'GAME_ID', 'SEASON', 'regular_season', 'TEAM_ID', 'TEAM_PTS', 'TEAM_FG_PCT', 'TEAM_FG3_PCT', 'TEAM_AST', 'TEAM_REB']
1 ['TEAM_TOV', 'OPP_TEAM_ID', 'OPP_TEAM_PTS', 'OPP_TEAM_FG_PCT', 'OPP_TEAM_FG3_PCT', 'OPP_TEAM_AST', 'OPP_TEAM_REB', 'OPP_TEAM_TOV', 'HOME', 'WIN']
2 ['last_game_date', 'days_since_last_game', 'next_game_date', 'days_until_next_game', 'first_back_to_back', 'second_back_to_back', 'game_number_of_season', 'total_regular_season_games', 'percentage_regular_season_games', 'TEAM_PTS_opp_per_game']
3 ['TEAM_FG_PCT_opp_per_game', 'TEAM_FG3_PCT_opp_per_game', 'TEAM_AST_opp_per_game', 'TEAM_REB_opp_per_game', 'TEAM_TOV_opp_per_game']

In [134]:
## Create dataframe of rolling averages for team stats
df_team_per_game_expanding = df_gamedays2[['GAME_DATE_EST', 'GAME_ID', 'TEAM_ID', 'SEASON',
    'HOME', 'days_until_next_game', 'TEAM_PTS_opp_per_game', 'TEAM_FG_PCT_opp_per_game',
    'TEAM_FG3_PCT_opp_per_game', 'TEAM_AST_opp_per_game', 'TEAM_REB_opp_per_game'
    ]].rename(columns={'TEAM_PTS_opp_per_game': 'PTS_ALLOWED',
        'TEAM_FG_PCT_opp_per_game': 'FG_PCT_ALLOWED',
        'TEAM_FG3_PCT_opp_per_game': 'FG3_PCT_ALLOWED',
        'TEAM_AST_opp_per_game': 'AST_ALLOWED',
        'TEAM_REB_opp_per_game': 'REB_ALLOWED',
        }).copy()

## get lag game for each team in each season
df_team_per_game_expanding['LAST_GAME_DATE'] = df_team_per_game_expanding.groupby(['TEAM_ID', 'SEASON'])['GAME_DATE_EST'].shift(1)
df_team_per_game_expanding[(df_team_per_game_expanding['TEAM_ID'] == 1610612759) & (df_team_per_game_expanding['SEASON'] == 2022)]

,GAME_DATE_EST,GAME_ID,TEAM_ID,SEASON,HOME,days_until_next_game,PTS_ALLOWED,FG_PCT_ALLOWED,FG3_PCT_ALLOWED,AST_ALLOWED,REB_ALLOWED,LAST_GAME_DATE
29922,2022-10-19,22200011,1.610613e+09,2022,1,2,NaN,NaN,NaN,NaN,NaN,NaT
61157,2022-10-21,22200018,1.610613e+09,2022,0,1,129.000000,0.511000,0.448000,26.000000,51.000000,2022-10-19
61167,2022-10-22,22200028,1.610613e+09,2022,0,2,131.500000,0.500500,0.381000,29.000000,46.500000,2022-10-21
61189,2022-10-24,22200050,1.610613e+09,2022,0,2,122.666667,0.480333,0.361667,28.000000,44.333333,2022-10-22
61201,2022-10-26,22200062,1.610613e+09,2022,0,2,118.500000,0.470750,0.335750,27.000000,45.750000,2022-10-24
...,...,...,...,...,...,...,...,...,...,...,...,...
62311,2023-04-02,22201170,1.610613e+09,2022,0,2,122.701299,0.509857,0.391571,26.558442,44.948052,2023-03-31
62329,2023-04-04,22201188,1.610613e+09,2022,0,2,122.846154,0.509423,0.389756,26.525641,44.923077,2023-04-02
31112,2023-04-06,22201199,1.610613e+09,2022,1,2,122.746835,0.509089,0.388658,26.506329,45.075949,2023-04-04
31127,2023-04-08,22201214,1.610613e+09,2022,1,1,122.800000,0.509363,0.388263,26.600000,44.962500,2023-04-06
62365,2023-04-09,22201224,1.610613e+09,2022,0,0,123.148148,0.509914,0.390358,26.790123,44.962963,2023-04-08

In [135]:
## from df_team_per_game_expanding, get team_id 1610612759 and year of game_date_est is 2022
df_team_per_game_expanding[(df_team_per_game_expanding['TEAM_ID'] == 1610612759) & (df_team_per_game_expanding['GAME_DATE_EST'].dt.year == 2022)].tail(20)
# df_team_per_game_expanding['GAME_DATE_EST']

,GAME_DATE_EST,GAME_ID,TEAM_ID,SEASON,HOME,days_until_next_game,PTS_ALLOWED,FG_PCT_ALLOWED,FG3_PCT_ALLOWED,AST_ALLOWED,REB_ALLOWED,LAST_GAME_DATE
61378,2022-11-19,22200239,1.610613e+09,2022,0,1,120.187500,0.505375,0.389250,27.750000,43.625000,2022-11-17
61386,2022-11-20,22200247,1.610613e+09,2022,0,3,120.117647,0.507588,0.397235,28.000000,43.117647,2022-11-19
30180,2022-11-23,22200269,1.610613e+09,2022,1,2,120.277778,0.508778,0.394778,28.055556,43.722222,2022-11-20
30193,2022-11-25,22200282,1.610613e+09,2022,1,1,120.736842,0.512158,0.396316,28.315789,43.631579,2022-11-23
30200,2022-11-26,22200288,1.610613e+09,2022,1,4,119.950000,0.510650,0.391300,28.300000,43.900000,2022-11-25
61459,2022-11-30,22200319,1.610613e+09,2022,0,2,121.047619,0.513952,0.397190,28.142857,43.666667,2022-11-26
30245,2022-12-02,22200333,1.610613e+09,2022,1,2,120.954545,0.513818,0.394273,27.636364,44.045455,2022-11-30
30257,2022-12-04,22200345,1.610613e+09,2022,1,4,120.782609,0.510391,0.389565,27.521739,44.434783,2022-12-02
30287,2022-12-08,22200375,1.610613e+09,2022,1,2,121.291667,0.510833,0.394750,27.958333,44.458333,2022-12-04
61527,2022-12-10,22200387,1.610613e+09,2022,0,2,120.800000,0.508360,0.392760,27.760000,44.360000,2022-12-08
30318,2022-12-12,22200406,1.610613e+09,2022,1,2,120.423077,0.507308,0.392346,27.692308,43.884615,2022-12-10
30332,2022-12-14,22200420,1.610613e+09,2022,1,3,120.074074,0.506630,0.385852,27.444444,43.888889,2022-12-12
30351,2022-12-17,22200439,1.610613e+09,2022,1,2,120.357143,0.510143,0.388143,27.392857,43.750000,2022-12-14
61595,2022-12-19,22200455,1.610613e+09,2022,0,3,120.034483,0.510207,0.387414,27.310345,43.620690,2022-12-17
61617,2022-12-22,22200477,1.610613e+09,2022,0,1,119.533333,0.507400,0.381433,27.166667,43.533333,2022-12-19
61619,2022-12-23,22200479,1.610613e+09,2022,0,3,119.741935,0.506645,0.381452,27.096774,43.612903,2022-12-22
30415,2022-12-26,22200503,1.610613e+09,2022,1,1,120.156250,0.508781,0.386125,27.187500,43.625000,2022-12-23
61651,2022-12-27,22200511,1.610613e+09,2022,0,2,120.212121,0.505545,0.383576,26.969697,43.666667,2022-12-26
30439,2022-12-29,22200527,1.610613e+09,2022,1,2,120.500000,0.506412,0.388235,26.911765,43.705882,2022-12-27
30454,2022-12-31,22200542,1.610613e+09,2022,1,2,120.342857,0.504000,0.387600,26.714286,43.542857,2022-12-29

In [136]:
## Get next 5 opponents for each team
df_gamedays2, next_opp_cols = get_all_lags(df=df_gamedays2, cols=['OPP_TEAM_ID'], group_cols=['TEAM_ID', 'SEASON'], n_lags=-5)
display_cols = ['GAME_DATE_EST', 'TEAM_ID', 'SEASON'] + next_opp_cols

display_df = df_gamedays2.loc[(df_gamedays2['TEAM_ID'] == 1610612759) & (df_gamedays2['SEASON'] == 2022), display_cols].head(8)
display_df[next_opp_cols] = display_df[next_opp_cols].astype(int)
display(display_df)
display_df = df_gamedays2.loc[(df_gamedays2['TEAM_ID'] == 1610612759) & (df_gamedays2['SEASON'] == 2022), display_cols].tail(5)
display(display_df)

,GAME_DATE_EST,TEAM_ID,SEASON,next_0_OPP_TEAM_ID,next_1_OPP_TEAM_ID,next_2_OPP_TEAM_ID,next_3_OPP_TEAM_ID,next_4_OPP_TEAM_ID
29922,2022-10-19,1.610613e+09,2022,1610612766,1610612754,1610612755,1610612750,1610612750
61157,2022-10-21,1.610613e+09,2022,1610612754,1610612755,1610612750,1610612750,1610612741
61167,2022-10-22,1.610613e+09,2022,1610612755,1610612750,1610612750,1610612741,1610612750
61189,2022-10-24,1.610613e+09,2022,1610612750,1610612750,1610612741,1610612750,1610612761
61201,2022-10-26,1.610613e+09,2022,1610612750,1610612741,1610612750,1610612761,1610612746
29988,2022-10-28,1.610613e+09,2022,1610612741,1610612750,1610612761,1610612746,1610612743
30003,2022-10-30,1.610613e+09,2022,1610612750,1610612761,1610612746,1610612743,1610612743
30025,2022-11-02,1.610613e+09,2022,1610612761,1610612746,1610612743,1610612743,1610612763

,GAME_DATE_EST,TEAM_ID,SEASON,next_0_OPP_TEAM_ID,next_1_OPP_TEAM_ID,next_2_OPP_TEAM_ID,next_3_OPP_TEAM_ID,next_4_OPP_TEAM_ID
62311,2023-04-02,1.610613e+09,2022,1.610613e+09,1.610613e+09,1.610613e+09,1.610613e+09,1.610613e+09
62329,2023-04-04,1.610613e+09,2022,1.610613e+09,1.610613e+09,1.610613e+09,1.610613e+09,NaN
31112,2023-04-06,1.610613e+09,2022,1.610613e+09,1.610613e+09,1.610613e+09,NaN,NaN
31127,2023-04-08,1.610613e+09,2022,1.610613e+09,1.610613e+09,NaN,NaN,NaN
62365,2023-04-09,1.610613e+09,2022,1.610613e+09,NaN,NaN,NaN,NaN

In [28]:
## Joins
import pandasql as ps
def query_forecast(game_num:int, df_gamedays_fc: pd.DataFrame, df_team_per_game_expanding: pd.DataFrame) -> pd.DataFrame:
    join_cols = ['HOME', 'days_until_next_game', 'PTS_ALLOWED', 'FG_PCT_ALLOWED', 'FG3_PCT_ALLOWED', 'AST_ALLOWED', 'REB_ALLOWED']
    select_str = ', '.join([f'per_game.{col} as next_{game_num}_{col}' for col in join_cols])

    sqlcode = dedent(f'''
        SELECT fc.*,
            {select_str}
        FROM df_gamedays_fc fc
        LEFT JOIN df_team_per_game_expanding per_game
            ON (fc.next_{game_num}_OPP_TEAM_ID = per_game.TEAM_ID)
                AND (fc.GAME_DATE_EST <= per_game.GAME_DATE_EST)
                AND (fc.GAME_DATE_EST > per_game.LAST_GAME_DATE)
        ;
        ''')

    df = ps.sqldf(sqlcode, locals())
    return df


df_gamedays_fc = df_gamedays2.copy()

## merge df_team_per_game_expanding onto df_gamedays2 on GAME_ID and df_team_per_game_expanding.TEAM_ID = df_gamedays2.next_X_OPP_TEAM_ID for X in range(5), and drop duplicate columns
# df_team_per_game_expanding = df_team_per_game_expanding[['GAME_ID', 'TEAM_ID', 'PTS_ALLOWED', 'FG_PCT_ALLOWED', 'FG3_PCT_ALLOWED', 'AST_ALLOWED', 'REB_ALLOWED']]
for i in range(5):
    df_gamedays_fc = query_forecast(game_num=i, df_gamedays_fc=df_gamedays_fc, df_team_per_game_expanding=df_team_per_game_expanding)

df_gamedays_fc['GAME_DATE_EST'] = pd.to_datetime(df_gamedays_fc['GAME_DATE_EST'])
df_gamedays_fc

,GAME_DATE_EST,GAME_ID,TEAM_ID,TEAM_PTS,TEAM_FG_PCT,TEAM_FG3_PCT,TEAM_AST,TEAM_REB,OPP_TEAM_ID,OPP_TEAM_PTS,...,next_3_FG3_PCT_ALLOWED,next_3_AST_ALLOWED,next_3_REB_ALLOWED,next_4_HOME,next_4_days_until_next_game,next_4_PTS_ALLOWED,next_4_FG_PCT_ALLOWED,next_4_FG3_PCT_ALLOWED,next_4_AST_ALLOWED,next_4_REB_ALLOWED
0,2003-10-28,20300003,1610612742,93.0,0.376,0.280,17.0,46.0,1610612747,109.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2003-10-28,20300003,1610612747,109.0,0.506,0.350,32.0,46.0,1610612742,93.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2003-10-28,20300001,1610612748,74.0,0.408,0.250,16.0,44.0,1610612755,89.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2003-10-28,20300001,1610612755,89.0,0.440,0.350,25.0,39.0,1610612748,74.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2003-10-28,20300002,1610612756,82.0,0.361,0.500,14.0,43.0,1610612759,83.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46575,2022-12-21,22200476,1610612766,105.0,0.402,0.290,25.0,40.0,1610612746,126.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46576,2022-12-22,22200477,1610612740,126.0,0.484,0.382,25.0,46.0,1610612759,117.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46577,2022-12-22,22200477,1610612759,117.0,0.478,0.321,23.0,44.0,1610612740,126.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46578,2022-12-22,22200478,1610612762,120.0,0.488,0.457,16.0,40.0,1610612764,112.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46579,2022-12-22,22200478,1610612764,112.0,0.561,0.333,20.0,37.0,1610612762,120.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
# display 30 rows and 60 columns
pd.set_option('display.max_rows', 30)
pd.set_option('display.max_columns', 60)

team_id_focus = 1610612759
display_cols = ['GAME_DATE_EST', 'GAME_ID', 'TEAM_ID', 'TEAM_PTS', 'TEAM_FG_PCT', 'TEAM_FG3_PCT', 'TEAM_AST', 'TEAM_REB', 'OPP_TEAM_ID', 'OPP_TEAM_PTS',
                'OPP_TEAM_FG_PCT', 'OPP_TEAM_FG3_PCT', 'OPP_TEAM_AST', 'OPP_TEAM_REB', 'SEASON']
display_df_current = df_gamedays_fc.loc[(df_gamedays_fc['TEAM_ID'] == team_id_focus) & (df_gamedays_fc['SEASON'] == 2022), display_cols].head(10)
display(display_df_current)


game_num = 4
opp_rolling_per_game_cols = [c for c in df_gamedays_fc.columns if f'next_{game_num}' in c]
display_cols = ['GAME_DATE_EST', 'GAME_ID', 'TEAM_ID', 'SEASON'] + opp_rolling_per_game_cols
display_df_future = df_gamedays_fc.loc[(df_gamedays_fc[f'next_{game_num}_OPP_TEAM_ID'] == team_id_focus) & (df_gamedays_fc['SEASON'] == 2022), display_cols].head(10)
display_df_future[f'next_{game_num}_OPP_TEAM_ID'] = display_df_future[f'next_{game_num}_OPP_TEAM_ID'].astype(int)
display(display_df_future)
## show all opp_team columns as integers

,GAME_DATE_EST,GAME_ID,TEAM_ID,TEAM_PTS,TEAM_FG_PCT,TEAM_FG3_PCT,TEAM_AST,TEAM_REB,OPP_TEAM_ID,OPP_TEAM_PTS,OPP_TEAM_FG_PCT,OPP_TEAM_FG3_PCT,OPP_TEAM_AST,OPP_TEAM_REB,season_short
45646,2022-10-19,22200011,1610612759,102.0,0.404,0.206,22.0,44.0,1610612766,129.0,0.511,0.448,26.0,51.0,2023
45673,2022-10-21,22200018,1610612759,137.0,0.543,0.548,34.0,37.0,1610612754,134.0,0.490,0.314,32.0,42.0,2023
45693,2022-10-22,22200028,1610612759,114.0,0.483,0.421,27.0,43.0,1610612755,105.0,0.440,0.323,26.0,40.0,2023
45724,2022-10-24,22200050,1610612759,115.0,0.457,0.324,37.0,50.0,1610612750,106.0,0.442,0.258,24.0,50.0,2023
45751,2022-10-26,22200062,1610612759,122.0,0.453,0.444,34.0,41.0,1610612750,134.0,0.650,0.588,37.0,30.0,2023
45780,2022-10-28,22200077,1610612759,129.0,0.535,0.421,37.0,42.0,1610612741,124.0,0.475,0.333,20.0,42.0,2023
45813,2022-10-30,22200092,1610612759,107.0,0.419,0.400,27.0,52.0,1610612750,98.0,0.404,0.138,21.0,45.0,2023
45853,2022-11-02,22200114,1610612759,100.0,0.394,0.326,29.0,46.0,1610612761,143.0,0.538,0.424,31.0,50.0,2023
45881,2022-11-04,22200126,1610612759,106.0,0.477,0.387,23.0,35.0,1610612746,113.0,0.525,0.455,26.0,44.0,2023
45901,2022-11-05,22200138,1610612759,101.0,0.488,0.400,28.0,28.0,1610612743,126.0,0.609,0.517,37.0,47.0,2023

,GAME_DATE_EST,GAME_ID,TEAM_ID,season_short,next_4_OPP_TEAM_ID,next_4_HOME,next_4_days_until_next_game,next_4_PTS_ALLOWED,next_4_FG_PCT_ALLOWED,next_4_FG3_PCT_ALLOWED,next_4_AST_ALLOWED,next_4_REB_ALLOWED
45638,2022-10-19,22200010,1610612750,2023,1610612759,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45661,2022-10-21,22200019,1610612741,2023,1610612759,0.0,1.0,129.000000,0.511000,0.448000,26.000000,51.000000
45704,2022-10-23,22200041,1610612750,2023,1610612759,0.0,2.0,122.666667,0.480333,0.361667,28.000000,44.333333
45725,2022-10-24,22200045,1610612761,2023,1610612759,0.0,2.0,122.666667,0.480333,0.361667,28.000000,44.333333
45739,2022-10-26,22200064,1610612743,2023,1610612759,0.0,2.0,118.500000,0.470750,0.335750,27.000000,45.750000
45758,2022-10-27,22200067,1610612746,2023,1610612759,1.0,2.0,121.600000,0.506600,0.386200,29.000000,42.600000
45769,2022-10-28,22200078,1610612743,2023,1610612759,1.0,2.0,121.600000,0.506600,0.386200,29.000000,42.600000
45856,2022-11-02,22200116,1610612763,2023,1610612759,1.0,2.0,118.571429,0.487429,0.343143,26.571429,42.857143
45869,2022-11-04,22200128,1610612744,2023,1610612759,1.0,1.0,121.625000,0.493750,0.353250,27.125000,43.750000
45873,2022-11-04,22200129,1610612749,2023,1610612759,1.0,1.0,121.625000,0.493750,0.353250,27.125000,43.750000

### Initial Game Detail table

In [30]:
def get_min(time_str):
    """Get minutes from time (MM:SS)"""
    if pd.isna(time_str): return np.nan
    try:
        m, s = time_str.split(':')
        mins = float(m) + float(s)/60
    except:
        mins = float(time_str)
    return mins

def game_played(min:float):
    """Binary variable if player played game"""
    # if min is null
    if np.isnan(min):
        return 0
    elif min < 1:
        return 0
    return 1

def comment_cat(comment_str):
    try:
        code, reason = comment_str.split('-', maxsplit=1)
        return code.strip(), reason.strip()
    except:
        return comment_str, comment_str

In [31]:
df_game_detail_fill_staging = pd.merge(df_gamedays2, df_game_detail, on=['GAME_ID', 'TEAM_ID'], how='inner')
drop_cols_initial_detail = [c for c in df_gamedays2.columns if c not in ['GAME_DATE_EST', 'SEASON', 'GAME_ID', 'TEAM_ID']]
df_game_detail_fill_staging.drop(drop_cols_initial_detail, axis=1, inplace=True)

df_game_detail_fill_staging['GAME_DATE_EST'] = pd.to_datetime(df_game_detail_fill_staging['GAME_DATE_EST'])
df_game_detail_fill_staging['next_game_played_date'] = df_game_detail_fill_staging.groupby(['PLAYER_ID', 'SEASON'])['GAME_DATE_EST'].shift(-1)
df_game_detail_fill_staging['last_game_played_date'] = df_game_detail_fill_staging.groupby(['PLAYER_ID', 'SEASON'])['GAME_DATE_EST'].shift(1)

df_game_detail_fill_staging

,GAME_DATE_EST,GAME_ID,TEAM_ID,season_short,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,NICKNAME,START_POSITION,COMMENT,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS,PLUS_MINUS,next_game_played_date,last_game_played_date
0,2003-10-28,20300003,1610612742,2004,DAL,Dallas,952,Antoine Walker,NaN,F,NaN,33:26,7.0,13.0,0.538,5.0,6.0,0.833,0.0,0.0,0.00,2.0,5.0,7.0,1.0,0.0,0.0,2.0,3.0,19.0,-16.0,2003-10-29,NaT
1,2003-10-28,20300003,1610612742,2004,DAL,Dallas,1717,Dirk Nowitzki,NaN,F,NaN,33:11,5.0,17.0,0.294,0.0,6.0,0.000,9.0,12.0,0.75,3.0,10.0,13.0,1.0,1.0,1.0,3.0,2.0,19.0,-20.0,2003-10-29,NaT
2,2003-10-28,20300003,1610612742,2004,DAL,Dallas,1504,Danny Fortson,NaN,C,NaN,13:42,0.0,0.0,0.000,0.0,0.0,0.000,0.0,2.0,0.00,0.0,3.0,3.0,0.0,0.0,0.0,0.0,1.0,0.0,-23.0,2003-10-29,NaT
3,2003-10-28,20300003,1610612742,2004,DAL,Dallas,714,Michael Finley,NaN,G,NaN,28:59,2.0,8.0,0.250,0.0,4.0,0.000,8.0,8.0,1.00,0.0,4.0,4.0,1.0,0.0,0.0,1.0,1.0,12.0,-14.0,2003-10-29,NaT
4,2003-10-28,20300003,1610612742,2004,DAL,Dallas,959,Steve Nash,NaN,G,NaN,28:40,4.0,10.0,0.400,0.0,4.0,0.000,0.0,0.0,0.00,0.0,0.0,0.0,7.0,0.0,0.0,4.0,4.0,8.0,-24.0,2003-10-29,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
579657,2022-12-22,22200478,1610612764,2023,WAS,Washington,1630692,Jordan Goodwin,Jordan,NaN,NaN,15:45,5.0,9.0,0.556,1.0,2.0,0.500,0.0,0.0,0.00,0.0,5.0,5.0,2.0,0.0,1.0,2.0,2.0,11.0,-9.0,NaT,2022-12-20
579658,2022-12-22,22200478,1610612764,2023,WAS,Washington,203115,Will Barton,Will,NaN,NaN,13:53,1.0,5.0,0.200,1.0,3.0,0.333,1.0,2.0,0.50,0.0,2.0,2.0,2.0,0.0,0.0,0.0,1.0,4.0,-20.0,NaT,2022-12-20
579659,2022-12-22,22200478,1610612764,2023,WAS,Washington,1629653,Devon Dotson,Devon,NaN,NaN,3:11,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.00,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,8.0,NaT,2022-12-18
579660,2022-12-22,22200478,1610612764,2023,WAS,Washington,1631098,Johnny Davis,Johnny,NaN,NaN,3:11,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,NaT,2022-12-18
579661,2022-12-22,22200478,1610612764,2023,WAS,Washington,1630264,Anthony Gill,Anthony,NaN,NaN,3:11,1.0,1.0,1.000,0.0,0.0,0.000,1.0,2.0,0.50,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,3.0,8.0,NaT,2022-12-20

In [32]:
def player_season_agg(x):
    names = {'min_date': x['GAME_DATE_EST'].min(), }
            #  'max_date': x['GAME_DATE_EST'].max()}
    return pd.Series(names, index=['min_date']) # , 'max_date'])

pd.set_option("display.max_rows", 30)

player_szn_group_cols = ['PLAYER_ID', 'PLAYER_NAME', 'TEAM_ID', 'SEASON']
player_seasons = df_game_detail_fill_staging.groupby(player_szn_group_cols).apply(player_season_agg).reset_index()
player_seasons.sort_values(by=['PLAYER_ID', 'SEASON', 'TEAM_ID'], inplace=True)
player_seasons.drop_duplicates(subset=['PLAYER_ID', 'SEASON', 'TEAM_ID'], inplace=True)

# create feature: max_date, which is the min_date of the next row for each player_id and season_short
player_seasons['max_date'] = player_seasons.groupby(['PLAYER_ID', 'SEASON'])['min_date'].shift(-1)

## create features: first_team_of_season (which is the first row for each player_id and season_short) and last_team_of_season
player_seasons['first_team_of_season'] = player_seasons.groupby(['PLAYER_ID', 'SEASON'])['TEAM_ID'].transform('first')
player_seasons['last_team_of_season'] = player_seasons.groupby(['PLAYER_ID', 'SEASON'])['TEAM_ID'].transform('last')
display(player_seasons)

# get unique player ids from player_seasons
player_ids = player_seasons['PLAYER_ID'].unique()
print('total number of unique player ids:', len(player_ids))

# get then print player IDs in player_seasons for some PLAYER_NAMEs
some_players = ['LeBron James', 'Nikola Jokic', 'Stephen Curry', 'Jimmy Butler', 'Cade Cunningham', 'Zach Collins', 'Kristaps Porzingis']
some_players_seasons = player_seasons[player_seasons['PLAYER_NAME'].isin(some_players)]
print('player/season combinations for these select players:', some_players_seasons.shape[0])
display(some_players_seasons)

some_player_ids = some_players_seasons['PLAYER_ID'].unique()
print('unique player ids:\n', some_player_ids)

,PLAYER_ID,PLAYER_NAME,TEAM_ID,season_short,min_date,max_date,first_team_of_season,last_team_of_season
2,15,Eric Piatkowski,1610612745,2004,2003-11-24,NaT,1610612745,1610612745
0,15,Eric Piatkowski,1610612741,2005,2004-11-05,NaT,1610612741,1610612741
1,15,Eric Piatkowski,1610612741,2006,2005-11-02,NaT,1610612741,1610612741
3,15,Eric Piatkowski,1610612756,2007,2006-10-31,NaT,1610612756,1610612756
4,15,Eric Piatkowski,1610612756,2008,2007-11-01,NaT,1610612756,1610612756
...,...,...,...,...,...,...,...,...
11195,1631298,Jack White,1610612743,2023,2022-10-21,NaT,1610612743,1610612743
11196,1631306,Cole Swider,1610612747,2023,2022-10-18,NaT,1610612747,1610612747
11197,1631309,Trevor Hudgins,1610612745,2023,2022-10-19,NaT,1610612745,1610612745
11198,1631320,Chima Moneke,1610612758,2023,2022-10-19,NaT,1610612758,1610612758
11199,1631323,Simone Fontecchio,1610612762,2023,2022-10-19,NaT,1610612762,1610612762

total number of unique player ids: 2094
player/season combinations for these select players: 71

,PLAYER_ID,PLAYER_NAME,TEAM_ID,season_short,min_date,max_date,first_team_of_season,last_team_of_season
2655,2544,LeBron James,1610612739,2004,2003-10-29,NaT,1610612739,1610612739
2656,2544,LeBron James,1610612739,2005,2004-11-03,NaT,1610612739,1610612739
2657,2544,LeBron James,1610612739,2006,2005-11-02,NaT,1610612739,1610612739
2658,2544,LeBron James,1610612739,2007,2006-11-01,NaT,1610612739,1610612739
2659,2544,LeBron James,1610612739,2008,2007-10-31,NaT,1610612739,1610612739
...,...,...,...,...,...,...,...,...
9648,1628380,Zach Collins,1610612757,2021,2021-01-28,NaT,1610612757,1610612757
9649,1628380,Zach Collins,1610612759,2022,2021-11-07,NaT,1610612759,1610612759
9650,1628380,Zach Collins,1610612759,2023,2022-10-19,NaT,1610612759,1610612759
11078,1630595,Cade Cunningham,1610612765,2022,2021-10-30,NaT,1610612765,1610612765
11079,1630595,Cade Cunningham,1610612765,2023,2022-10-19,NaT,1610612765,1610612765

unique player ids:
 [   2544  201939  202710  203999  204001 1628380 1630595]

In [33]:
## 3. Join games table onto season table
import pandasql as ps

season_table = "player_seasons" # "player_seasons" or "some_players_seasons"

sqlcode = f'''
    select team.GAME_DATE_EST as staging_game_date_est,
        team.TEAM_ID as staging_team_id,
        team.GAME_ID as staging_game_id,
        team.season_short as staging_season_short,
        season.PLAYER_ID as staging_player_id,
        season.PLAYER_NAME as staging_player_name,
        player.*
    from df_gamedays2 team
    inner join {season_table} season
        on team.season_short = season.season_short
            and team.TEAM_ID = season.TEAM_ID
            and ((team.TEAM_ID = season.first_team_of_season) or (team.GAME_DATE_EST >= season.min_date))
            and ((team.TEAM_ID = season.last_team_of_season) or (team.GAME_DATE_EST < season.max_date))
    left join df_game_detail_fill_staging player
        on season.PLAYER_ID = player.PLAYER_ID
            and team.GAME_ID = player.GAME_ID
            and team.TEAM_ID = player.TEAM_ID
            and team.season_short = player.season_short
            and (
                ((player.next_game_played_date is null) and (team.GAME_DATE_EST > player.GAME_DATE_EST))
                or ((player.last_game_played_date is null) and (team.GAME_DATE_EST <= player.GAME_DATE_EST))
                or ((player.next_game_played_date is not null) and (player.last_game_played_date is not null) and
                    (team.GAME_DATE_EST >= player.GAME_DATE_EST) and (team.GAME_DATE_EST < player.next_game_played_date))
            )
    ;
    '''

players_games_filled = ps.sqldf(sqlcode,locals())
display(players_games_filled[(players_games_filled['staging_player_name'] == 'Cade Cunningham')].head(6))

,staging_game_date_est,staging_team_id,staging_game_id,staging_season_short,staging_player_id,staging_player_name,GAME_DATE_EST,GAME_ID,TEAM_ID,season_short,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,NICKNAME,START_POSITION,COMMENT,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS,PLUS_MINUS,next_game_played_date,last_game_played_date
699957,2021-10-20 00:00:00.000000,1610612765,22100004,2022,1630595,Cade Cunningham,None,NaN,NaN,NaN,None,None,NaN,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None
700855,2021-10-23 00:00:00.000000,1610612765,22100030,2022,1630595,Cade Cunningham,None,NaN,NaN,NaN,None,None,NaN,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None
701458,2021-10-25 00:00:00.000000,1610612765,22100043,2022,1630595,Cade Cunningham,None,NaN,NaN,NaN,None,None,NaN,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None
702344,2021-10-28 00:00:00.000000,1610612765,22100065,2022,1630595,Cade Cunningham,None,NaN,NaN,NaN,None,None,NaN,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None
703097,2021-10-30 00:00:00.000000,1610612765,22100079,2022,1630595,Cade Cunningham,2021-10-30 00:00:00.000000,22100079.0,1.610613e+09,2022.0,DET,Detroit,1630595.0,Cade Cunningham,Cade,G,None,18:55,1.0,8.0,0.125,0.0,5.0,0.0,0.0,0.0,0.0,2.0,5.0,7.0,2.0,0.0,1.0,2.0,0.0,2.0,1.0,2021-11-02 00:00:00.000000,None
703280,2021-10-31 00:00:00.000000,1610612765,22100092,2022,1630595,Cade Cunningham,None,NaN,NaN,NaN,None,None,NaN,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None

In [34]:
## convert any field with date in it to datetime
date_cols = [c for c in players_games_filled.columns if 'date' in c.lower()]
for c in date_cols:
    players_games_filled[c] = pd.to_datetime(players_games_filled[c])

players_games_filled.loc[(players_games_filled['staging_season_short'] == 2022)]

,staging_game_date_est,staging_team_id,staging_game_id,staging_season_short,staging_player_id,staging_player_name,GAME_DATE_EST,GAME_ID,TEAM_ID,season_short,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,NICKNAME,START_POSITION,COMMENT,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS,PLUS_MINUS,next_game_played_date,last_game_played_date
699448,2021-10-19,1610612744,22100002,2022,2738,Andre Iguodala,2021-10-19,22100002.0,1.610613e+09,2022.0,GSW,Golden State,2738.0,Andre Iguodala,Andre,None,None,22:58,4.0,7.0,0.571,2.0,5.0,0.40,2.0,2.0,1.0,0.0,1.0,1.0,2.0,0.0,1.0,0.0,1.0,12.0,8.0,2021-10-21,NaT
699449,2021-10-19,1610612744,22100002,2022,201939,Stephen Curry,2021-10-19,22100002.0,1.610613e+09,2022.0,GSW,Golden State,201939.0,Stephen Curry,Stephen,G,None,36:11,5.0,21.0,0.238,2.0,8.0,0.25,9.0,9.0,1.0,1.0,9.0,10.0,10.0,3.0,0.0,4.0,1.0,21.0,4.0,2021-10-21,NaT
699450,2021-10-19,1610612744,22100002,2022,202357,Nemanja Bjelica,2021-10-19,22100002.0,1.610613e+09,2022.0,GSW,Golden State,202357.0,Nemanja Bjelica,Nemanja,None,None,25:55,6.0,7.0,0.857,1.0,1.0,1.00,2.0,2.0,1.0,2.0,9.0,11.0,4.0,1.0,0.0,1.0,2.0,15.0,20.0,2021-10-21,NaT
699451,2021-10-19,1610612744,22100002,2022,202691,Klay Thompson,NaT,NaN,NaN,NaN,None,None,NaN,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT
699452,2021-10-19,1610612744,22100002,2022,203110,Draymond Green,2021-10-19,22100002.0,1.610613e+09,2022.0,GSW,Golden State,203110.0,Draymond Green,Draymond,F,None,29:56,2.0,5.0,0.400,0.0,0.0,0.00,2.0,4.0,0.5,3.0,5.0,8.0,6.0,1.0,0.0,5.0,3.0,6.0,-2.0,2021-10-21,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
750630,2022-04-15,1610612746,52100211,2022,1629875,Xavier Moon,NaT,NaN,NaN,NaN,None,None,NaN,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT
750631,2022-04-15,1610612746,52100211,2022,1630206,Jay Scrubb,NaT,NaN,NaN,NaN,None,None,NaN,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT
750632,2022-04-15,1610612746,52100211,2022,1630527,Brandon Boston Jr.,NaT,NaN,NaN,NaN,None,None,NaN,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT
750633,2022-04-15,1610612746,52100211,2022,1630554,Jason Preston,NaT,NaN,NaN,NaN,None,None,NaN,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT
750634,2022-04-15,1610612746,52100211,2022,1630589,Moses Wright,NaT,NaN,NaN,NaN,None,None,NaN,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT

In [35]:
df_game_detail_ts = players_games_filled.copy()

## check if any "staging_"* columns are null
staging_cols = [c for c in df_game_detail_ts.columns if 'staging_' in c.lower()]
print('staging cols with nulls:', df_game_detail_ts[staging_cols].isnull().any().sum())

## fill nulls in "staging_"* columns with previous non-null value for group of staging_player_id and staging_season_short ordered by staging_game_date_est
df_game_detail_ts[staging_cols] = df_game_detail_ts.groupby(['staging_player_id', 'staging_season_short'])[staging_cols].ffill()

## rename "staging_"* columns and drop the columns they are replacing
df_game_detail_ts.drop(columns=['GAME_DATE_EST', 'TEAM_ID', 'SEASON', 'PLAYER_ID', 'PLAYER_NAME', 'GAME_ID'], inplace=True)
df_game_detail_ts.rename(
    columns={'staging_game_date_est': 'GAME_DATE_EST',
            'staging_team_id': 'TEAM_ID',
            'staging_game_id': 'GAME_ID',
            'staging_season_short': 'SEASON',
            'staging_player_id': 'PLAYER_ID',
            'staging_player_name': 'PLAYER_NAME'},
    inplace=True)

## Get minutes as float
df_game_detail_ts['MIN'] = df_game_detail_ts['MIN'].apply(get_min)

## Get binary variable if player played game
df_game_detail_ts['game_played'] = df_game_detail_ts['MIN'].apply(game_played)

## Get comment code and reason
df_game_detail_ts['comment_code'], df_game_detail_ts['comment_reason'] = zip(*df_game_detail_ts['COMMENT'].apply(comment_cat))

## Change to per minute stats
cols_to_make_per_min = \
    ['FGM', 'FGA', 'FG3M', 'FG3A', 'FTM', 'FTA', 'OREB', 'DREB',
    'REB', 'AST', 'STL', 'BLK', 'TO', 'PTS', 'PLUS_MINUS', 'PF',
    ]
per_min_cols = [x + '_pm' for x in cols_to_make_per_min]

arr1 = np.array(df_game_detail_ts[cols_to_make_per_min])
arr2 = np.array(df_game_detail_ts['MIN'])

df_per_min = pd.DataFrame(np.where(arr2==0, np.nan, arr1.T/arr2).T, columns=per_min_cols)
# df_per_min = pd.DataFrame((arr1.T / arr2).T, columns=per_min_cols)  # divide warnings were turned off earlier
df_game_detail_ts = pd.concat([df_game_detail_ts, df_per_min], axis=1)

## this time keep 'GAME_ID', 'TEAM_ID', 'PLAYER_ID', 'PLAYER_NAME'
df_game_detail_ts.drop(['TEAM_CITY', 'TEAM_ABBREVIATION', 'NICKNAME', 'COMMENT'], axis=1, inplace=True)

print(df_game_detail_ts.shape)
display(df_game_detail_ts.head())
display(df_game_detail_ts.tail(15))

staging cols with nulls: 0

C:\Users\BrandonBrown\AppData\Local\Temp\ipykernel_17064\1404492822.py:40: RuntimeWarning: divide by zero encountered in divide
  df_per_min = pd.DataFrame(np.where(arr2==0, np.nan, arr1.T/arr2).T, columns=per_min_cols)
C:\Users\BrandonBrown\AppData\Local\Temp\ipykernel_17064\1404492822.py:40: RuntimeWarning: invalid value encountered in divide
  df_per_min = pd.DataFrame(np.where(arr2==0, np.nan, arr1.T/arr2).T, columns=per_min_cols)

(766375, 48)

,GAME_DATE_EST,TEAM_ID,GAME_ID,season_short,PLAYER_ID,PLAYER_NAME,START_POSITION,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS,PLUS_MINUS,next_game_played_date,last_game_played_date,game_played,comment_code,comment_reason,FGM_pm,FGA_pm,FG3M_pm,FG3A_pm,FTM_pm,FTA_pm,OREB_pm,DREB_pm,REB_pm,AST_pm,STL_pm,BLK_pm,TO_pm,PTS_pm,PLUS_MINUS_pm,PF_pm
0,2003-10-28,1610612742,20300003,2004,281,Scott Williams,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,0,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2003-10-28,1610612742,20300003,2004,696,Travis Best,None,16.200000,0.0,5.0,0.000,0.0,1.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,4.0,2.0,0.0,1.0,2.0,0.0,8.0,2003-10-29,NaT,1,None,None,0.000000,0.308642,0.000000,0.061728,0.000000,0.000000,0.000000,0.000000,0.000000,0.246914,0.123457,0.0,0.061728,0.000000,0.493827,0.123457
2,2003-10-28,1610612742,20300003,2004,714,Michael Finley,G,28.983333,2.0,8.0,0.250,0.0,4.0,0.000,8.0,8.0,1.0,0.0,4.0,4.0,1.0,0.0,0.0,1.0,1.0,12.0,-14.0,2003-10-29,NaT,1,None,None,0.069005,0.276021,0.000000,0.138010,0.276021,0.276021,0.000000,0.138010,0.138010,0.034503,0.000000,0.0,0.034503,0.414031,-0.483036,0.034503
3,2003-10-28,1610612742,20300003,2004,762,Shawn Bradley,None,4.016667,2.0,2.0,1.000,0.0,0.0,0.000,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,4.0,2.0,2003-10-29,NaT,1,None,None,0.497925,0.497925,0.000000,0.000000,0.000000,0.000000,0.248963,0.000000,0.248963,0.000000,0.000000,0.0,0.000000,0.995851,0.497925,0.248963
4,2003-10-28,1610612742,20300003,2004,952,Antoine Walker,F,33.433333,7.0,13.0,0.538,5.0,6.0,0.833,0.0,0.0,0.0,2.0,5.0,7.0,1.0,0.0,0.0,2.0,3.0,19.0,-16.0,2003-10-29,NaT,1,None,None,0.209372,0.388833,0.149551,0.179462,0.000000,0.000000,0.059821,0.149551,0.209372,0.029910,0.000000,0.0,0.059821,0.568295,-0.478564,0.089731

,GAME_DATE_EST,TEAM_ID,GAME_ID,season_short,PLAYER_ID,PLAYER_NAME,START_POSITION,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS,PLUS_MINUS,next_game_played_date,last_game_played_date,game_played,comment_code,comment_reason,FGM_pm,FGA_pm,FG3M_pm,FG3A_pm,FTM_pm,FTA_pm,OREB_pm,DREB_pm,REB_pm,AST_pm,STL_pm,BLK_pm,TO_pm,PTS_pm,PLUS_MINUS_pm,PF_pm
766360,2022-12-22,1610612764,22200478,2023,204001,Kristaps Porzingis,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,0,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
766361,2022-12-22,1610612764,22200478,2023,1626153,Delon Wright,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,0,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
766362,2022-12-22,1610612764,22200478,2023,1628398,Kyle Kuzma,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,0,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
766363,2022-12-22,1610612764,22200478,2023,1628420,Monte Morris,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,0,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
766364,2022-12-22,1610612764,22200478,2023,1629060,Rui Hachimura,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,0,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
766365,2022-12-22,1610612764,22200478,2023,1629653,Devon Dotson,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,0,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
766366,2022-12-22,1610612764,22200478,2023,1629655,Daniel Gafford,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,0,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
766367,2022-12-22,1610612764,22200478,2023,1630166,Deni Avdija,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,0,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
766368,2022-12-22,1610612764,22200478,2023,1630176,Vernon Carey Jr.,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,0,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
766369,2022-12-22,1610612764,22200478,2023,1630225,Isaiah Todd,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,0,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
766370,2022-12-22,1610612764,22200478,2023,1630264,Anthony Gill,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,0,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
766371,2022-12-22,1610612764,22200478,2023,1630557,Corey Kispert,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,0,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
766372,2022-12-22,1610612764,22200478,2023,1630648,Jordan Schakel,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,0,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
766373,2022-12-22,1610612764,22200478,2023,1630692,Jordan Goodwin,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,0,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
766374,2022-12-22,1610612764,22200478,2023,1631098,Johnny Davis,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,0,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Timeseries data with game/season features

In [36]:
## 6. Merge game/season table onto game detail timeseries table
df_gamedays_fc_ts = pd.merge(df_gamedays_fc, df_game_detail_ts, on=['GAME_DATE_EST', 'GAME_ID', 'TEAM_ID', 'SEASON'], how='inner')

## Create two features: 1) played in first game of back to back, 2) played in second game of back to back
# if first game of back to back is 1 and game played is 1, then played in first game of back to back. if first game of back to back is 0, then played in first game of back to back is null
df_gamedays_fc_ts['played_in_first_game_of_back_to_back'] = np.where((df_gamedays_fc_ts['first_back_to_back'] == 1) & (df_gamedays_fc_ts['game_played'] == 1), 1, 0)
df_gamedays_fc_ts['played_in_first_game_of_back_to_back'] = np.where(df_gamedays_fc_ts['first_back_to_back'] == 0, np.nan, df_gamedays_fc_ts['played_in_first_game_of_back_to_back'])

# if second game of back to back is 1 and game played is 1, then played in second game of back to back
df_gamedays_fc_ts['played_in_second_game_of_back_to_back'] = np.where((df_gamedays_fc_ts['second_back_to_back'] == 1) & (df_gamedays_fc_ts['game_played'] == 1), 1, 0)
df_gamedays_fc_ts['played_in_second_game_of_back_to_back'] = np.where(df_gamedays_fc_ts['second_back_to_back'] == 0, np.nan, df_gamedays_fc_ts['played_in_second_game_of_back_to_back'])

# pandas display 100 columns
pd.set_option('display.max_columns', 100)
print(df_gamedays_fc_ts.shape)
display(pd.concat([df_gamedays_fc_ts.head(5), df_gamedays_fc_ts.tail(10)], axis=0, sort=False))

# # display first_back_to_back = 1 and season_short is 2022
# display(df_gamedays_fc_ts[(df_gamedays_fc_ts['second_back_to_back'] == 1) & (df_gamedays_fc_ts['SEASON'] == 2022)].head(14))

# lost a row, somebody didn't have a match for game and team ids

(766375, 127)

,GAME_DATE_EST,GAME_ID,TEAM_ID,TEAM_PTS,TEAM_FG_PCT,TEAM_FG3_PCT,TEAM_AST,TEAM_REB,OPP_TEAM_ID,OPP_TEAM_PTS,OPP_TEAM_FG_PCT,OPP_TEAM_FG3_PCT,OPP_TEAM_AST,OPP_TEAM_REB,HOME,WIN,last_game_date,days_since_last_game,next_game_date,days_until_next_game,first_back_to_back,second_back_to_back,season,season_short,min_games,max_games,number_of_teams,preseason_end,postseason_start,postseason_end,regular_season,preseason,postseason,game_number_of_season,total_regular_season_games,percentage_regular_season_games,TEAM_PTS_opp_per_game,TEAM_FG_PCT_opp_per_game,TEAM_FG3_PCT_opp_per_game,TEAM_AST_opp_per_game,TEAM_REB_opp_per_game,next_0_OPP_TEAM_ID,next_1_OPP_TEAM_ID,next_2_OPP_TEAM_ID,next_3_OPP_TEAM_ID,next_4_OPP_TEAM_ID,next_0_HOME,next_0_days_until_next_game,next_0_PTS_ALLOWED,next_0_FG_PCT_ALLOWED,...,next_4_FG_PCT_ALLOWED,next_4_FG3_PCT_ALLOWED,next_4_AST_ALLOWED,next_4_REB_ALLOWED,PLAYER_ID,PLAYER_NAME,START_POSITION,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS,PLUS_MINUS,next_game_played_date,last_game_played_date,game_played,comment_code,comment_reason,FGM_pm,FGA_pm,FG3M_pm,FG3A_pm,FTM_pm,FTA_pm,OREB_pm,DREB_pm,REB_pm,AST_pm,STL_pm,BLK_pm,TO_pm,PTS_pm,PLUS_MINUS_pm,PF_pm,played_in_first_game_of_back_to_back,played_in_second_game_of_back_to_back
0,2003-10-28,20300003,1610612742,93.0,0.376,0.280,17.0,46.0,1610612747,109.0,0.506,0.350,32.0,46.0,0,0.0,2003-10-22 00:00:00.000000,6,2003-10-29 00:00:00.000000,1,1,0,2003-2004,2004,82,82,29,2003-10-28 00:00:00.000000,2004-04-17 00:00:00.000000,2004-06-15 00:00:00.000000,1,0,0,1,82,0.012195,NaN,NaN,NaN,NaN,NaN,1610612747,1.610613e+09,1.610613e+09,1.610613e+09,1.610613e+09,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,281,Scott Williams,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,0,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN
1,2003-10-28,20300003,1610612742,93.0,0.376,0.280,17.0,46.0,1610612747,109.0,0.506,0.350,32.0,46.0,0,0.0,2003-10-22 00:00:00.000000,6,2003-10-29 00:00:00.000000,1,1,0,2003-2004,2004,82,82,29,2003-10-28 00:00:00.000000,2004-04-17 00:00:00.000000,2004-06-15 00:00:00.000000,1,0,0,1,82,0.012195,NaN,NaN,NaN,NaN,NaN,1610612747,1.610613e+09,1.610613e+09,1.610613e+09,1.610613e+09,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,696,Travis Best,None,16.200000,0.0,5.0,0.000,0.0,1.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,4.0,2.0,0.0,1.0,2.0,0.0,8.0,2003-10-29,NaT,1,None,None,0.000000,0.308642,0.000000,0.061728,0.000000,0.000000,0.000000,0.000000,0.000000,0.246914,0.123457,0.0,0.061728,0.000000,0.493827,0.123457,1.0,NaN
2,2003-10-28,20300003,1610612742,93.0,0.376,0.280,17.0,46.0,1610612747,109.0,0.506,0.350,32.0,46.0,0,0.0,2003-10-22 00:00:00.000000,6,2003-10-29 00:00:00.000000,1,1,0,2003-2004,2004,82,82,29,2003-10-28 00:00:00.000000,2004-04-17 00:00:00.000000,2004-06-15 00:00:00.000000,1,0,0,1,82,0.012195,NaN,NaN,NaN,NaN,NaN,1610612747,1.610613e+09,1.610613e+09,1.610613e+09,1.610613e+09,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,714,Michael Finley,G,28.983333,2.0,8.0,0.250,0.0,4.0,0.000,8.0,8.0,1.0,0.0,4.0,4.0,1.0,0.0,0.0,1.0,1.0,12.0,-14.0,2003-10-29,NaT,1,None,None,0.069005,0.276021,0.000000,0.138010,0.276021,0.276021,0.000000,0.138010,0.138010,0.034503,0.000000,0.0,0.034503,0.414031,-0.483036,0.034503,1.0,NaN
3,2003-10-28,20300003,1610612742,93.0,0.376,0.280,17.0,46.0,1610612747,109.0,0.506,0.350,32.0,46.0,0,0.0,2003-10-22 00:00:00.000000,6,2003-10-29 00:00:00.000000,1,1,0,2003-2004,2004,82,82,29,2003-10-28 00:00:00.000000,2004-04-17 00:00:00.000000,2004-06-15 00:00:00.000000,1,0,0,1,82,0.012195,NaN,NaN,NaN,NaN,NaN,1610612747,1.610613e+09,1.610613e+09,1.610613e+09,1.610613e+09,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,762,Shawn Bradley,None,4.016667,2.0,2.0,1.000,0.0,0.0,0.000,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,4.0,2.0,2003-10-29,NaT,1,None,None,0.497925,0.497925,0.000000,0.000000,0.000000,0.000000,0.248963,0.000000,0.248963,0.000000,0.000000,0.0,0.000000,0.995851,0.497925,0.248963,1.0,NaN
4,2003-10-28,20300003,1610612742,93.0,0.376,0.280,17.0,46.0,1610612747,109.0,0.506,0.350,32.0,46.0,0,0.0,2003-10-22 00:00:00.000000,6,2003-10-29 00:00:00.000000,1,1,0,2003-2004,2004,82,82,29,2003-10-28 00:00:00.000000,2004-04-17 00:00:00.000000,2004-06-15 00:00:00.000000,1,0,0,1,82,0.012195,NaN,NaN,NaN,NaN,NaN,1610612747,1.610613e+09,1.610613e+09,1.610613e+09,1.610613e+09,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,952,Antoine Walker,F,33.433333,7.0,13.0,0.538,5.0,6.0,0.833,0.0,0.0,0.0,2.0,5.0,7.0,1.0,0.0,0.0,2.0,3.0,19.0,-16.0,2003-10-29,NaT,1,None,None,0.209372,0.388833,0.149551,0.179462,0.000000,0.000000,0.059821,0.149551,0.209372,0.029910,0.000000,0.0,0.059821,0.568295,-0.478564,0.089731,1.0,NaN
766365,2022-12-22,22200478,1610612764,112.0,0.561,0.333,20.0,37.0,1610612762,120.0,0.488,0.457,16.0,40.0,0,0.0,2022-12-20 00:00:00.000000,2,None,0,0,0,2022-2023,2023,82,82,30,2022-10-18 00:00:00.000000,2023-04-16 00:00:00.000000,2023-06-16 00:00:00.000000,1,0,0,33,82,0.402439,113.5625,0.467406,0.371375,24.15625,43.84375,1610612762,NaN,NaN,NaN,NaN,1.0,0.0,116.029412,0.481088,...,NaN,NaN,NaN,NaN,1629653,Devon Dotson,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,0,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
766366,2022-12-22,22200478,1610612764,112.0,0.561,0.333,20.0,37.0,1610612762,120.0,0.488,0.457,16.0,40.0,0,0.0,2022-12-20 00:00:00.000000,2,None,0,0,0,2022-2023,2023,82,82,30,2022-10-18 00:00:00.000000,2023-04-16 00:00:00.000000,2023-06-16 00:00:00.000000,1,0,0,33,82,0.402439,113.5625,0.467406,0.371375,24.15625,43.84375,1610612762,NaN,NaN,NaN,NaN,1.0,0.0,116.029412,0.481088,...,NaN,NaN,NaN,NaN,1629655,Daniel Gafford,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,0,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
766367,2022-12-22,22200478,1610612764,112.0,0.561,0.333,20.0,37.0,1610612762,120.0,0.488,0.457,16.0,40.0,0,0.0,2022-12-20 00:00:00.000000,2,None,0,0,0,2022-2023,2023,82,82,30,2022-10-18 00:00:00.000000,2023-04-16 00:00:00.000000,2023-06-16 00:00:00.000000,1,0,0,33,82,0.402439,113.5625,0.467406,0.371375,24.15625,43.84375,1610612762,NaN,NaN,NaN,NaN,1.0,0.0,116.029412,0.481088,...,NaN,NaN,NaN,NaN,1630166,Deni Avdija,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,0,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
766368,2022-12-22,22200478,1610612764,112.0,0.561,0.333,20.0,37.0,1610612762,120.0,0.488,0.457,16.0,40.0,0,0.0,2022-12-20 00:00:00.000000,2,None,0,0,0,2022-2023,2023,82,82,30,2022-10-18 00:00:00.000000,2023-04-16 00:00:00.000000,2023-06-16 00:00:00.000000,1,0,0,33,82,0.402439,113.5625,0.467406,0.371375,24.15625,43.84375,1610612762,NaN,NaN,NaN,NaN,1.0,0.0,116.029412,0.481088,...,NaN,NaN,NaN,NaN,1630176,Vernon Carey Jr.,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,0,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
766369,2022-12-22,22200478,1610612764,112.0,0.561,0.333,20.0,37.0,1610612762,120.0,0.488,0.457,16.0,40.0,0,0.0,2022-12-20 00:00:00.000000,2,None,0,0,0,2022-2023,2023,82,82,30,2022-10-18 00:00:00.000000,2023-04-16 00:00:00.000000,2023-06-16 00:00:00.000000,1,0,0,33,82,0.402439,113.5625,0.467406,0.371375,24.15625,43.84375,1610612762,NaN,NaN,NaN,NaN,1.0,0.0,116.029412,0.481088,...,NaN,NaN,NaN,NaN,1630225,Isaiah Todd,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,0,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
766370,2022-12-22,22200478,1610612764,112.0,0.561,0.333,20.0,37.0,1610612762,120.0,0.488,0.457,16.0,40.0,0,0.0,2022-12-20 00:00:00.000000,2,None,0,0,0,2022-2023,2023,82,82,30,2022-10-18 00:00:00.000000,2023-04-16 00:00:00.000000,2023-06-16 00:00:00.000000,1,0,0,33,82,0.402439,113.5625,0.467406,0.371375,24.15625,43.84375,1610612762,NaN,NaN,NaN,NaN,1.0,0.0,116.029412,0.481088,...,NaN,NaN,NaN,NaN,1630264,Anthony Gill,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,0,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
766371,2022-12-22,22200478,1610612764,112.0,0.561,0.333,20.0,37.0,1610612762,120.0,0.488,0.457,16.0,40.0,0,0.0,2022-12-20 00:00:00.000000,2,None,0,0,0,2022-2023,2023,82,82,30,2022-10-18 00:00:00.000000,2023-04-16 00:00:00.000000,2023-06-16 00:00:00.000000,1,0,0,33,82,0.402439,113.5625,0.467406,0.371375,24.15625,43.84375,1610612762,NaN,NaN,NaN,NaN,1.0,0.0,116.029412,0.481088,...,NaN,NaN,NaN,NaN,1630557,Corey Kispert,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,0,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
766372,2022-12-22,22200478,1610612764,112.0,0.561,0.333,20.0,37.0,1610612762,120.0,0.488,0.457,16.0,40.0,0,0.0,2022-12-20 00:00:00.000000,2,None,0,0,0,2022-2023,2023,82,82,30,2022-10-18 00:00:00.000000,2023-04-16 00:00:00.000000,2023-06-16 00:00:00.000000,1,0,0,33,82,0.402439,113.5625,0.467406,0.371375,24.15625,43.84375,1610612762,NaN,NaN,NaN,NaN,1.0,0.0,116.029412,0.481088,...,NaN,NaN,NaN,NaN,1630648,Jordan Schakel,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,0,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
766373,2022-12-22,22200478,1610612764,112.0,0.561,0.333,20.0,37.0,1610612762,120.0,0.488,0.457,16.0,40.0,0,0.0,2022-12-20 00:00:00.000000,2,None,0,0,0,2022-2023,2023,82,82,30,2022-10-18 00:00:00.000000,2023-04-16 00:00:00.000000,2023-06-16 00:00:00.000000,1,0,0,33,82,0.402439,113.5625,0.467406,0.371375,24.15625,43.84375,1610612762,NaN,NaN,NaN,NaN,1.0,0.0,116.029412,0.481088,...,NaN,NaN,NaN,NaN,1630692,Jordan Goodwin,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,0,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
766374,2022-12-22,22200478,1610612764,112.0,0.561,0.333,20.0,37.0,1610612762,120.0,0.488,0.457,16.0,40.0,0,0.0,2022-12-20 00:00:00.000000,2,None,0,0,0,2022-2023,2023,82,82,30,2022-10-18 00:00:00.000000,2023-04-16 00:00:00.000000,2023-06-16 00:00:00.000000,1,0,0,33,82,0.402439,113.5625,0.467406,0.371375,24.15625,43.84375,1610612762,NaN,NaN,NaN,NaN,1.0,0.0,116.029412,0.481088,...,NaN,NaN,NaN,NaN,1631098,Johnny Davis,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,0,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [37]:
pd.set_option('display.max_rows', 120)
display(df_gamedays_fc_ts.dtypes)
pd.set_option('display.max_rows', 30)

GAME_DATE_EST                            datetime64[ns]
GAME_ID                                           int64
TEAM_ID                                           int64
TEAM_PTS                                        float64
TEAM_FG_PCT                                     float64
                                              ...
PTS_pm                                          float64
PLUS_MINUS_pm                                   float64
PF_pm                                           float64
played_in_first_game_of_back_to_back            float64
played_in_second_game_of_back_to_back           float64
Length: 127, dtype: object

### Player-Season-level stats

In [38]:
df_gamedays_fc_ts.columns
L = ['MIN', 'game_played', 'FGM_pm',
       'FGA_pm', 'FG3M_pm', 'FG3A_pm', 'FTM_pm', 'FTA_pm',
       'REB_pm', 'AST_pm', 'STL_pm', 'BLK_pm', 'TO_pm', 'PTS_pm',
       'PLUS_MINUS_pm', 'PF_pm', 'played_in_first_game_of_back_to_back', 'played_in_second_game_of_back_to_back'
]
[f"'{col}': ['mean']" for col in L]

["'MIN': ['mean']",
 "'game_played': ['mean']",
 "'FGM_pm': ['mean']",
 "'FGA_pm': ['mean']",
 "'FG3M_pm': ['mean']",
 "'FG3A_pm': ['mean']",
 "'FTM_pm': ['mean']",
 "'FTA_pm': ['mean']",
 "'REB_pm': ['mean']",
 "'AST_pm': ['mean']",
 "'STL_pm': ['mean']",
 "'BLK_pm': ['mean']",
 "'TO_pm': ['mean']",
 "'PTS_pm': ['mean']",
 "'PLUS_MINUS_pm': ['mean']",
 "'PF_pm': ['mean']",
 "'played_in_first_game_of_back_to_back': ['mean']",
 "'played_in_second_game_of_back_to_back': ['mean']"]

In [39]:
## TODO: Create a table of player-season level stats 
# get player-season level stats
df_player_season_stats = df_gamedays_fc_ts.groupby(['PLAYER_ID', 'SEASON', ], as_index=False).agg({
    'MIN': ['mean'],
    'game_played': ['mean'],
    'FGM_pm': ['mean'],
    'FGA_pm': ['mean'],
    'FG3M_pm': ['mean'],
    'FG3A_pm': ['mean'],
    'FTM_pm': ['mean'],
    'FTA_pm': ['mean'],
    'REB_pm': ['mean'],
    'AST_pm': ['mean'],
    'STL_pm': ['mean'],
    'BLK_pm': ['mean'],
    'TO_pm': ['mean'],
    'PTS_pm': ['mean'],
    'PLUS_MINUS_pm': ['mean'],
    'PF_pm': ['mean'],
    'played_in_first_game_of_back_to_back': ['mean'],
    'played_in_second_game_of_back_to_back': ['mean'],
})
df_player_season_stats.columns = ['_'.join(col).strip() for col in df_player_season_stats.columns.values]
df_player_season_stats.columns = [col.replace('mean', 'SEASON') for col in df_player_season_stats.columns]
df_player_season_stats.rename(columns={'PLAYER_ID_': 'PLAYER_ID', 'season_short_': 'SEASON'}, inplace=True)
df_player_season_stats

,PLAYER_ID,season_short,MIN_season,game_played_season,FGM_pm_season,FGA_pm_season,FG3M_pm_season,FG3A_pm_season,FTM_pm_season,FTA_pm_season,REB_pm_season,AST_pm_season,STL_pm_season,BLK_pm_season,TO_pm_season,PTS_pm_season,PLUS_MINUS_pm_season,PF_pm_season,played_in_first_game_of_back_to_back_season,played_in_second_game_of_back_to_back_season
0,15,2004,9.915700,0.573171,0.095538,0.267195,0.057646,0.176355,0.018107,0.022048,0.115158,0.036025,0.018918,0.005804,0.039066,0.266829,-0.114803,0.065765,0.736842,0.684211
1,15,2005,10.188477,0.804878,0.108947,0.296782,0.053501,0.155933,0.042562,0.054097,0.090200,0.053748,0.026232,0.000801,0.059080,0.313956,-0.148268,0.077139,0.863636,0.681818
2,15,2006,4.197484,0.329268,0.070418,0.194852,0.023390,0.093096,0.005952,0.014739,0.087533,0.063156,0.023667,0.011905,0.054072,0.170179,0.232714,0.127523,0.318182,0.454545
3,15,2007,1.654545,0.134146,0.100816,0.306694,0.084048,0.203262,0.052701,0.052701,0.169743,0.032916,0.000000,0.004258,0.068214,0.338381,-0.018101,0.063966,0.100000,0.100000
4,15,2008,1.288444,0.182927,0.124084,0.289660,0.112720,0.212884,0.066365,0.066365,0.103772,0.075334,0.000000,0.012121,0.077517,0.427251,-0.582166,0.121266,0.176471,0.176471
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9833,1631298,2023,1.961111,0.233333,0.000000,0.286406,0.000000,0.141677,0.000000,0.000000,0.195637,0.000000,0.051635,0.029204,0.000000,0.000000,-1.788386,0.170881,0.000000,0.500000
9834,1631306,2023,1.866667,0.032258,0.000000,0.535714,0.000000,0.535714,0.000000,0.000000,0.535714,0.535714,0.000000,0.000000,0.000000,0.000000,1.607143,0.000000,0.000000,0.000000
9835,1631309,2023,0.343939,0.032258,0.264317,0.264317,0.264317,0.264317,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.792952,-0.528634,0.000000,0.000000,0.250000
9836,1631320,2023,0.881481,0.066667,0.309278,0.388434,0.000000,0.000000,0.000000,0.158311,0.158311,0.079156,0.000000,0.000000,0.618557,0.618557,-0.712401,0.158311,0.000000,0.000000
9837,1631323,2023,7.030769,0.485714,0.104497,0.345702,0.063738,0.262305,0.036121,0.055921,0.139691,0.028435,0.019896,0.018993,0.040351,0.308853,-0.160200,0.067436,0.444444,0.555556

In [40]:
df_player_season_stats.columns

Index(['PLAYER_ID', 'season_short', 'MIN_season', 'game_played_season',
       'FGM_pm_season', 'FGA_pm_season', 'FG3M_pm_season', 'FG3A_pm_season',
       'FTM_pm_season', 'FTA_pm_season', 'REB_pm_season', 'AST_pm_season',
       'STL_pm_season', 'BLK_pm_season', 'TO_pm_season', 'PTS_pm_season',
       'PLUS_MINUS_pm_season', 'PF_pm_season',
       'played_in_first_game_of_back_to_back_season',
       'played_in_second_game_of_back_to_back_season'],
      dtype='object')

In [41]:
## get two lags for player season stats and get average for the rest of the seasons per player
df_player_season_stats_ts = df_player_season_stats.copy().sort_values(by=['PLAYER_ID', 'SEASON'])

group_cols = ['PLAYER_ID']
player_season_stats_cols = ['MIN_season', 'game_played_season',
       'FGM_pm_season', 'FGA_pm_season', 'FG3M_pm_season', 'FG3A_pm_season',
       'FTM_pm_season', 'FTA_pm_season', 'REB_pm_season', 'AST_pm_season',
       'STL_pm_season', 'BLK_pm_season', 'TO_pm_season', 'PTS_pm_season',
       'PLUS_MINUS_pm_season', 'PF_pm_season', 'played_in_first_game_of_back_to_back_season',
       'played_in_second_game_of_back_to_back_season',
       ]
df_player_season_stats_ts, created_player_season_stats_cols = get_all_lags(
    df=df_player_season_stats, cols=player_season_stats_cols, group_cols=group_cols, n_lags=2)

windows = np.array([20])
shifts = np.array([3])
min_periods = np.array([1])
df_player_season_stats_ts, created_player_season_stats_cols = get_all_average_windows(
       df=df_player_season_stats_ts, cols=player_season_stats_cols, group_cols=group_cols,
       prefix='avg_', windows=windows, shifts=shifts, min_periods=min_periods
       )

df_player_season_stats_ts.drop(columns=player_season_stats_cols, inplace=True)
df_player_season_stats_ts

,PLAYER_ID,season_short,lag_1_MIN_season,lag_2_MIN_season,lag_1_game_played_season,lag_2_game_played_season,lag_1_FGM_pm_season,lag_2_FGM_pm_season,lag_1_FGA_pm_season,lag_2_FGA_pm_season,lag_1_FG3M_pm_season,lag_2_FG3M_pm_season,lag_1_FG3A_pm_season,lag_2_FG3A_pm_season,lag_1_FTM_pm_season,lag_2_FTM_pm_season,lag_1_FTA_pm_season,lag_2_FTA_pm_season,lag_1_REB_pm_season,lag_2_REB_pm_season,lag_1_AST_pm_season,lag_2_AST_pm_season,lag_1_STL_pm_season,lag_2_STL_pm_season,lag_1_BLK_pm_season,lag_2_BLK_pm_season,lag_1_TO_pm_season,lag_2_TO_pm_season,lag_1_PTS_pm_season,lag_2_PTS_pm_season,lag_1_PLUS_MINUS_pm_season,lag_2_PLUS_MINUS_pm_season,lag_1_PF_pm_season,lag_2_PF_pm_season,lag_1_played_in_first_game_of_back_to_back_season,lag_2_played_in_first_game_of_back_to_back_season,lag_1_played_in_second_game_of_back_to_back_season,lag_2_played_in_second_game_of_back_to_back_season,avg_3_22_MIN_season,avg_3_22_game_played_season,avg_3_22_FGM_pm_season,avg_3_22_FGA_pm_season,avg_3_22_FG3M_pm_season,avg_3_22_FG3A_pm_season,avg_3_22_FTM_pm_season,avg_3_22_FTA_pm_season,avg_3_22_REB_pm_season,avg_3_22_AST_pm_season,avg_3_22_STL_pm_season,avg_3_22_BLK_pm_season,avg_3_22_TO_pm_season,avg_3_22_PTS_pm_season,avg_3_22_PLUS_MINUS_pm_season,avg_3_22_PF_pm_season,avg_3_22_played_in_first_game_of_back_to_back_season,avg_3_22_played_in_second_game_of_back_to_back_season
0,15,2004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,15,2005,9.915700,NaN,0.573171,NaN,0.095538,NaN,0.267195,NaN,0.057646,NaN,0.176355,NaN,0.018107,NaN,0.022048,NaN,0.115158,NaN,0.036025,NaN,0.018918,NaN,0.005804,NaN,0.039066,NaN,0.266829,NaN,-0.114803,NaN,0.065765,NaN,0.736842,NaN,0.684211,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,15,2006,10.188477,9.915700,0.804878,0.573171,0.108947,0.095538,0.296782,0.267195,0.053501,0.057646,0.155933,0.176355,0.042562,0.018107,0.054097,0.022048,0.090200,0.115158,0.053748,0.036025,0.026232,0.018918,0.000801,0.005804,0.059080,0.039066,0.313956,0.266829,-0.148268,-0.114803,0.077139,0.065765,0.863636,0.736842,0.681818,0.684211,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,15,2007,4.197484,10.188477,0.329268,0.804878,0.070418,0.108947,0.194852,0.296782,0.023390,0.053501,0.093096,0.155933,0.005952,0.042562,0.014739,0.054097,0.087533,0.090200,0.063156,0.053748,0.023667,0.026232,0.011905,0.000801,0.054072,0.059080,0.170179,0.313956,0.232714,-0.148268,0.127523,0.077139,0.318182,0.863636,0.454545,0.681818,9.915700,0.573171,0.095538,0.267195,0.057646,0.176355,0.018107,0.022048,0.115158,0.036025,0.018918,0.005804,0.039066,0.266829,-0.114803,0.065765,0.736842,0.684211
4,15,2008,1.654545,4.197484,0.134146,0.329268,0.100816,0.070418,0.306694,0.194852,0.084048,0.023390,0.203262,0.093096,0.052701,0.005952,0.052701,0.014739,0.169743,0.087533,0.032916,0.063156,0.000000,0.023667,0.004258,0.011905,0.068214,0.054072,0.338381,0.170179,-0.018101,0.232714,0.063966,0.127523,0.100000,0.318182,0.100000,0.454545,10.052089,0.689024,0.102242,0.281988,0.055574,0.166144,0.030335,0.038072,0.102679,0.044887,0.022575,0.003303,0.049073,0.290393,-0.131535,0.071452,0.800239,0.683014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9833,1631298,2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9834,1631306,2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9835,1631309,2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9836,1631320,2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9837,1631323,2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Timeseries final data

In [42]:
## Separate features into five categories: do not include, labels, this game, as of last game, and window of games
index_cols = ['GAME_DATE_EST', 'GAME_ID', 'TEAM_ID', 'PLAYER_ID', 'PLAYER_NAME', 'SEASON']
do_not_include = ['OPP_TEAM_ID', 'last_game_date', 'next_game_date', 
        'min_games', 'max_games', 'number_of_teams', 'regular_season', 'preseason', 'postseason',
        'total_regular_season_games', 'TEAM_PTS', 'OPP_TEAM_PTS', 'preseason_end',
        'postseason_start', 'postseason_end', 'game_number_of_season', 'OREB_pm', 'DREB_pm', 'next_game_date', 
        'OREB', 'DREB', 'TEAM_FG_PCT', 'TEAM_FG3_PCT', 'TEAM_AST', 'TEAM_REB',
        'OPP_TEAM_FG_PCT', 'OPP_TEAM_FG3_PCT', 'OPP_TEAM_AST', 'OPP_TEAM_REB',
        'FG_PCT', 'FG3_PCT', 'FT_PCT', 'WIN', 'next_0_OPP_TEAM_ID', 'next_1_OPP_TEAM_ID',
        'next_2_OPP_TEAM_ID', 'next_3_OPP_TEAM_ID', 'next_4_OPP_TEAM_ID', 'TEAM_PTS_opp_per_game',
        'TEAM_FG_PCT_opp_per_game', 'TEAM_FG3_PCT_opp_per_game', 'TEAM_AST_opp_per_game', 'TEAM_REB_opp_per_game',
        'days_until_next_game', 'first_back_to_back', 'second_back_to_back', 'HOME', 
        ]
labels = ['MIN', 'FGM', 'FGA', 'FG3M', 'FG3A', 'FTM', 'FTA', 'REB', 'AST', 'STL', 'BLK', 'TO', 'PTS', 'PLUS_MINUS', 'PF']
num_cols_this_game = ['days_since_last_game', 'percentage_regular_season_games',
        'next_0_HOME', 'next_0_days_until_next_game', 'next_0_PTS_ALLOWED', 'next_0_FG_PCT_ALLOWED', 'next_0_FG3_PCT_ALLOWED', 'next_0_AST_ALLOWED', 'next_0_REB_ALLOWED',
        'next_1_HOME', 'next_1_days_until_next_game', 'next_1_PTS_ALLOWED', 'next_1_FG_PCT_ALLOWED', 'next_1_FG3_PCT_ALLOWED', 'next_1_AST_ALLOWED', 'next_1_REB_ALLOWED',
        'next_2_HOME', 'next_2_days_until_next_game', 'next_2_PTS_ALLOWED', 'next_2_FG_PCT_ALLOWED', 'next_2_FG3_PCT_ALLOWED', 'next_2_AST_ALLOWED', 'next_2_REB_ALLOWED',
        'next_3_HOME', 'next_3_days_until_next_game', 'next_3_PTS_ALLOWED', 'next_3_FG_PCT_ALLOWED', 'next_3_FG3_PCT_ALLOWED', 'next_3_AST_ALLOWED', 'next_3_REB_ALLOWED',
        'next_4_HOME', 'next_4_days_until_next_game', 'next_4_PTS_ALLOWED', 'next_4_FG_PCT_ALLOWED', 'next_4_FG3_PCT_ALLOWED', 'next_4_AST_ALLOWED', 'next_4_REB_ALLOWED'
]
cat_cols_this_game = []
this_game_cols = num_cols_this_game + cat_cols_this_game

num_cols_last_game = []
cat_cols_last_game = ['START_POSITION', 'comment_code', 'comment_reason']
last_game_cols = num_cols_last_game + cat_cols_last_game

num_cols_window = ['MIN', 'FGM_pm', 'FGA_pm', 'FG3M_pm', 'FG3A_pm', 'FTM_pm', 'FTA_pm', 'REB_pm', 'AST_pm', 'STL_pm',
        'BLK_pm', 'TO_pm', 'PTS_pm', 'PLUS_MINUS_pm', 'PF_pm', 
        ]
cat_cols_window = ['game_played']
standard_window_cols = num_cols_window + cat_cols_window
back_to_back_cols_window = ['played_in_first_game_of_back_to_back', 'played_in_second_game_of_back_to_back',]
all_window_cols = standard_window_cols + back_to_back_cols_window

# print cols that are in the lists and not the df, and vice versa
print('add col to lists:')
print([col for col in df_gamedays_fc_ts.columns if col not in index_cols + do_not_include + labels + this_game_cols + last_game_cols + all_window_cols])
print('remove col from lists:')
print([col for col in index_cols + do_not_include + labels + this_game_cols + last_game_cols + all_window_cols if col not in df_gamedays_fc_ts.columns])

# explore with ExploreData.py
explore_windows = ExploreData(df_gamedays_fc_ts)
print('num_vars:', explore_windows.var_dict['num_vars'])
print('cat_vars:', explore_windows.var_dict['cat_vars'])

add col to lists:
['next_game_played_date', 'last_game_played_date']
remove col from lists:
[]
num_vars: ['GAME_DATE_EST', 'GAME_ID', 'TEAM_ID', 'TEAM_PTS', 'TEAM_FG_PCT', 'TEAM_FG3_PCT', 'TEAM_AST', 'TEAM_REB', 'OPP_TEAM_ID', 'OPP_TEAM_PTS', 'OPP_TEAM_FG_PCT', 'OPP_TEAM_FG3_PCT', 'OPP_TEAM_AST', 'OPP_TEAM_REB', 'days_since_last_game', 'days_until_next_game', 'season_short', 'game_number_of_season', 'percentage_regular_season_games', 'TEAM_PTS_opp_per_game', 'TEAM_FG_PCT_opp_per_game', 'TEAM_FG3_PCT_opp_per_game', 'TEAM_AST_opp_per_game', 'TEAM_REB_opp_per_game', 'next_0_OPP_TEAM_ID', 'next_1_OPP_TEAM_ID', 'next_2_OPP_TEAM_ID', 'next_3_OPP_TEAM_ID', 'next_4_OPP_TEAM_ID', 'next_0_days_until_next_game', 'next_0_PTS_ALLOWED', 'next_0_FG_PCT_ALLOWED', 'next_0_FG3_PCT_ALLOWED', 'next_0_AST_ALLOWED', 'next_0_REB_ALLOWED', 'next_1_days_until_next_game', 'next_1_PTS_ALLOWED', 'next_1_FG_PCT_ALLOWED', 'next_1_FG3_PCT_ALLOWED', 'next_1_AST_ALLOWED', 'next_1_REB_ALLOWED', 'next_2_days_until_next_game', 'next_2_PTS_ALLOWED', 'next_2_FG_PCT_ALLOWED', 'next_2_FG3_PCT_ALLOWED', 'next_2_AST_ALLOWED', 'next_2_REB_ALLOWED', 'next_3_days_until_next_game', 'next_3_PTS_ALLOWED', 'next_3_FG_PCT_ALLOWED', 'next_3_FG3_PCT_ALLOWED', 'next_3_AST_ALLOWED', 'next_3_REB_ALLOWED', 'next_4_days_until_next_game', 'next_4_PTS_ALLOWED', 'next_4_FG_PCT_ALLOWED', 'next_4_FG3_PCT_ALLOWED', 'next_4_AST_ALLOWED', 'next_4_REB_ALLOWED', 'PLAYER_ID', 'MIN', 'FGM', 'FGA', 'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST', 'STL', 'BLK', 'TO', 'PTS', 'PLUS_MINUS', 'next_game_played_date', 'last_game_played_date', 'FGM_pm', 'FGA_pm', 'FG3M_pm', 'FG3A_pm', 'FTM_pm', 'FTA_pm', 'OREB_pm', 'DREB_pm', 'REB_pm', 'AST_pm', 'STL_pm', 'BLK_pm', 'TO_pm', 'PTS_pm', 'PLUS_MINUS_pm', 'PF_pm']
cat_vars: ['HOME', 'WIN', 'last_game_date', 'next_game_date', 'first_back_to_back', 'second_back_to_back', 'season', 'min_games', 'max_games', 'number_of_teams', 'preseason_end', 'postseason_start', 'postseason_end', 'regular_season', 'preseason', 'postseason', 'total_regular_season_games', 'next_0_HOME', 'next_1_HOME', 'next_2_HOME', 'next_3_HOME', 'next_4_HOME', 'PLAYER_NAME', 'START_POSITION', 'PF', 'game_played', 'comment_code', 'comment_reason', 'played_in_first_game_of_back_to_back', 'played_in_second_game_of_back_to_back']

In [43]:
## TODO:
# - get_all_lags(nlags=-5) with labels
# - drop columns in do_not_include and all columns that are no longer needed after creating lags/windows, remember to include index_cols
# - finish prepping data for export

In [44]:
# 7. Get rolling averages and lag features
group_cols = ['PLAYER_ID', 'SEASON']

## get lags for last game columns
df_gamedays_ts, created_game_lag_cols = get_all_lags(df=df_gamedays_fc_ts, cols=last_game_cols, group_cols=group_cols, n_lags=1)

## get window features -- 1 lag and the rest are average windows
df_gamedays_ts, created_window_lag_cols = get_all_lags(df=df_gamedays_ts, cols=standard_window_cols, group_cols=group_cols, n_lags=1)

## get_all_lags(nlags=-5) with labels
df_gamedays_ts, created_label_lag_cols = get_all_lags(df=df_gamedays_ts, cols=labels, group_cols=group_cols, n_lags=-5)

windows = np.array([2, 6, 10, 16, 50])
shifts = np.array([2, 4, 10, 20, 36])
min_periods = np.array([1, 2, 3, 4, 5])
df_gamedays_ts, created_window_avg_cols = get_all_average_windows(
    df=df_gamedays_ts, cols=standard_window_cols, group_cols=group_cols, prefix='avg_',
    windows=windows, shifts=shifts, min_periods=min_periods
    )
windows = np.array([20, 70])
shifts = np.array([1, 21])
min_periods = np.array([1, 5])
df_gamedays_ts, created_back_to_back_window_cols = get_all_average_windows(
    df=df_gamedays_ts, cols=back_to_back_cols_window, group_cols=group_cols, prefix='avg_',
    windows=windows, shifts=shifts, min_periods=min_periods
    )

print(df_gamedays_ts.shape)
display(pd.concat([df_gamedays_ts.head(5), df_gamedays_ts.tail(5)], axis=0, sort=False))

(766375, 305)

,GAME_DATE_EST,GAME_ID,TEAM_ID,TEAM_PTS,TEAM_FG_PCT,TEAM_FG3_PCT,TEAM_AST,TEAM_REB,OPP_TEAM_ID,OPP_TEAM_PTS,OPP_TEAM_FG_PCT,OPP_TEAM_FG3_PCT,OPP_TEAM_AST,OPP_TEAM_REB,HOME,WIN,last_game_date,days_since_last_game,next_game_date,days_until_next_game,first_back_to_back,second_back_to_back,season,season_short,min_games,max_games,number_of_teams,preseason_end,postseason_start,postseason_end,regular_season,preseason,postseason,game_number_of_season,total_regular_season_games,percentage_regular_season_games,TEAM_PTS_opp_per_game,TEAM_FG_PCT_opp_per_game,TEAM_FG3_PCT_opp_per_game,TEAM_AST_opp_per_game,TEAM_REB_opp_per_game,next_0_OPP_TEAM_ID,next_1_OPP_TEAM_ID,next_2_OPP_TEAM_ID,next_3_OPP_TEAM_ID,next_4_OPP_TEAM_ID,next_0_HOME,next_0_days_until_next_game,next_0_PTS_ALLOWED,next_0_FG_PCT_ALLOWED,...,avg_36_85_FTA_pm,avg_2_3_REB_pm,avg_4_9_REB_pm,avg_10_19_REB_pm,avg_20_35_REB_pm,avg_36_85_REB_pm,avg_2_3_AST_pm,avg_4_9_AST_pm,avg_10_19_AST_pm,avg_20_35_AST_pm,avg_36_85_AST_pm,avg_2_3_STL_pm,avg_4_9_STL_pm,avg_10_19_STL_pm,avg_20_35_STL_pm,avg_36_85_STL_pm,avg_2_3_BLK_pm,avg_4_9_BLK_pm,avg_10_19_BLK_pm,avg_20_35_BLK_pm,avg_36_85_BLK_pm,avg_2_3_TO_pm,avg_4_9_TO_pm,avg_10_19_TO_pm,avg_20_35_TO_pm,avg_36_85_TO_pm,avg_2_3_PTS_pm,avg_4_9_PTS_pm,avg_10_19_PTS_pm,avg_20_35_PTS_pm,avg_36_85_PTS_pm,avg_2_3_PLUS_MINUS_pm,avg_4_9_PLUS_MINUS_pm,avg_10_19_PLUS_MINUS_pm,avg_20_35_PLUS_MINUS_pm,avg_36_85_PLUS_MINUS_pm,avg_2_3_PF_pm,avg_4_9_PF_pm,avg_10_19_PF_pm,avg_20_35_PF_pm,avg_36_85_PF_pm,avg_2_3_game_played,avg_4_9_game_played,avg_10_19_game_played,avg_20_35_game_played,avg_36_85_game_played,avg_1_20_played_in_first_game_of_back_to_back,avg_21_90_played_in_first_game_of_back_to_back,avg_1_20_played_in_second_game_of_back_to_back,avg_21_90_played_in_second_game_of_back_to_back
0,2003-10-28,20300003,1610612742,93.0,0.376,0.280,17.0,46.0,1610612747,109.0,0.506,0.350,32.0,46.0,0,0.0,2003-10-22 00:00:00.000000,6,2003-10-29 00:00:00.000000,1,1,0,2003-2004,2004,82,82,29,2003-10-28 00:00:00.000000,2004-04-17 00:00:00.000000,2004-06-15 00:00:00.000000,1,0,0,1,82,0.012195,NaN,NaN,NaN,NaN,NaN,1610612747,1.610613e+09,1.610613e+09,1.610613e+09,1.610613e+09,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2003-10-28,20300003,1610612742,93.0,0.376,0.280,17.0,46.0,1610612747,109.0,0.506,0.350,32.0,46.0,0,0.0,2003-10-22 00:00:00.000000,6,2003-10-29 00:00:00.000000,1,1,0,2003-2004,2004,82,82,29,2003-10-28 00:00:00.000000,2004-04-17 00:00:00.000000,2004-06-15 00:00:00.000000,1,0,0,1,82,0.012195,NaN,NaN,NaN,NaN,NaN,1610612747,1.610613e+09,1.610613e+09,1.610613e+09,1.610613e+09,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2003-10-28,20300003,1610612742,93.0,0.376,0.280,17.0,46.0,1610612747,109.0,0.506,0.350,32.0,46.0,0,0.0,2003-10-22 00:00:00.000000,6,2003-10-29 00:00:00.000000,1,1,0,2003-2004,2004,82,82,29,2003-10-28 00:00:00.000000,2004-04-17 00:00:00.000000,2004-06-15 00:00:00.000000,1,0,0,1,82,0.012195,NaN,NaN,NaN,NaN,NaN,1610612747,1.610613e+09,1.610613e+09,1.610613e+09,1.610613e+09,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2003-10-28,20300003,1610612742,93.0,0.376,0.280,17.0,46.0,1610612747,109.0,0.506,0.350,32.0,46.0,0,0.0,2003-10-22 00:00:00.000000,6,2003-10-29 00:00:00.000000,1,1,0,2003-2004,2004,82,82,29,2003-10-28 00:00:00.000000,2004-04-17 00:00:00.000000,2004-06-15 00:00:00.000000,1,0,0,1,82,0.012195,NaN,NaN,NaN,NaN,NaN,1610612747,1.610613e+09,1.610613e+09,1.610613e+09,1.610613e+09,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2003-10-28,20300003,1610612742,93.0,0.376,0.280,17.0,46.0,1610612747,109.0,0.506,0.350,32.0,46.0,0,0.0,2003-10-22 00:00:00.000000,6,2003-10-29 00:00:00.000000,1,1,0,2003-2004,2004,82,82,29,2003-10-28 00:00:00.000000,2004-04-17 00:00:00.000000,2004-06-15 00:00:00.000000,1,0,0,1,82,0.012195,NaN,NaN,NaN,NaN,NaN,1610612747,1.610613e+09,1.610613e+09,1.610613e+09,1.610613e+09,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
766370,2022-12-22,22200478,1610612764,112.0,0.561,0.333,20.0,37.0,1610612762,120.0,0.488,0.457,16.0,40.0,0,0.0,2022-12-20 00:00:00.000000,2,None,0,0,0,2022-2023,2023,82,82,30,2022-10-18 00:00:00.000000,2023-04-16 00:00:00.000000,2023-06-16 00:00:00.000000,1,0,0,33,82,0.402439,113.5625,0.467406,0.371375,24.15625,43.84375,1610612762,NaN,NaN,NaN,NaN,1.0,0.0,116.029412,0.481088,...,NaN,NaN,0.162775,0.237682,0.214555,NaN,NaN,0.238152,0.073697,0.080388,NaN,NaN,0.201283,1.221245e-16,0.011797,NaN,NaN,0.019468,0.056855,0.050708,NaN,NaN,0.027135,0.058439,0.047269,NaN,NaN,0.312678,0.348834,0.343567,NaN,NaN,0.550860,-0.435852,-0.549609,NaN,NaN,0.084188,0.158087,0.128459,NaN,0.0,0.666667,0.5,0.6250,NaN,NaN,0.764706,0.833333,0.6
766371,2022-12-22,22200478,1610612764,112.0,0.561,0.333,20.0,37.0,1610612762,120.0,0.488,0.457,16.0,40.0,0,0.0,2022-12-20 00:00:00.000000,2,None,0,0,0,2022-2023,2023,82,82,30,2022-10-18 00:00:00.000000,2023-04-16 00:00:00.000000,2023-06-16 00:00:00.000000,1,0,0,33,82,0.402439,113.5625,0.467406,0.371375,24.15625,43.84375,1610612762,NaN,NaN,NaN,NaN,1.0,0.0,116.029412,0.481088,...,NaN,0.059940,0.169993,0.224650,0.153259,NaN,0.059940,0.108359,0.066731,0.087344,NaN,1.443290e-15,0.057052,5.316321e-03,0.015275,NaN,0.0,0.026686,0.052695,0.025638,NaN,0.0,0.027135,0.048699,0.030556,NaN,0.359640,0.428174,0.365123,0.389463,NaN,-0.839161,0.110949,-0.272832,-0.609549,NaN,0.059940,0.105843,0.153004,0.127059,NaN,0.5,0.666667,0.6,0.6250,NaN,NaN,0.764706,0.800000,0.6
766372,2022-12-22,22200478,1610612764,112.0,0.561,0.333,20.0,37.0,1610612762,120.0,0.488,0.457,16.0,40.0,0,0.0,2022-12-20 00:00:00.000000,2,None,0,0,0,2022-2023,2023,82,82,30,2022-10-18 00:00:00.000000,2023-04-16 00:00:00.000000,2023-06-16 00:00:00.000000,1,0,0,33,82,0.402439,113.5625,0.467406,0.371375,24.15625,43.84375,1610612762,NaN,NaN,NaN,NaN,1.0,0.0,116.029412,0.481088,...,NaN,0.059940,0.135807,0.245263,0.153259,NaN,0.059940,0.105542,0.061840,0.087344,NaN,1.443290e-15,0.063091,6.379585e-03,0.015275,NaN,0.0,0.009625,0.057155,0.025638,NaN,0.0,0.023202,0.052360,0.030556,NaN,0.359640,0.428134,0.353042,0.389463,NaN,-0.839161,0.160911,-0.297004,-0.609549,NaN,0.059940,0.115167,0.171447,0.127059,NaN,0.5,0.500000,0.5,0.6250,NaN,NaN,0.764706,0.750000,0.6
766373,2022-12-22,22200478,1610612764,112.0,0.561,0.333,20.0,37.0,1610612762,120.0,0.488,0.457,16.0,40.0,0,0.0,2022-12-20 00:00:00.000000,2,None,0,0,0,2022-2023,2023,82,82,30,2022-10-18 00:00:00.000000,2023-04-16 00:00:00.000000,2023-06-16 00:00:00.000000,1,0,0,33,82,0.402439,113.5625,0.467406,0.371375,24.15625,43.84375,1610612762,NaN,NaN,NaN,NaN,1.0,0.0,116.029412,0.481088,...,NaN,0.367133,0.082462,0.283272,0.148181,NaN,0.262238,0.145099,0.029010,0.088259,NaN,1.443290e-15,0.028289,6.379585e-03,0.018314,NaN,0.0,0.025885,0.057155,0.032162,NaN,0.0,0.032520,0.058695,0.027778,NaN,0.367133,0.518847,0.301550,0.393904,NaN,0.524476,0.163004,-0.460681,-0.589554,NaN,0.104895,0.073423,0.191950,0.128790,NaN,0.5,0.500000,0.5,0.6875,NaN,NaN,0.764706,1.000000,0.6
766374,2022-12-22,22200478,1610612764,112.0,0.561,0.333,20.0,37.0,1610612762,120.0,0.488,0.457,16.0,40.0,0,0.0,2022-12-20 00:00:00.000000,2,None,0,0,0,2022-2023,2023,82,82,30,2022-10-18 00:00:00.000000,2023-04-16 00:00:00.000000,2023-06-16 00:00:00.000000,1,0,0,33,82,0.402439,113.5625,0.467406,0.371375,24.15625,43.84375,1610612762,NaN,NaN,NaN,NaN,1.0,0.0,116.029412,0.481088,...,NaN,0.367133,0.082462,0.283272,0.148181,NaN,0.262238,0.145099,0.029010,0.088259,NaN,1.443290e-15,0.028289,6.379585e-03,0.018314,NaN,0.0,0.025885,0.057155,0.032162,NaN,0.0,0.032520,0.058695,0.027778,NaN,0.367133,0.518847,0.301550,0.393904,NaN,0.524476,0.163004,-0.460681,-0.589554,NaN,0.104895,0.073423,0.191950,0.128790,NaN,0.5,0.500000,0.5,0.6875,NaN,NaN,0.764706,1.000000,0.6

In [45]:
print(created_game_lag_cols)
print(created_window_lag_cols)
print(created_label_lag_cols)
print(created_window_avg_cols)
print(created_back_to_back_window_cols)

['lag_1_START_POSITION', 'lag_1_comment_code', 'lag_1_comment_reason']
['lag_1_MIN', 'lag_1_FGM_pm', 'lag_1_FGA_pm', 'lag_1_FG3M_pm', 'lag_1_FG3A_pm', 'lag_1_FTM_pm', 'lag_1_FTA_pm', 'lag_1_REB_pm', 'lag_1_AST_pm', 'lag_1_STL_pm', 'lag_1_BLK_pm', 'lag_1_TO_pm', 'lag_1_PTS_pm', 'lag_1_PLUS_MINUS_pm', 'lag_1_PF_pm', 'lag_1_game_played']
['next_0_MIN', 'next_1_MIN', 'next_2_MIN', 'next_3_MIN', 'next_4_MIN', 'next_0_FGM', 'next_1_FGM', 'next_2_FGM', 'next_3_FGM', 'next_4_FGM', 'next_0_FGA', 'next_1_FGA', 'next_2_FGA', 'next_3_FGA', 'next_4_FGA', 'next_0_FG3M', 'next_1_FG3M', 'next_2_FG3M', 'next_3_FG3M', 'next_4_FG3M', 'next_0_FG3A', 'next_1_FG3A', 'next_2_FG3A', 'next_3_FG3A', 'next_4_FG3A', 'next_0_FTM', 'next_1_FTM', 'next_2_FTM', 'next_3_FTM', 'next_4_FTM', 'next_0_FTA', 'next_1_FTA', 'next_2_FTA', 'next_3_FTA', 'next_4_FTA', 'next_0_REB', 'next_1_REB', 'next_2_REB', 'next_3_REB', 'next_4_REB', 'next_0_AST', 'next_1_AST', 'next_2_AST', 'next_3_AST', 'next_4_AST', 'next_0_STL', 'next_1_STL', 'next_2_STL', 'next_3_STL', 'next_4_STL', 'next_0_BLK', 'next_1_BLK', 'next_2_BLK', 'next_3_BLK', 'next_4_BLK', 'next_0_TO', 'next_1_TO', 'next_2_TO', 'next_3_TO', 'next_4_TO', 'next_0_PTS', 'next_1_PTS', 'next_2_PTS', 'next_3_PTS', 'next_4_PTS', 'next_0_PLUS_MINUS', 'next_1_PLUS_MINUS', 'next_2_PLUS_MINUS', 'next_3_PLUS_MINUS', 'next_4_PLUS_MINUS', 'next_0_PF', 'next_1_PF', 'next_2_PF', 'next_3_PF', 'next_4_PF']
['avg_2_3_MIN', 'avg_4_9_MIN', 'avg_10_19_MIN', 'avg_20_35_MIN', 'avg_36_85_MIN', 'avg_2_3_FGM_pm', 'avg_4_9_FGM_pm', 'avg_10_19_FGM_pm', 'avg_20_35_FGM_pm', 'avg_36_85_FGM_pm', 'avg_2_3_FGA_pm', 'avg_4_9_FGA_pm', 'avg_10_19_FGA_pm', 'avg_20_35_FGA_pm', 'avg_36_85_FGA_pm', 'avg_2_3_FG3M_pm', 'avg_4_9_FG3M_pm', 'avg_10_19_FG3M_pm', 'avg_20_35_FG3M_pm', 'avg_36_85_FG3M_pm', 'avg_2_3_FG3A_pm', 'avg_4_9_FG3A_pm', 'avg_10_19_FG3A_pm', 'avg_20_35_FG3A_pm', 'avg_36_85_FG3A_pm', 'avg_2_3_FTM_pm', 'avg_4_9_FTM_pm', 'avg_10_19_FTM_pm', 'avg_20_35_FTM_pm', 'avg_36_85_FTM_pm', 'avg_2_3_FTA_pm', 'avg_4_9_FTA_pm', 'avg_10_19_FTA_pm', 'avg_20_35_FTA_pm', 'avg_36_85_FTA_pm', 'avg_2_3_REB_pm', 'avg_4_9_REB_pm', 'avg_10_19_REB_pm', 'avg_20_35_REB_pm', 'avg_36_85_REB_pm', 'avg_2_3_AST_pm', 'avg_4_9_AST_pm', 'avg_10_19_AST_pm', 'avg_20_35_AST_pm', 'avg_36_85_AST_pm', 'avg_2_3_STL_pm', 'avg_4_9_STL_pm', 'avg_10_19_STL_pm', 'avg_20_35_STL_pm', 'avg_36_85_STL_pm', 'avg_2_3_BLK_pm', 'avg_4_9_BLK_pm', 'avg_10_19_BLK_pm', 'avg_20_35_BLK_pm', 'avg_36_85_BLK_pm', 'avg_2_3_TO_pm', 'avg_4_9_TO_pm', 'avg_10_19_TO_pm', 'avg_20_35_TO_pm', 'avg_36_85_TO_pm', 'avg_2_3_PTS_pm', 'avg_4_9_PTS_pm', 'avg_10_19_PTS_pm', 'avg_20_35_PTS_pm', 'avg_36_85_PTS_pm', 'avg_2_3_PLUS_MINUS_pm', 'avg_4_9_PLUS_MINUS_pm', 'avg_10_19_PLUS_MINUS_pm', 'avg_20_35_PLUS_MINUS_pm', 'avg_36_85_PLUS_MINUS_pm', 'avg_2_3_PF_pm', 'avg_4_9_PF_pm', 'avg_10_19_PF_pm', 'avg_20_35_PF_pm', 'avg_36_85_PF_pm', 'avg_2_3_game_played', 'avg_4_9_game_played', 'avg_10_19_game_played', 'avg_20_35_game_played', 'avg_36_85_game_played']
['avg_1_20_played_in_first_game_of_back_to_back', 'avg_21_90_played_in_first_game_of_back_to_back', 'avg_1_20_played_in_second_game_of_back_to_back', 'avg_21_90_played_in_second_game_of_back_to_back']

### Team-Season-level stats (NO LONGER USED)

In [46]:
# ## TODO: Create a table of team-season level stats
# # get team-season level stats
# df_team_season_stats = df_gamedays_fc.groupby(['TEAM_ID', 'season_short', ], as_index=False).agg({
#     'TEAM_PTS': ['mean'],
#     'TEAM_FG_PCT': ['mean'],
#     'TEAM_FG3_PCT': ['mean'],
#     'TEAM_AST': ['mean'],
#     'TEAM_REB': ['mean'],
#     'OPP_TEAM_PTS': ['mean'],
#     'OPP_TEAM_FG_PCT': ['mean'],
#     'OPP_TEAM_FG3_PCT': ['mean'],
#     'OPP_TEAM_AST': ['mean'],
#     'OPP_TEAM_REB': ['mean'],
#     'WIN': ['mean'],
# })
# df_team_season_stats.columns = ['_'.join(col).strip() for col in df_team_season_stats.columns.values]
# df_team_season_stats.rename(columns={'TEAM_ID_': 'TEAM_ID', 'season_short_': 'season_short'}, inplace=True)
# df_team_season_stats

In [47]:
# ## get last seasons team stats
# df_team_season_stats_ts = df_team_season_stats.copy().sort_values(by=['TEAM_ID', 'season_short'])

# group_cols = ['TEAM_ID']
# team_season_stats_cols = ['TEAM_PTS_mean', 'TEAM_FG_PCT_mean',
#        'TEAM_FG3_PCT_mean', 'TEAM_AST_mean', 'TEAM_REB_mean',
#        'OPP_TEAM_PTS_mean', 'OPP_TEAM_FG_PCT_mean', 'OPP_TEAM_FG3_PCT_mean',
#        'OPP_TEAM_AST_mean', 'OPP_TEAM_REB_mean', 'WIN_mean']

# df_team_season_stats_ts, created_team_season_stats_cols = get_all_lags(
#     df=df_team_season_stats, group_cols=group_cols, cols=team_season_stats_cols, n_lags=1)

# df_team_season_stats_ts.drop(columns=team_season_stats_cols, inplace=True)
# df_team_season_stats_ts.columns = [col.replace('mean', 'season') for col in df_team_season_stats_ts.columns]
# df_team_season_stats_ts

### Final Timeseries dataframe

In [48]:
## join df_gamedays_ts to team season level stats and player season level stats
# df_gamedays_ts = df_gamedays_ts.merge(df_team_season_stats_ts, on=['TEAM_ID', 'season_short'], how='left')
df_gamedays_ts_final = df_gamedays_ts.merge(df_player_season_stats_ts, on=['PLAYER_ID', 'SEASON'], how='left')

df_gamedays_ts_final

,GAME_DATE_EST,GAME_ID,TEAM_ID,TEAM_PTS,TEAM_FG_PCT,TEAM_FG3_PCT,TEAM_AST,TEAM_REB,OPP_TEAM_ID,OPP_TEAM_PTS,OPP_TEAM_FG_PCT,OPP_TEAM_FG3_PCT,OPP_TEAM_AST,OPP_TEAM_REB,HOME,WIN,last_game_date,days_since_last_game,next_game_date,days_until_next_game,first_back_to_back,second_back_to_back,season,season_short,min_games,max_games,number_of_teams,preseason_end,postseason_start,postseason_end,regular_season,preseason,postseason,game_number_of_season,total_regular_season_games,percentage_regular_season_games,TEAM_PTS_opp_per_game,TEAM_FG_PCT_opp_per_game,TEAM_FG3_PCT_opp_per_game,TEAM_AST_opp_per_game,TEAM_REB_opp_per_game,next_0_OPP_TEAM_ID,next_1_OPP_TEAM_ID,next_2_OPP_TEAM_ID,next_3_OPP_TEAM_ID,next_4_OPP_TEAM_ID,next_0_HOME,next_0_days_until_next_game,next_0_PTS_ALLOWED,next_0_FG_PCT_ALLOWED,...,lag_1_FGM_pm_season,lag_2_FGM_pm_season,lag_1_FGA_pm_season,lag_2_FGA_pm_season,lag_1_FG3M_pm_season,lag_2_FG3M_pm_season,lag_1_FG3A_pm_season,lag_2_FG3A_pm_season,lag_1_FTM_pm_season,lag_2_FTM_pm_season,lag_1_FTA_pm_season,lag_2_FTA_pm_season,lag_1_REB_pm_season,lag_2_REB_pm_season,lag_1_AST_pm_season,lag_2_AST_pm_season,lag_1_STL_pm_season,lag_2_STL_pm_season,lag_1_BLK_pm_season,lag_2_BLK_pm_season,lag_1_TO_pm_season,lag_2_TO_pm_season,lag_1_PTS_pm_season,lag_2_PTS_pm_season,lag_1_PLUS_MINUS_pm_season,lag_2_PLUS_MINUS_pm_season,lag_1_PF_pm_season,lag_2_PF_pm_season,lag_1_played_in_first_game_of_back_to_back_season,lag_2_played_in_first_game_of_back_to_back_season,lag_1_played_in_second_game_of_back_to_back_season,lag_2_played_in_second_game_of_back_to_back_season,avg_3_22_MIN_season,avg_3_22_game_played_season,avg_3_22_FGM_pm_season,avg_3_22_FGA_pm_season,avg_3_22_FG3M_pm_season,avg_3_22_FG3A_pm_season,avg_3_22_FTM_pm_season,avg_3_22_FTA_pm_season,avg_3_22_REB_pm_season,avg_3_22_AST_pm_season,avg_3_22_STL_pm_season,avg_3_22_BLK_pm_season,avg_3_22_TO_pm_season,avg_3_22_PTS_pm_season,avg_3_22_PLUS_MINUS_pm_season,avg_3_22_PF_pm_season,avg_3_22_played_in_first_game_of_back_to_back_season,avg_3_22_played_in_second_game_of_back_to_back_season
0,2003-10-28,20300003,1610612742,93.0,0.376,0.280,17.0,46.0,1610612747,109.0,0.506,0.350,32.0,46.0,0,0.0,2003-10-22 00:00:00.000000,6,2003-10-29 00:00:00.000000,1,1,0,2003-2004,2004,82,82,29,2003-10-28 00:00:00.000000,2004-04-17 00:00:00.000000,2004-06-15 00:00:00.000000,1,0,0,1,82,0.012195,NaN,NaN,NaN,NaN,NaN,1610612747,1.610613e+09,1.610613e+09,1.610613e+09,1.610613e+09,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28.672122,0.774390,0.169565,0.341332,0.007279,0.022493,0.101090,0.127094,0.148801,0.080661,0.033077,0.016190,0.057143,0.447499,0.017010,0.074397,0.788049,0.690149
1,2003-10-28,20300003,1610612742,93.0,0.376,0.280,17.0,46.0,1610612747,109.0,0.506,0.350,32.0,46.0,0,0.0,2003-10-22 00:00:00.000000,6,2003-10-29 00:00:00.000000,1,1,0,2003-2004,2004,82,82,29,2003-10-28 00:00:00.000000,2004-04-17 00:00:00.000000,2004-06-15 00:00:00.000000,1,0,0,1,82,0.012195,NaN,NaN,NaN,NaN,NaN,1610612747,1.610613e+09,1.610613e+09,1.610613e+09,1.610613e+09,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.539626,0.646575,0.111262,0.243878,0.000039,0.000955,0.069656,0.089983,0.222647,0.027335,0.021747,0.054894,0.041728,0.292220,-0.079778,0.124069,0.628401,0.604599
2,2003-10-28,20300003,1610612742,93.0,0.376,0.280,17.0,46.0,1610612747,109.0,0.506,0.350,32.0,46.0,0,0.0,2003-10-22 00:00:00.000000,6,2003-10-29 00:00:00.000000,1,1,0,2003-2004,2004,82,82,29,2003-10-28 00:00:00.000000,2004-04-17 00:00:00.000000,2004-06-15 00:00:00.000000,1,0,0,1,82,0.012195,NaN,NaN,NaN,NaN,NaN,1610612747,1.610613e+09,1.610613e+09,1.610613e+09,1.610613e+09,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.341347,0.721907,0.185073,0.405329,0.014291,0.051599,0.101741,0.121639,0.210749,0.099190,0.032401,0.021534,0.065733,0.486177,0.072570,0.066026,0.743023,0.733186
3,2003-10-28,20300003,1610612742,93.0,0.376,0.280,17.0,46.0,1610612747,109.0,0.506,0.350,32.0,46.0,0,0.0,2003-10-22 00:00:00.000000,6,2003-10-29 00:00:00.000000,1,1,0,2003-2004,2004,82,82,29,2003-10-28 00:00:00.000000,2004-04-17 00:00:00.000000,2004-06-15 00:00:00.000000,1,0,0,1,82,0.012195,NaN,NaN,NaN,NaN,NaN,1610612747,1.610613e+09,1.610613e+09,1.610613e+09,1.610613e+09,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33.410813,0.938230,0.158951,0.375386,0.045610,0.128687,0.051073,0.065012,0.183085,0.089411,0.030343,0.035868,0.046011,0.414585,0.094791,0.082073,0.946506,0.922325
4,2003-10-28,20300003,1610612742,93.0,0.376,0.280,17.0,46.0,1610612747,109.0,0.506,0.350,32.0,46.0,0,0.0,2003-10-22 00:00:00.000000,6,2003-10-29 00:00:00.000000,1,1,0,2003-2004,2004,82,82,29,2003-10-28 00:00:00.000000,2004-04-17 00:00:00.000000,2004-06-15 00:00:00.000000,1,0,0,1,82,0.012195,NaN,NaN,NaN,NaN,NaN,1610612747,1.610613e+09,1.610613e+09,1.610613e+09,1.610613e+09,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36.343135,0.827479,0.186777,0.408939,0.048654,0.126369,0.106710,0.123115,0.117914,0.110124,0.030211,0.006206,0.060625,0.528917,0.037154,0.061376,0.821777,0.781969
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
766370,2022-12-22,22200478,1610612764,112.0,0.561,0.333,20.0,37.0,1610612762,120.0,0.488,0.457,16.0,40.0,0,0.0,2022-12-20 00:00:00.000000,2,None,0,0,0,2022-2023,2023,82,82,30,2022-10-18 00:00:00.000000,2023-04-16 00:00:00.000000,2023-06-16 00:00:00.000000,1,0,0,33,82,0.402439,113.5625,0.467406,0.371375,24.15625,43.84375,1610612762,NaN,NaN,NaN,NaN,1.0,0.0,116.029412,0.481088,...,0.120657,0.121661,0.185861,0.239585,0.035188,0.030633,0.050579,0.102468,0.106986,0.06209,0.126342,0.081839,0.178215,0.213316,0.038707,0.050222,0.005978,0.028286,0.027033,0.031378,0.033855,0.021783,0.383487,0.336044,0.033790,-0.375556,0.094069,0.140757,0.500000,0.294118,0.571429,0.352941,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
766371,2022-12-22,22200478,1610612764,112.0,0.561,0.333,20.0,37.0,1610612762,120.0,0.488,0.457,16.0,40.0,0,0.0,2022-12-20 00:00:00.000000,2,None,0,0,0,2022-2023,2023,82,82,30,2022-10-18 00:00:00.000000,2023-04-16 00:00:00.000000,2023-06-16 00:00:00.000000,1,0,0,33,82,0.402439,113.5625,0.467406,0.371375,24.15625,43.84375,1610612762,NaN,NaN,NaN,NaN,1.0,0.0,116.029412,0.481088,...,0.121389,NaN,0.277505,NaN,0.052125,NaN,0.166700,NaN,0.035007,NaN,0.041063,NaN,0.123289,NaN,0.047480,NaN,0.019023,NaN,0.014566,NaN,0.027348,NaN,0.329910,NaN,0.059373,NaN,0.050407,NaN,0.857143,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
766372,2022-12-22,22200478,1610612764,112.0,0.561,0.333,20.0,37.0,1610612762,120.0,0.488,0.457,16.0,40.0,0,0.0,2022-12-20 00:00:00.000000,2,None,0,0,0,2022-2023,2023,82,82,30,2022-10-18 00:00:00.000000,2023-04-16 00:00:00.000000,2023-06-16 00:00:00.000000,1,0,0,33,82,0.402439,113.5625,0.467406,0.371375,24.15625,43.84375,1610612762,NaN,NaN,NaN,NaN,1.0,0.0,116.029412,0.481088,...,0.027778,NaN,0.329690,NaN,0.027778,NaN,0.192623,NaN,0.055556,NaN,0.055556,NaN,0.249545,NaN,0.000000,NaN,0.027778,NaN,0.000000,NaN,0.027778,NaN,0.138889,NaN,0.145719,NaN,0.000000,NaN,0.000000,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
766373,2022-12-22,22200478,1610612764,112.0,0.561,0.333,20.0,37.0,1610612762,120.0,0.488,0.457,16.0,40.0,0,0.0,2022-12-20 00:00:00.000000,2,None,0,0,0,2022-2023,2023,82,82,30,2022-10-18 00:00:00.000000,2023-04-16 00:00:00.000000,2023-06-16 00:00:00.000000,1,0,0,33,82,0.402439,113.5625,0.467406,0.371375,24.15625,43.84375,1610612762,NaN,NaN,NaN,NaN,1.0,0.0,116.029412,0.481088,...,0.000000,NaN,0.511881,NaN,0.000000,NaN,0.163043,NaN,0.000000,NaN,0.000000,NaN,0.163043,NaN,0.000000,NaN,0.000000,NaN,0.000000,NaN,0.000000,NaN,0.000000,NaN,-1.383974,NaN,0.163043,NaN,0.000000,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
766374,2022-12-22,22200478,1610612764,112.0,0.561,0.333,20.0,37.0,1610612762,120.0,0.488,0.457,16.0,40.0,0,0.0,2022-12-20 00:00:00.000000,2,None,0,0,0,2022-2023,2023,82,82,30,2022-10-18 00:00:00.000000,2023-04-16 00:00:00.000000,2023-06-16 00:00:00.000000,1,0,0,33,82,0.402439,113.5625,0.467406,0.371375,24.15625,43.84375,1610612762,NaN,NaN,NaN,NaN,1.0,0.0,116.029412,0.481088,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [49]:
## get data for player id 201935 and export to csv
# df_gamedays_ts[df_gamedays_ts['PLAYER_ID'] == 201935].sort_values(by=['GAME_DATE_EST']).to_csv(data_path + '201935 (James Harden) data.csv', index=False)

In [50]:
new_cols = [col for col in df_gamedays_ts_final.columns if col not in do_not_include + labels + last_game_cols + all_window_cols]
new_cols = index_cols + [col for col in new_cols if col not in index_cols]
for i in range(int(len(new_cols)/10)+1):
    try:
        print(i, list(new_cols[i*10:(i+1)*10]))
    except:
        print(i, list(new_cols[i*10:]))
        break

0 ['GAME_DATE_EST', 'GAME_ID', 'TEAM_ID', 'PLAYER_ID', 'PLAYER_NAME', 'season', 'days_since_last_game', 'season_short', 'percentage_regular_season_games', 'next_0_HOME']
1 ['next_0_days_until_next_game', 'next_0_PTS_ALLOWED', 'next_0_FG_PCT_ALLOWED', 'next_0_FG3_PCT_ALLOWED', 'next_0_AST_ALLOWED', 'next_0_REB_ALLOWED', 'next_1_HOME', 'next_1_days_until_next_game', 'next_1_PTS_ALLOWED', 'next_1_FG_PCT_ALLOWED']
2 ['next_1_FG3_PCT_ALLOWED', 'next_1_AST_ALLOWED', 'next_1_REB_ALLOWED', 'next_2_HOME', 'next_2_days_until_next_game', 'next_2_PTS_ALLOWED', 'next_2_FG_PCT_ALLOWED', 'next_2_FG3_PCT_ALLOWED', 'next_2_AST_ALLOWED', 'next_2_REB_ALLOWED']
3 ['next_3_HOME', 'next_3_days_until_next_game', 'next_3_PTS_ALLOWED', 'next_3_FG_PCT_ALLOWED', 'next_3_FG3_PCT_ALLOWED', 'next_3_AST_ALLOWED', 'next_3_REB_ALLOWED', 'next_4_HOME', 'next_4_days_until_next_game', 'next_4_PTS_ALLOWED']
4 ['next_4_FG_PCT_ALLOWED', 'next_4_FG3_PCT_ALLOWED', 'next_4_AST_ALLOWED', 'next_4_REB_ALLOWED', 'next_game_played_date', 'last_game_played_date', 'lag_1_START_POSITION', 'lag_1_comment_code', 'lag_1_comment_reason', 'lag_1_MIN']
5 ['lag_1_FGM_pm', 'lag_1_FGA_pm', 'lag_1_FG3M_pm', 'lag_1_FG3A_pm', 'lag_1_FTM_pm', 'lag_1_FTA_pm', 'lag_1_REB_pm', 'lag_1_AST_pm', 'lag_1_STL_pm', 'lag_1_BLK_pm']
6 ['lag_1_TO_pm', 'lag_1_PTS_pm', 'lag_1_PLUS_MINUS_pm', 'lag_1_PF_pm', 'lag_1_game_played', 'next_0_MIN', 'next_1_MIN', 'next_2_MIN', 'next_3_MIN', 'next_4_MIN']
7 ['next_0_FGM', 'next_1_FGM', 'next_2_FGM', 'next_3_FGM', 'next_4_FGM', 'next_0_FGA', 'next_1_FGA', 'next_2_FGA', 'next_3_FGA', 'next_4_FGA']
8 ['next_0_FG3M', 'next_1_FG3M', 'next_2_FG3M', 'next_3_FG3M', 'next_4_FG3M', 'next_0_FG3A', 'next_1_FG3A', 'next_2_FG3A', 'next_3_FG3A', 'next_4_FG3A']
9 ['next_0_FTM', 'next_1_FTM', 'next_2_FTM', 'next_3_FTM', 'next_4_FTM', 'next_0_FTA', 'next_1_FTA', 'next_2_FTA', 'next_3_FTA', 'next_4_FTA']
10 ['next_0_REB', 'next_1_REB', 'next_2_REB', 'next_3_REB', 'next_4_REB', 'next_0_AST', 'next_1_AST', 'next_2_AST', 'next_3_AST', 'next_4_AST']
11 ['next_0_STL', 'next_1_STL', 'next_2_STL', 'next_3_STL', 'next_4_STL', 'next_0_BLK', 'next_1_BLK', 'next_2_BLK', 'next_3_BLK', 'next_4_BLK']
12 ['next_0_TO', 'next_1_TO', 'next_2_TO', 'next_3_TO', 'next_4_TO', 'next_0_PTS', 'next_1_PTS', 'next_2_PTS', 'next_3_PTS', 'next_4_PTS']
13 ['next_0_PLUS_MINUS', 'next_1_PLUS_MINUS', 'next_2_PLUS_MINUS', 'next_3_PLUS_MINUS', 'next_4_PLUS_MINUS', 'next_0_PF', 'next_1_PF', 'next_2_PF', 'next_3_PF', 'next_4_PF']
14 ['avg_2_3_MIN', 'avg_4_9_MIN', 'avg_10_19_MIN', 'avg_20_35_MIN', 'avg_36_85_MIN', 'avg_2_3_FGM_pm', 'avg_4_9_FGM_pm', 'avg_10_19_FGM_pm', 'avg_20_35_FGM_pm', 'avg_36_85_FGM_pm']
15 ['avg_2_3_FGA_pm', 'avg_4_9_FGA_pm', 'avg_10_19_FGA_pm', 'avg_20_35_FGA_pm', 'avg_36_85_FGA_pm', 'avg_2_3_FG3M_pm', 'avg_4_9_FG3M_pm', 'avg_10_19_FG3M_pm', 'avg_20_35_FG3M_pm', 'avg_36_85_FG3M_pm']
16 ['avg_2_3_FG3A_pm', 'avg_4_9_FG3A_pm', 'avg_10_19_FG3A_pm', 'avg_20_35_FG3A_pm', 'avg_36_85_FG3A_pm', 'avg_2_3_FTM_pm', 'avg_4_9_FTM_pm', 'avg_10_19_FTM_pm', 'avg_20_35_FTM_pm', 'avg_36_85_FTM_pm']
17 ['avg_2_3_FTA_pm', 'avg_4_9_FTA_pm', 'avg_10_19_FTA_pm', 'avg_20_35_FTA_pm', 'avg_36_85_FTA_pm', 'avg_2_3_REB_pm', 'avg_4_9_REB_pm', 'avg_10_19_REB_pm', 'avg_20_35_REB_pm', 'avg_36_85_REB_pm']
18 ['avg_2_3_AST_pm', 'avg_4_9_AST_pm', 'avg_10_19_AST_pm', 'avg_20_35_AST_pm', 'avg_36_85_AST_pm', 'avg_2_3_STL_pm', 'avg_4_9_STL_pm', 'avg_10_19_STL_pm', 'avg_20_35_STL_pm', 'avg_36_85_STL_pm']
19 ['avg_2_3_BLK_pm', 'avg_4_9_BLK_pm', 'avg_10_19_BLK_pm', 'avg_20_35_BLK_pm', 'avg_36_85_BLK_pm', 'avg_2_3_TO_pm', 'avg_4_9_TO_pm', 'avg_10_19_TO_pm', 'avg_20_35_TO_pm', 'avg_36_85_TO_pm']
20 ['avg_2_3_PTS_pm', 'avg_4_9_PTS_pm', 'avg_10_19_PTS_pm', 'avg_20_35_PTS_pm', 'avg_36_85_PTS_pm', 'avg_2_3_PLUS_MINUS_pm', 'avg_4_9_PLUS_MINUS_pm', 'avg_10_19_PLUS_MINUS_pm', 'avg_20_35_PLUS_MINUS_pm', 'avg_36_85_PLUS_MINUS_pm']
21 ['avg_2_3_PF_pm', 'avg_4_9_PF_pm', 'avg_10_19_PF_pm', 'avg_20_35_PF_pm', 'avg_36_85_PF_pm', 'avg_2_3_game_played', 'avg_4_9_game_played', 'avg_10_19_game_played', 'avg_20_35_game_played', 'avg_36_85_game_played']
22 ['avg_1_20_played_in_first_game_of_back_to_back', 'avg_21_90_played_in_first_game_of_back_to_back', 'avg_1_20_played_in_second_game_of_back_to_back', 'avg_21_90_played_in_second_game_of_back_to_back', 'lag_1_MIN_season', 'lag_2_MIN_season', 'lag_1_game_played_season', 'lag_2_game_played_season', 'lag_1_FGM_pm_season', 'lag_2_FGM_pm_season']
23 ['lag_1_FGA_pm_season', 'lag_2_FGA_pm_season', 'lag_1_FG3M_pm_season', 'lag_2_FG3M_pm_season', 'lag_1_FG3A_pm_season', 'lag_2_FG3A_pm_season', 'lag_1_FTM_pm_season', 'lag_2_FTM_pm_season', 'lag_1_FTA_pm_season', 'lag_2_FTA_pm_season']
24 ['lag_1_REB_pm_season', 'lag_2_REB_pm_season', 'lag_1_AST_pm_season', 'lag_2_AST_pm_season', 'lag_1_STL_pm_season', 'lag_2_STL_pm_season', 'lag_1_BLK_pm_season', 'lag_2_BLK_pm_season', 'lag_1_TO_pm_season', 'lag_2_TO_pm_season']
25 ['lag_1_PTS_pm_season', 'lag_2_PTS_pm_season', 'lag_1_PLUS_MINUS_pm_season', 'lag_2_PLUS_MINUS_pm_season', 'lag_1_PF_pm_season', 'lag_2_PF_pm_season', 'lag_1_played_in_first_game_of_back_to_back_season', 'lag_2_played_in_first_game_of_back_to_back_season', 'lag_1_played_in_second_game_of_back_to_back_season', 'lag_2_played_in_second_game_of_back_to_back_season']
26 ['avg_3_22_MIN_season', 'avg_3_22_game_played_season', 'avg_3_22_FGM_pm_season', 'avg_3_22_FGA_pm_season', 'avg_3_22_FG3M_pm_season', 'avg_3_22_FG3A_pm_season', 'avg_3_22_FTM_pm_season', 'avg_3_22_FTA_pm_season', 'avg_3_22_REB_pm_season', 'avg_3_22_AST_pm_season']
27 ['avg_3_22_STL_pm_season', 'avg_3_22_BLK_pm_season', 'avg_3_22_TO_pm_season', 'avg_3_22_PTS_pm_season', 'avg_3_22_PLUS_MINUS_pm_season', 'avg_3_22_PF_pm_season', 'avg_3_22_played_in_first_game_of_back_to_back_season', 'avg_3_22_played_in_second_game_of_back_to_back_season']

In [51]:
# ## TODO
# ## - Separate each column into predictors for: MIN, PTS, REB, AST, STL, BLK, TO, PF, FGM, FGA, FTM, FTA
# ## - Will need to add in missing features
# cat_features_min = ['HOME', 'lag_1_START_POSITION', 'lag_1_comment_code', 'lag_1_comment_reason', ]
# num_features_min = [
#     'days_since_last_game', 'days_until_next_game', 'season_short', 'percentage_regular_season_games', 'lag_1_MIN',
#     'lag_1_PLUS_MINUS_pm', 'lag_1_PF_pm', 
#     'avg_2_3_MIN', 'avg_4_9_MIN', 'avg_10_19_MIN', 'avg_20_35_MIN', 'avg_36_85_MIN',
#     'avg_2_3_PLUS_MINUS_pm', 'avg_4_9_PLUS_MINUS_pm', 'avg_10_19_PLUS_MINUS_pm', 'avg_20_35_PLUS_MINUS_pm', 'avg_36_85_PLUS_MINUS_pm',
#     'avg_2_3_PF_pm', 'avg_4_9_PF_pm', 'avg_10_19_PF_pm', 'avg_20_35_PF_pm', 'avg_36_85_PF_pm',
#     'avg_1_20_played_in_first_game_of_back_to_back', 'avg_21_90_played_in_first_game_of_back_to_back', 'avg_1_20_played_in_second_game_of_back_to_back',
#     'avg_21_90_played_in_second_game_of_back_to_back', 'avg_2_3_game_played', 'avg_4_9_game_played', 'avg_10_19_game_played', 'avg_20_35_game_played',
#     'avg_36_85_game_played', 'lag_1_MIN_season', 'lag_2_MIN_season', 'lag_1_game_played_season', 'lag_2_game_played_season',
#     'lag_1_PLUS_MINUS_pm_season', 'lag_2_PLUS_MINUS_pm_season', 'lag_1_PF_pm_season', 'lag_2_PF_pm_season', 'lag_1_played_in_first_game_of_back_to_back_season',
#     'lag_2_played_in_first_game_of_back_to_back_season', 'lag_1_played_in_second_game_of_back_to_back_season',
#     'lag_2_played_in_second_game_of_back_to_back_season', 'avg_3_22_MIN_season', 'avg_3_22_game_played_season', 'avg_3_22_PLUS_MINUS_pm_season',
#     'avg_3_22_PF_pm_season', 'avg_3_22_played_in_first_game_of_back_to_back_season', 'avg_3_22_played_in_second_game_of_back_to_back_season']
# features_min = cat_features_min + num_features_min

In [52]:
## export timeseries data
df_gamedays_ts_final[new_cols].to_csv(data_path + 'data_timeseries.csv', index=False)